### ISSUE TITLE
Issue when trying to save the predictor model in image classification

### ISSUE THREAD

**Issue by zenetio** [autogluon/autogluon#1029]
When I try to save the predictor model using the function **predictor.save()** I am getting the following error
Traceback (most recent call last):
  File "/home/carlao/projects/autogluon/examples/image_classification/benchmark.py", line 95, in <module>
    main()
  File "/home/carlao/projects/autogluon/examples/image_classification/benchmark.py", line 92, in main
    predictor.save()
  File "/home/carlao/projects/autogluon/vision/src/autogluon/vision/predictor/predictor.py", line 478, in save
    pickle.dump(self, fid)
AttributeError: Can't pickle local object 'config_choice.<locals>.NAG'

INFO:root:Namespace(batch_size=-1, custom='predict', data_dir='data/', dataset='dog-breed-identification', ngpus_per_trial=1, num_epochs=1, num_trials=-1)
Namespace(batch_size=-1, custom='predict', data_dir='data/', dataset='dog-breed-identification', ngpus_per_trial=1, num_epochs=1, num_trials=-1)
INFO:gluoncv.auto.tasks.image_classification:Randomly split train_data into train[9191]/validation[1031] splits.
Randomly split train_data into train[9191]/validation[1031] splits.
INFO:gluoncv.auto.tasks.image_classification:Starting fit without HPO
Starting fit without HPO
INFO:ImageClassificationEstimator:modified configs(<old> != <new>): {
modified configs(<old> != <new>): {
INFO:ImageClassificationEstimator:root.img_cls.model   resnet50_v1 != resnet50_v1b
root.img_cls.model   resnet50_v1 != resnet50_v1b
INFO:ImageClassificationEstimator:root.img_cls.last_gamma False != True
root.img_cls.last_gamma False != True
INFO:ImageClassificationEstimator:root.train.epochs    10 != 1
root.train.epochs    10 != 1
INFO:ImageClassificationEstimator:root.train.no_wd     False != True
root.train.no_wd     False != True
INFO:ImageClassificationEstimator:root.train.batch_size 128 != 48
root.train.batch_size 128 != 48
INFO:ImageClassificationEstimator:root.train.rec_val_idx ~/.mxnet/datasets/imagenet/rec/val.idx != auto
root.train.rec_val_idx ~/.mxnet/datasets/imagenet/rec/val.idx != auto
INFO:ImageClassificationEstimator:root.train.lr        0.1 != 0.01
root.train.lr        0.1 != 0.01
INFO:ImageClassificationEstimator:root.train.num_training_samples 1281167 != -1
root.train.num_training_samples 1281167 != -1
INFO:ImageClassificationEstimator:root.train.rec_train ~/.mxnet/datasets/imagenet/rec/train.rec != auto
root.train.rec_train ~/.mxnet/datasets/imagenet/rec/train.rec != auto
INFO:ImageClassificationEstimator:root.train.label_smoothing False != True
root.train.label_smoothing False != True
INFO:ImageClassificationEstimator:root.train.lr_mode   step != cosine
root.train.lr_mode   step != cosine
INFO:ImageClassificationEstimator:root.train.lr_decay_epoch 40, 60 != 60,120
root.train.lr_decay_epoch 40, 60 != 60,120
INFO:ImageClassificationEstimator:root.train.rec_val   ~/.mxnet/datasets/imagenet/rec/val.rec != auto
root.train.rec_val   ~/.mxnet/datasets/imagenet/rec/val.rec != auto
INFO:ImageClassificationEstimator:root.train.warmup_epochs 0 != 5
root.train.warmup_epochs 0 != 5
INFO:ImageClassificationEstimator:root.train.data_dir  ~/.mxnet/datasets/imagenet != auto
root.train.data_dir  ~/.mxnet/datasets/imagenet != auto
INFO:ImageClassificationEstimator:root.train.rec_train_idx ~/.mxnet/datasets/imagenet/rec/train.idx != auto
root.train.rec_train_idx ~/.mxnet/datasets/imagenet/rec/train.idx != auto
INFO:ImageClassificationEstimator:root.valid.batch_size 128 != 48
root.valid.batch_size 128 != 48
INFO:ImageClassificationEstimator:}
}
INFO:ImageClassificationEstimator:Saved config to /home/carlao/projects/autogluon/examples/image_classification/dog-breed-identification/checkpoint/e5494d05/.trial_0/config.yaml
Saved config to /home/carlao/projects/autogluon/examples/image_classification/dog-breed-identification/checkpoint/e5494d05/.trial_0/config.yaml
INFO:ImageClassificationEstimator:Start training from [Epoch 0]
Start training from [Epoch 0]
[23:31:48] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:ImageClassificationEstimator:Epoch[0] Batch [49]   Speed: 29.822947 samples/sec    accuracy=0.010417       lr=0.000524
Epoch[0] Batch [49]     Speed: 29.822947 samples/sec    accuracy=0.010417       lr=0.000524
INFO:ImageClassificationEstimator:Epoch[0] Batch [99]   Speed: 59.025596 samples/sec    accuracy=0.009375       lr=0.001048
Epoch[0] Batch [99]     Speed: 59.025596 samples/sec    accuracy=0.009375       lr=0.001048
INFO:ImageClassificationEstimator:Epoch[0] Batch [149]  Speed: 62.207178 samples/sec    accuracy=0.011250       lr=0.001572
Epoch[0] Batch [149]    Speed: 62.207178 samples/sec    accuracy=0.011250       lr=0.001572
INFO:ImageClassificationEstimator:Epoch[0] Batch [199]  Speed: 67.868545 samples/sec    accuracy=0.012083       lr=0.002096
Epoch[0] Batch [199]    Speed: 67.868545 samples/sec    accuracy=0.012083       lr=0.002096
INFO:ImageClassificationEstimator:[Epoch 0] training: accuracy=0.012579
[Epoch 0] training: accuracy=0.012579
INFO:ImageClassificationEstimator:[Epoch 0] speed: 49 samples/sec       time cost: 242.924523
[Epoch 0] speed: 49 samples/sec time cost: 242.924523
INFO:ImageClassificationEstimator:[Epoch 0] validation: top1=0.016435 top5=0.067697
[Epoch 0] validation: top1=0.016435 top5=0.067697
INFO:ImageClassificationEstimator:[Epoch 0] Current best top-1: 0.016435 vs previous 0.000000, saved to /home/carlao/projects/autogluon/examples/image_classification/dog-breed-identification/checkpoint/e5494d05/.trial_0/best_checkpoint.pkl
[Epoch 0] Current best top-1: 0.016435 vs previous 0.000000, saved to /home/carlao/projects/autogluon/examples/image_classification/dog-breed-identification/checkpoint/e5494d05/.trial_0/best_checkpoint.pkl
INFO:ImageClassificationEstimator:Pickled to /home/carlao/projects/autogluon/examples/image_classification/dog-breed-identification/checkpoint/e5494d05/.trial_0/best_checkpoint.pkl
Pickled to /home/carlao/projects/autogluon/examples/image_classification/dog-breed-identification/checkpoint/e5494d05/.trial_0/best_checkpoint.pkl
INFO:gluoncv.auto.tasks.image_classification:Finished, total runtime is 372.25 s
Finished, total runtime is 372.25 s
INFO:gluoncv.auto.tasks.image_classification:{ 'best_config': { 'batch_norm': False,
                   'batch_size': 48,
                   'custom_net': 'resnext101_64x4d',
                   'custom_optimizer': <kaggle_configuration.config_choice.<locals>.NAG object at 0x7f34feddfa90>,
                   'dist_ip_addrs': None,
                   'epochs': 1,
                   'estimator': <class 'gluoncv.auto.estimators.image_classification.image_classification.ImageClassificationEstimator'>,
                   'final_fit': False,
                   'gpus': [0],
                   'hard_weight': 0.5,
                   'label_smoothing': True,
                   'last_gamma': True,
                   'log_dir': 'dog-breed-identification/checkpoint/e5494d05',
                   'lr': 0.01,
                   'lr_decay': 0.1,
                   'lr_decay_epoch': '60,120',
                   'lr_decay_period': 0,
                   'lr_mode': 'cosine',
                   'mixup': False,
                   'mixup_alpha': 0.2,
                   'mixup_off_epoch': 0,
                   'model': 'resnet50_v1b',
                   'ngpus_per_trial': 1,
                   'no_wd': True,
                   'nthreads_per_trial': 128,
                   'num_trials': 1,
                   'num_workers': 4,
                   'search_strategy': 'random',
                   'seed': 745,
                   'teacher_name': None,
                   'temperature': 20.0,
                   'time_limits': 1800,
                   'use_gn': False,
                   'use_pretrained': True,
                   'use_se': False,
                   'wall_clock_tick': 1616554870.5903194,
                   'warmup_epochs': 5,
                   'warmup_lr': 0.0},
  'total_time': 328.90664768218994,
  'train_acc': 0.012578616352201259,
  'valid_acc': 0.01643513989434553}
{ 'best_config': { 'batch_norm': False,
                   'batch_size': 48,
                   'custom_net': 'resnext101_64x4d',
                   'custom_optimizer': <kaggle_configuration.config_choice.<locals>.NAG object at 0x7f34feddfa90>,
                   'dist_ip_addrs': None,
                   'epochs': 1,
                   'estimator': <class 'gluoncv.auto.estimators.image_classification.image_classification.ImageClassificationEstimator'>,
                   'final_fit': False,
                   'gpus': [0],
                   'hard_weight': 0.5,
                   'label_smoothing': True,
                   'last_gamma': True,
                   'log_dir': 'dog-breed-identification/checkpoint/e5494d05',
                   'lr': 0.01,
                   'lr_decay': 0.1,
                   'lr_decay_epoch': '60,120',
                   'lr_decay_period': 0,
                   'lr_mode': 'cosine',
                   'mixup': False,
                   'mixup_alpha': 0.2,
                   'mixup_off_epoch': 0,
                   'model': 'resnet50_v1b',
                   'ngpus_per_trial': 1,
                   'no_wd': True,
                   'nthreads_per_trial': 128,
                   'num_trials': 1,
                   'num_workers': 4,
                   'search_strategy': 'random',
                   'seed': 745,
                   'teacher_name': None,
                   'temperature': 20.0,
                   'time_limits': 1800,
                   'use_gn': False,
                   'use_pretrained': True,
                   'use_se': False,
                   'wall_clock_tick': 1616554870.5903194,
                   'warmup_epochs': 5,
                   'warmup_lr': 0.0},
  'total_time': 328.90664768218994,
  'train_acc': 0.012578616352201259,
  'valid_acc': 0.01643513989434553}
INFO:root:Top-1 val acc: 0.013
Top-1 val acc: 0.013
INFO:root:{'train_acc': 0.012578616352201259, 'valid_acc': 0.01643513989434553, 'total_time': 328.90664768218994, 'best_config': {'model': 'resnet50_v1b', 'lr': 0.01, 'num_trials': 1, 'epochs': 1, 'batch_size': 48, 'nthreads_per_trial': 128, 'ngpus_per_trial': 1, 'time_limits': 1800, 'search_strategy': 'random', 'dist_ip_addrs': None, 'log_dir': 'dog-breed-identification/checkpoint/e5494d05', 'custom_net': 'resnext101_64x4d', 'custom_optimizer': <kaggle_configuration.config_choice.<locals>.NAG object at 0x7f34feddfa90>, 'lr_mode': 'cosine', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '60,120', 'warmup_lr': 0.0, 'warmup_epochs': 5, 'last_gamma': True, 'use_pretrained': True, 'use_se': False, 'mixup': False, 'mixup_alpha': 0.2, 'mixup_off_epoch': 0, 'label_smoothing': True, 'no_wd': True, 'teacher_name': None, 'temperature': 20.0, 'hard_weight': 0.5, 'batch_norm': False, 'use_gn': False, 'num_workers': 4, 'gpus': [0], 'seed': 745, 'final_fit': False, 'estimator': <class 'gluoncv.auto.estimators.image_classification.image_classification.ImageClassificationEstimator'>, 'wall_clock_tick': 1616554870.5903194}, 'fit_history': {'train_acc': 0.012578616352201259, 'valid_acc': 0.01643513989434553, 'total_time': 328.90664768218994, 'best_config': {'model': 'resnet50_v1b', 'lr': 0.01, 'num_trials': 1, 'epochs': 1, 'batch_size': 48, 'nthreads_per_trial': 128, 'ngpus_per_trial': 1, 'time_limits': 1800, 'search_strategy': 'random', 'dist_ip_addrs': None, 'log_dir': 'dog-breed-identification/checkpoint/e5494d05', 'custom_net': 'resnext101_64x4d', 'custom_optimizer': <kaggle_configuration.config_choice.<locals>.NAG object at 0x7f34feddfa90>, 'lr_mode': 'cosine', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '60,120', 'warmup_lr': 0.0, 'warmup_epochs': 5, 'last_gamma': True, 'use_pretrained': True, 'use_se': False, 'mixup': False, 'mixup_alpha': 0.2, 'mixup_off_epoch': 0, 'label_smoothing': True, 'no_wd': True, 'teacher_name': None, 'temperature': 20.0, 'hard_weight': 0.5, 'batch_norm': False, 'use_gn': False, 'num_workers': 4, 'gpus': [0], 'seed': 745, 'final_fit': False, 'estimator': <class 'gluoncv.auto.estimators.image_classification.image_classification.ImageClassificationEstimator'>, 'wall_clock_tick': 1616554870.5903194}}}
{'train_acc': 0.012578616352201259, 'valid_acc': 0.01643513989434553, 'total_time': 328.90664768218994, 'best_config': {'model': 'resnet50_v1b', 'lr': 0.01, 'num_trials': 1, 'epochs': 1, 'batch_size': 48, 'nthreads_per_trial': 128, 'ngpus_per_trial': 1, 'time_limits': 1800, 'search_strategy': 'random', 'dist_ip_addrs': None, 'log_dir': 'dog-breed-identification/checkpoint/e5494d05', 'custom_net': 'resnext101_64x4d', 'custom_optimizer': <kaggle_configuration.config_choice.<locals>.NAG object at 0x7f34feddfa90>, 'lr_mode': 'cosine', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '60,120', 'warmup_lr': 0.0, 'warmup_epochs': 5, 'last_gamma': True, 'use_pretrained': True, 'use_se': False, 'mixup': False, 'mixup_alpha': 0.2, 'mixup_off_epoch': 0, 'label_smoothing': True, 'no_wd': True, 'teacher_name': None, 'temperature': 20.0, 'hard_weight': 0.5, 'batch_norm': False, 'use_gn': False, 'num_workers': 4, 'gpus': [0], 'seed': 745, 'final_fit': False, 'estimator': <class 'gluoncv.auto.estimators.image_classification.image_classification.ImageClassificationEstimator'>, 'wall_clock_tick': 1616554870.5903194}, 'fit_history': {'train_acc': 0.012578616352201259, 'valid_acc': 0.01643513989434553, 'total_time': 328.90664768218994, 'best_config': {'model': 'resnet50_v1b', 'lr': 0.01, 'num_trials': 1, 'epochs': 1, 'batch_size': 48, 'nthreads_per_trial': 128, 'ngpus_per_trial': 1, 'time_limits': 1800, 'search_strategy': 'random', 'dist_ip_addrs': None, 'log_dir': 'dog-breed-identification/checkpoint/e5494d05', 'custom_net': 'resnext101_64x4d', 'custom_optimizer': <kaggle_configuration.config_choice.<locals>.NAG object at 0x7f34feddfa90>, 'lr_mode': 'cosine', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '60,120', 'warmup_lr': 0.0, 'warmup_epochs': 5, 'last_gamma': True, 'use_pretrained': True, 'use_se': False, 'mixup': False, 'mixup_alpha': 0.2, 'mixup_off_epoch': 0, 'label_smoothing': True, 'no_wd': True, 'teacher_name': None, 'temperature': 20.0, 'hard_weight': 0.5, 'batch_norm': False, 'use_gn': False, 'num_workers': 4, 'gpus': [0], 'seed': 745, 'final_fit': False, 'estimator': <class 'gluoncv.auto.estimators.image_classification.image_classification.ImageClassificationEstimator'>, 'wall_clock_tick': 1616554870.5903194}}}

I am running Ubuntu 18.04 on WSL2

**Comment by Innixma** [comment]
Marking as resolved, use autogluon.mulit
