### ISSUE TITLE
AutoGluon stacking quality

### ISSUE THREAD

**Issue by qo4on** [autogluon/autogluon#1060]
What is the reason why `AutoGluon` shows significantly worse result compare to simple [one layer stacking](https://www.kaggle.com/sergeyzinchenko/predicting-a-biological-response)?
5 hours `best_quality` training gives private score `0.38131` compare to `0.37353` for 2 hours logistic regression.

![image](https://user-images.githubusercontent.com/35609308/114684468-61cdda00-9d2a-11eb-997c-eae94c984e89.png)

**Comment by Innixma** [comment]
Thanks for providing the kernel!

Logistic / Linear regression has been known to outperform greedy ensemble selection on some datasets (Greedy Ensemble Selection is what `WeightedEnsemble` is based on), so this may be the cause.

It's also possible that AutoGluon may have overfit to the cross-validation data from early-stopping.

There was also this trick in the kernel that may have contributed:

```
# Linear stretch of predictions to [0, 1]
y_submission = (y_submission - y_submission.min()) / (y_submission.max() - y_submission.min())
```

Finally, they used larger random forest / extra trees models than we do (we use 300 tree, they used 1000), which may have contributed.

This dataset may be a good reference to test future improvements, thanks for bringing it up!

**Comment by qo4on** [comment]
They also use calibration `CalibratedClassifierCV`. Can we manually set 1000 trees? Do you know which parameters could improve `AutoGluon` result in this case?

**Comment by Innixma** [comment]
You can set to 1000 trees via the `hyperparameters` argument in `.fit`: https://auto.gluon.ai/stable/_modules/autogluon/tabular/predictor/predictor.html#TabularPredictor.fit

something like:

```
hyperparameters = {
    'NN': {},
    'GBM': [
        {},
        {'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}},
        'GBMLarge',
    ],
    'CAT': {},
    'XGB': {},
    'FASTAI': {},
    'RF': [
        {'criterion': 'gini', 'n_estimators': 1000, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}},
        {'criterion': 'entropy', 'n_estimators': 1000, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}},
        {'criterion': 'mse', 'n_estimators': 1000, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression']}},
    ],
    'XT': [
        {'criterion': 'gini', 'n_estimators': 1000, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}},
        {'criterion': 'entropy', 'n_estimators': 1000, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}},
        {'criterion': 'mse', 'n_estimators': 1000, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression']}},
    ],
    'KNN': [
        {'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}},
        {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}},
    ],
}
```

**Comment by qo4on** [comment]
It looks like `19.6GB` of `Kaggle` disk space is not enough:
`Failed after 1 hour and 56 minutes` `OSError: [Errno 28] No space left on device`

**Comment by Innixma** [comment]
Yes, this is expected on Kaggle, having 1000 trees means using a lot of disk space. Especially when you are using `best_quality`. You could try using `presets='high_quality_fast_inference_only_refit'`, which should fit on disk without error.

**Comment by qo4on** [comment]
Thanks.
Unfortunately I did not managed to get the same score using `AutoGluon`. Stretch improves the result to `0.37828`, but it's far from `0.37353`. If anyone finds a better `AutoGluon` setting, post it here, please.

**Comment by gradientsky** [comment]
>  `Failed after 1 hour and 56 minutes` `OSError: [Errno 28] No space left on device`

I would suggest excluding KNNs since those take a lot of disk space:
```python
predictor_light = TabularPredictor(label=label, eval_metric=metric).fit(train_data, excluded_model_types=['KNN'], time_limit=30)
```
The most recent changes might have optimizations made by Nick to reduce disk space consumption. @Innixma are these ok to use at this point?

**Comment by Innixma** [comment]
@gradientsky Yes, they are available in v0.2 release.

**Comment by qo4on** [comment]
I have some suggestions for improving `AutoGluon`:
> Logistic / Linear regression has been known to outperform greedy ensemble selection on some datasets (Greedy Ensemble Selection is what `WeightedEnsemble` is based on), so this may be the cause.

1. It would be nice to add Logistic / Linear regression option to `AutoGluon`.

2. Add calibration wrapper for each first level model:
 ```
CalibratedClassifierCV(clf, method='isotonic', cv=StratifiedKFold(5))
```
I didn't find how to do that using current `AutoGluon` version.

3. Also I faced a problem when `'best'` model is not the best one. In this case on Titanic dataset the second model shows better test score than the first model.

![image](https://user-images.githubusercontent.com/35609308/118808478-ff38a280-b8c2-11eb-8d16-507af9010678.png)

I would suggest another way to choose the best model:
```
lb = predictor.leaderboard(silent=True)
best_model = lb[lb['stack_level'] == lb['stack_level'].max()]['model'].iloc[0]
```
4. One last thing that might be useful is to replace `AutoGluon` neural net with [MaskNet](https://paperswithcode.com/sota/click-through-rate-prediction-on-criteo).

**Comment by Innixma** [comment]
Re 1: This already exists (`'LR'` is the key to use in `hyperparameters`), however it is not used by default. I plan to add it as a default model in a future release (possibly in v0.3).

Re 2: We have a more sophisticated method of handling bagging / CV than is available in sklearn. We have to handle more complex cases than is supported by CalibratedClassifierCV. In future we may consider contributing the functionality back to sklearn, as this is some of the most important components of AutoGluon.

Re 3: It is impossible to pick the best model ahead of time for the `test` score. `best` is picked off of the strongest `val` score. ML would be very easy if we could know which model was best on the `test` data ahead of time, but that is not the case.

Re 4: We are happy to accept contributions! If you'd like, please open a PR which adds this model and we can test it / benchmark it to see if it improves upon our existing methods!

**Comment by wjlgatech** [comment]
Hi @Innixma, 
For Re 2, do you mean that Autogluon already calibrate the models it shows? What module/function Autogluon use?

I am reading Macest https://github.com/oracle/macest and they calibrate Machine Learning models' confidence scores. Does Autogluon provide sample-wise confidence score for its prediction?

**Comment by Innixma** [comment]
@jwmueller would be best fit to answer the calibration question.

We are currently working on automatic model calibration and have recently added Temperature Scaling to AG, and I think we have further plans to leverage model confidence.

**Comment by jwmueller** [comment]
@wjlgatech autogluon currently does not output epistemic uncertainty estimates.  

To get aleatoric uncertainty estimates in classification today, you can use `predict_proba()` output which can also be calibrated via autogluon's built-in temperature-scaling, or you can calibrate these yourself posthoc using eg. sklearn. To get aleatoric uncertainty estimates in regression today, you can use autogluon's built-in quantile regression functionality. 
To get epistemic uncertainty estimates with autogluon today, you can produce predictions via every individual model in autogluon's ensemble and use the variation in these predictions as a crude measure of epistemic uncertainty.

We will be adding new functionality for improved calibration and epistemic uncertainty estimation in the near future via conformal methods, stay tuned!
