### ISSUE TITLE
Make torch installed by user instead of auto-installation

### ISSUE THREAD

**Issue by talhaanwarch** [autogluon/autogluon#1070]
I think the torch version should be installed by the user. Currently with `v0.1.0`,  `torch-1.8.1` is installed which throws the error `AssertionError: Torch not compiled with CUDA enabled`. And as user, I first need to uninstall it and then install it again. Further different systems has different cuda version and making it pre-installed with latest cuda version make things difficult. 

Note:  the tested system is windows 10 with python `3.8.5`

**Comment by Innixma** [comment]
Thanks for mentioning this!

One option is to install torch prior to AutoGluon, which should keep your torch version in most cases.

Another is to avoid installing torch altogether via:

```
pip install autogluon.tabular[lightgbm,catboost,xgboost]
```

By default, it installs `autogluon.tabular[all]` which includes torch.

Hope this helps! We may consider making torch a separate dependency, however `fastai` depends on `torch`, and we ideally want `fastai` to be a default model.
