### ISSUE TITLE
[Tabular] Error with NeuralNetMXNet model saving to S3 path

### ISSUE THREAD

**Issue by mattmcclean** [autogluon/autogluon#1094]
Am trying to run the getting started example with AutoGluon Tabular and running into a problem with the NeuralNetMXNet model training. The problem is with `TabularPredictor` `__init__` method that can take an S3 prefix rather than a local dir. I tried again removing the S3 path and it worked fine. The error is below.

The error message is the following:
```
(pid=6543, ip=172.31.47.150) Fitting model: NeuralNetMXNet ...
(pid=6543, ip=172.31.47.150) 	Warning: Exception caused NeuralNetMXNet to fail during training... Skipping this model.
(pid=6543, ip=172.31.47.150) 		Traceback (most recent call last):
(pid=6543, ip=172.31.47.150)   File "../3rdparty/dmlc-core/src/io.cc", line 57
(pid=6543, ip=172.31.47.150) MXNetError: Please compile with DMLC_USE_S3=1 to use S3
(pid=6543, ip=172.31.47.150) Detailed Traceback:
(pid=6543, ip=172.31.47.150) Traceback (most recent call last):
(pid=6543, ip=172.31.47.150)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 924, in _train_and_save
(pid=6543, ip=172.31.47.150)     model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
(pid=6543, ip=172.31.47.150)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 896, in _train_single
(pid=6543, ip=172.31.47.150)     model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
(pid=6543, ip=172.31.47.150)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/autogluon/core/models/abstract/abstract_model.py", line 411, in fit
(pid=6543, ip=172.31.47.150)     self._fit(**kwargs)
(pid=6543, ip=172.31.47.150)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/autogluon/tabular/models/tabular_nn/tabular_nn_model.py", line 214, in _fit
(pid=6543, ip=172.31.47.150)     self.train_net(train_dataset=train_dataset, params=params, val_dataset=val_dataset, initialize=True, setup_trainer=True, time_limit=time_limit, reporter=reporter)
(pid=6543, ip=172.31.47.150)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/autogluon/tabular/models/tabular_nn/tabular_nn_model.py", line 367, in train_net
(pid=6543, ip=172.31.47.150)     self.model.save_parameters(net_filename)
(pid=6543, ip=172.31.47.150)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 451, in save_parameters
(pid=6543, ip=172.31.47.150)     save_fn(filename, arg_dict)
(pid=6543, ip=172.31.47.150)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mxnet/ndarray/utils.py", line 280, in save
(pid=6543, ip=172.31.47.150)     keys))
(pid=6543, ip=172.31.47.150)   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mxnet/base.py", line 246, in check_call
(pid=6543, ip=172.31.47.150)     raise get_last_ffi_error()
(pid=6543, ip=172.31.47.150) mxnet.base.MXNetError: Traceback (most recent call last):
(pid=6543, ip=172.31.47.150)   File "../3rdparty/dmlc-core/src/io.cc", line 57
(pid=6543, ip=172.31.47.150) MXNetError: Please compile with DMLC_USE_S3=1 to use S3
```

**Comment by mattmcclean** [comment]
Looks like will need to follow the instructions here to build with S3 support - https://mxnet.apache.org/versions/1.8.0/api/faq/s3_integration#step-1-build-mxnet-with-s3-integration-enabled. Do you know if there is a pre-built version of this library with S3 support to avoid building from source ?

**Comment by jwmueller** [comment]
I'm not aware of a pre-built MXNet with the S3 support, so you may have to build from source.

Alternatively why not just first train with a local path, and then copy the resulting directory over to s3 after training is complete?

If there's some reason you need to use s3 path and cannot install s3-supported mxnet, then you could also just pass: `excluded_model_types=['NN'] to skip training of this particular model (and any others that give you s3 issues).

**Comment by mattmcclean** [comment]
Yes, I got around it by using EFS instead to save the models instead of S3

**Comment by Innixma** [comment]
This is a bug at present, we don't have good testing in place for the train in s3 functionality so it can sometimes have issues with certain models that are not traditionally serializable in pickle.

**Comment by songqiang** [comment]
> Alternatively why not just first train with a local path, and then copy the resulting directory over to s3 after training is complete?

Is it possible to make this a built-in behavior in autogluon? 

in predictor constructor (__init__):

```
if path is a local path:
    use the path as-is
elif path is a s3 path:
    create a temporary local path, and use the temp local path for training and inference

```
in predictor destructor (__del__):

```
if path is a local path:
    pass 
elif path is a s3 path:
    copy the artifacts from the temp local path to the original s3 path
    clean up temporary local path

```

This is definitely a hacky way, but seems a nice usability enhancements. As AutoGluon sometimes use quite a lot of local disk, we do have the need to persist the artifacts to s3 when training a lots of models.

**Comment by Innixma** [comment]
> > Alternatively why not just first train with a local path, and then copy the resulting directory over to s3 after training is complete?
> 
> Is it possible to make this a built-in behavior in autogluon?
> 
> in predictor constructor (**init**):
> 
> ```
> if path is a local path:
>     use the path as-is
> elif path is a s3 path:
>     create a temporary local path, and use the temp local path for training and inference
> ```
> 
> in predictor destructor (**del**):
> 
> ```
> if path is a local path:
>     pass 
> elif path is a s3 path:
>     copy the artifacts from the temp local path to the original s3 path
>     clean up temporary local path
> ```
> 
> This is definitely a hacky way, but seems a nice usability enhancements. As AutoGluon sometimes use quite a lot of local disk, we do have the need to persist the artifacts to s3 when training a lots of models.

This is reasonable, although probably best done at the model level rather than the predictor level. Models could save their artifacts to a temp directory, then when it comes time to save, it will upload those artifacts to S3.

**Comment by Innixma** [comment]
Fixed due to replacing the MXNet NN with the Torch NN in Tabular.
