### ISSUE TITLE
How to do transfer learning in vision task

### ISSUE THREAD

**Issue by talhaanwarch** [autogluon/autogluon#1196]
Let suppose I have a data of ct-scan with four classes, I trained AG model at it. I have another data with 5 classes, I want to use pre-trained weights obtained in the first case instead of using imagenet weights. How can I do this?

**Comment by zhreshold** [comment]
Manipulating underlying weights can be error-prone, with exceptions.
So if I assuming you are using the exactly the same configuration(especially the network arch is the same), then you can try to 
1) load the previous ct-scan autogluon model and resume training
2) touch the underlying classifier, e.g. `predictor._classifier.net` is a pure mxnet.gluon network, which has `save_parameters` and `load_parameters`
