### ISSUE TITLE
Add M1 Mac Support

### ISSUE THREAD

**Issue by km5ar** [autogluon/autogluon#1242]
Hi, I'm trying to run autogluon on M1 macbook air, but it doesn't seems work, does autogluon support M1 mac?

See also #2271 for M2 issues

**Comment by Innixma** [comment]
Probably not, unfortunately AutoGluon has a variety of dependencies and therefore each fo the dependencies will have to support M1 before AutoGluon does. We haven't tried testing on M1 but hopefully we can look towards supporting it closer to end of year or sometime next year.

If anyone with an M1 mac has insights into what needs to be done for AG to work on it, please feel free to add information here.

**Comment by sackoh** [comment]
Recently, I worked on M1 Mac mini to test AutoGluon on diverse environments. 
If you use _conda miniforge_, most dependencies are supported.
but some libraries like `catboost` are not supported yet.

**Comment by Innixma** [comment]
@sackoh Thanks for the information! It is great to hear that AutoGluon is mostly functional on M1 Mac. So long as the core packages are supported, it is ok if individual models are not yet available as that will hopefully be resolved by the model authors in future releases.

**Comment by km5ar** [comment]
I'm using Anaconda, which Autogluon doesn't work.

**Comment by asgeorges** [comment]
I was able to get some functionally building from source (I grabbed build `autogluon-0.3.2b20210908`).  The main issues I've come across currently are those reported in #245.  Basically, both GBM & XGB models stall __even when implementing the solutions in #245__.  I could be doing something wrong, but for clarity here's been what I've tried:  

1) Setting `auto_stack=True`  along w/ `hyperparameter_tune=False` within the hyperparams dict, i.e: 

```
hyperparameters = {
    'GBM': [
        {'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}},
        {'hyperparameter_tune': False},
        'GBMLarge',
    ],
    'XGB': {'hyperparameter_tune': False}}
```
2) Reverting to different versions of autogluon
3) Set `excluded_model_types='GBM'`

I swept the `GBM` issue under the rug by doing (3), but then I hit the wall again when the ensemble gets to `XGBoost_BAG_L1`

I've only successfully run so far w/ `excluded_model_types='[GBM', 'XGB']`

**Comment by harrywang** [comment]
I tried so many different things and finally figured out it might be the M1 chip - Autogluon should put a note for this.

**Comment by Innixma** [comment]
@harrywang Good callout, I've created #1424 to track adding documentation on the status of M1 support to the installation page.

**Comment by motin** [comment]
> Probably not, unfortunately AutoGluon has a variety of dependencies and therefore each of the dependencies will have to support M1 before AutoGluon does. We haven't tried testing on M1 but hopefully we can look towards supporting it closer to end of year or sometime next year.
> 
> If anyone with an M1 mac has insights into what needs to be done for AG to work on it, please feel free to add information here.

For PyPi, these are the versions in which these autogluon dependencies supplies M1-compatible wheels:
- Python 3.8+
- Numpy 1.21.1+ 
- Scipy 1.7.3+
- Ray 1.8+

Autogluon is fine with these requirements for Python and Numpy, but not for scipy, [autogluon requiring <1.7](https://github.com/awslabs/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py#L21), and ray, [autogluon requiring <1.8](https://github.com/awslabs/autogluon/blob/f686066afec04141c2a79eb8ecf80dc5eb7c980c/core/setup.py#L41).

If one relaxes the scipy requirement to allow for scipy 1.7 and ray 1.8, autogluon goes further in the installation process and it is possible to see what are the next set of blockers. Findings:

- catboost is not available at all (`ERROR: Could not find a version that satisfies the requirement catboost<1.1,>=1.0 (from autogluon-tabular[all]) (from versions: none)`)
- xgboost, lightgbm, fastai and tokenizers don't have M1 wheels ([tokenizers issue](https://github.com/huggingface/tokenizers/issues/712)) and fails to compile out of the box

...resulting in autgluon installed, albeit without any of the optional tabular dependencies and without autogluon-text.

If one can find a way to successfully build or install these set of dependencies, we would see what the next set of blocking/missing dependencies are, but first things first: Can autogluon support scipy 1.7.3+ as a first step towards M1 support?

**Comment by Innixma** [comment]
@motin Thanks for this! We have updated scipy and ray to allow for valid versions in #1503. You should be able to try installing pre-release again and see if you are able to get further.

**Comment by mli** [comment]
looks like there are still issues with scipy and numpy, when i'm trying to install `--pre` on m1 mac

```bash
    error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/muli/miniforge3/include -arch arm64 -fPIC -O2 -isystem /Users/muli/miniforge3/include -arch arm64 -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-11.0-arm64-3.9/numpy/core/src/umath -Ibuild/src.macosx-11.0-arm64-3.9/numpy/core/src/npymath -Ibuild/src.macosx-11.0-arm64-3.9/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-11.0-arm64-3.9/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/muli/miniforge3/include/python3.9 -Ibuild/src.macosx-11.0-arm64-3.9/numpy/core/src/common -Ibuild/src.macosx-11.0-arm64-3.9/numpy/core/src/npymath -c numpy/core/src/multiarray/array_assign_scalar.c -o build/temp.macosx-11.0-arm64-3.9/numpy/core/src/multiarray/array_assign_scalar.o -MMD -MF build/temp.macosx-11.0-arm64-3.9/numpy/core/src/multiarray/array_assign_scalar.o.d -faltivec -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for numpy
  Failed to build numpy
  ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/26/68/84dbe18583e79e56e4cee8d00232a8dd7d4ae33bc3acf3be1c347991848f/scipy-1.6.1.tar.gz#sha256=c4fceb864890b6168e79b0e714c585dbe2fd4222768ee90bc1aa0f8218691b11 (from https://pypi.org/simple/scipy/) (requires-python:>=3.7). Command errored out with exit status 1: /Users/muli/miniforge3/bin/python3.9 /private/var/folders/3x/bwrgc6yn3zjc4sc995ts77dm0000gn/T/pip-standalone-pip-ua5eb9rg/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/3x/bwrgc6yn3zjc4sc995ts77dm0000gn/T/pip-build-env-dqwec5fr/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --pre -- wheel 'setuptools<=51.0.0' 'Cython>=0.29.18' 'pybind11>=2.4.3' 'numpy==1.19.2; python_version=='"'"'3.6'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.19.2; python_version=='"'"'3.7'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.16.5; python_version=='"'"'3.6'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.16.5; python_version=='"'"'3.7'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.19.0; python_version=='"'"'3.6'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' 'numpy==1.20.0; python_version=='"'"'3.7'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' 'numpy; python_version>='"'"'3.10'"'"'' 'numpy; python_version>='"'"'3.8'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' Check the logs for full command output.
^[[6~^[[6~^[[6~  Downloading scipy-1.6.0.tar.gz (27.3 MB)
     |████████████████████████████████| 27.3 MB 8.3 MB/s
```

**Comment by chrisking** [comment]
Just commenting that if you are comfortable with the pre-release tag build of catboost you can follow along on this ticket, then just install the pre version of autogluon without the restrictions now on m1s. https://github.com/catboost/catboost/issues/1526

**Comment by Innixma** [comment]
@chrisking Thanks for the info! Have you successfully ran AutoGluon on m1 with this new CatBoost pre-release? If so, could you perhaps provide a brief write-up on the steps needed, such as pip install lines?

**Comment by chrisking** [comment]
@Innixma great idea, I created this guide this morning, it covers the entire process from creating a Python environment to actually training a model using the official tutorial. https://github.com/chrisking/AutoGluonTabularOnM1Guide

**Comment by Innixma** [comment]
@chrisking This is awesome!! I notified my team and I'll see if we can get anyone with an M1 Mac to try out your tutorial. Do you have any insight into when this will be available in a stable CatBoost release? Is this planned for next CatBoost release (1.0.5)?

**Comment by chrisking** [comment]
https://github.com/catboost/catboost/releases/tag/v1.0.5 New release is out and working so it should be good to go now.

**Comment by mli** [comment]
Confirm successfully installed autogluon v0.4 on M1 mac by

```bash
conda create --name py39 python=3.9
conda activate py39
pip install autogluon
```

Though in the first trial I got an error when building wheel for `tokenizers` that "error: can't find Rust compiler pip". It can be fixed by 

```bash
brew install rust
```

**Comment by andreas12345** [comment]
FYI Torch has support for M1 in latest nightly builds (https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/) – I wonder if anyone has tried this with autogluon? Currently blocked from trying it myself by https://github.com/awslabs/autogluon/issues/875.

**Comment by gradientsky** [comment]
### AutoGluon 0.5.2 on M1 mac, MacOS 12.6 Monterrey

#### Install xcode
```shell
xcode-select --install
```

#### System installs    
```shell
brew install cmake libomp rust
brew install llvm
```

#### Install [mamba forge](https://github.com/conda-forge/miniforge)
```shell
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-$(uname -m).sh"
bash Mambaforge-MacOSX-arm64.sh
```

!!! Open fresh shell

```shell
conda update -y -n base -c conda-forge conda
```

#### Packages installation

```shell
conda create -n py39 -y python=3.9
conda activate py39
python -m venv venv-ag-39
source venv-ag-39/bin/activate
pip install -U pip
pip install -U setuptools wheel
conda install -y numpy scipy scikit-learn
conda install -y Cython
conda install -y vowpalwabbit
conda install -y lightgbm 
conda install -y xgboost
```

!!! Open fresh shell

```shell
conda activate py39
source venv-ag-39/bin/activate
pip install Cython xgboost

export CC=/opt/homebrew/opt/llvm/bin/clang 
export CXX=/opt/homebrew/opt/llvm/bin/clang++
export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"

./full_install.sh
```

**Comment by giswqs** [comment]
@gradientsky Thanks for providing the detailed steps. I was able to following the steps and successfully installed autogluon on my M1 Mac. The only issue was the step to install Cython and xgboost, which threw an [grpcio error](https://stackoverflow.com/questions/66640705/how-can-i-install-grpcio-on-an-apple-m1-silicon-laptop). After running the following two lines, the installation went smoothly. 

```bash
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
```

**Comment by notingbad** [comment]
@gradientsky Thanks for the great work, but it seems not function on m2 Macbook air(MacBook Air（M2，2022, MacOS 12.6 Monterrey）

**Comment by gradientsky** [comment]
@notingbad I would suggest creating a separate thread for M2

**Comment by Cokral** [comment]
Hi! @gradientsky I used your message to install Autogluon ([message link](https://github.com/awslabs/autogluon/issues/1242#issuecomment-1285276870)) but since then I am unable to install LightGBM on its own on my other virtual environments. Do you have any idea of what could've gone wrong?

**Comment by elikastelein** [comment]
> I really appreciate these instructions, but could do with a bit of help. I have tried to follow these instructions, and get as far as the "./full_install.sh" step but I don't see a script called that. Where does it come from? Maybe I missed a step?

@drdavew it's in the top-level of this git repo: https://github.com/autogluon/autogluon/blob/master/full_install.sh

**Comment by drdavew** [comment]
> 

Thanks very much!

**Comment by backeb** [comment]
Hi,

thank you for the detailed instructions on how to install autogluon. It also works for me on M1 Mac:
```
(autogluon) (venv-ag-39) backeb@Bjorns-MacBook-Pro-2:autogluon>ipython
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:48:25) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import autogluon

In [2]: 
```

Does anyone know how to get it to work in a Jupyter Notebook? 

In Visual Studio Code in a Jupyter Notebook, after I've followed the installation steps I can see the kernel:
![image](https://user-images.githubusercontent.com/29396406/208954422-cf10b7aa-fa8f-4b38-822a-35f191c236bd.png)

Selecting that kernel and running a cell with the command gives me a `ModuleNotFoundError: No module named 'autogluon'`

I get the same error when I launch the jupyter-notebook from the `(autogluon) (venv-ag-39)` environment.
![image](https://user-images.githubusercontent.com/29396406/208955990-c0df0493-539d-4eb8-8cab-54c6a4a551fd.png)

Interestingly when I open a terminal in jupyter and then launch ipython and then do `import autogluon` it works again...
![image](https://user-images.githubusercontent.com/29396406/208956554-ee7f3c0c-39f0-4874-8675-7168240faf68.png)

Any ideas?

**Comment by gradientsky** [comment]
@backeb do you happen to have `autogluon` folder in jupyter environment? If you do, then it can shadow the packages installed in the system.

**Comment by gradientsky** [comment]
Last updated: 2023/01/13
### Python 3.10 - AutoGluon 0.6.2 on M1 mac, MacOS 12.6 Monterrey
```
PyTorch version: 1.12.1
OS: macOS 12.6 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: version 3.24.2
Libc version: N/A
Python version: 3.10.8 | packaged by conda-forge (64-bit runtime)
Python platform: macOS-12.6.2-arm64-arm-64bit
```

#### Install xcode
```shell
xcode-select --install
```

#### System installs    
```shell
brew install cmake libomp rust
brew install llvm
```

#### Install [mamba forge](https://github.com/conda-forge/miniforge)
```shell
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-$(uname -m).sh"
bash Mambaforge-MacOSX-arm64.sh
```

!!! Open fresh shell

```shell
conda update -y -n base -c conda-forge conda
```

#### Packages installation

```shell
conda create -n py310 -y python=3.10
conda activate py310
python -m venv venv-ag-310
source venv-ag-310/bin/activate
pip install -U pip
pip install -U setuptools wheel
conda install -y numpy scipy scikit-learn Cython lightgbm
conda install -y -c conda-forge vowpalwabbit
conda install -y -c conda-forge xgboost
```

!!! Open fresh shell

```shell
conda activate py310
source venv-ag-310/bin/activate

export CC=/opt/homebrew/opt/llvm/bin/clang 
export CXX=/opt/homebrew/opt/llvm/bin/clang++
export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1

VW_VER=$(conda list | grep vowpalwabbit | awk '{print $2}' | tail -1)
CYTHON_VER=$(conda list | grep cython | awk '{print $2}' | tail -1)
XGBOOST_VER=$(conda list | grep xgboost | awk '{print $2}' | tail -1)
LGBM_VER=$(conda list | grep lightgbm | awk '{print $2}' | tail -1)
pip install cython==$CYTHON_VER xgboost==$XGBOOST_VER vowpalwabbit==$VW_VER lightgbm==$LGBM_VER

# from autogluon sources root
./full_install.sh
```

<details>
<summary><b><u>Details - Fit Summary</u></b></summary>

```
Beginning AutoGluon training ...
AutoGluon will save models to "agModels-predictClass/"
AutoGluon Version:  0.6.3b20230113
Python Version:     3.10.8
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000
Train Data Rows:    39073
Train Data Columns: 14
Label Column: class
Preprocessing data ...
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [' <=50K', ' >50K']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Selected class <--> label mapping:  class 1 =  >50K, class 0 =  <=50K
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive ( >50K) vs negative ( <=50K) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    12679.88 MB
	Train Data (Original)  Memory Usage: 22.92 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 6 | ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', ...]
		('object', []) : 8 | ['workclass', 'education', 'marital-status', 'occupation', 'relationship', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 7 | ['workclass', 'education', 'marital-status', 'occupation', 'relationship', ...]
		('int', [])       : 6 | ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', ...]
		('int', ['bool']) : 1 | ['sex']
	0.1s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 2.19 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0639828014229775, Train Rows: 36573, Val Rows: 2500
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7752	 = Validation score   (accuracy)
	0.25s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.766	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ...
	0.8792	 = Validation score   (accuracy)
	2.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	0.8824	 = Validation score   (accuracy)
	1.54s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8604	 = Validation score   (accuracy)
	0.92s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8604	 = Validation score   (accuracy)
	0.98s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	0.882	 = Validation score   (accuracy)
	7.78s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8508	 = Validation score   (accuracy)
	0.63s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.846	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
[W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
	0.8636	 = Validation score   (accuracy)
	29.73s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: XGBoost ...
	0.8872	 = Validation score   (accuracy)
	5.66s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch ...
[W ParallelNative.cpp:229] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
	0.8612	 = Validation score   (accuracy)
	32.25s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8856	 = Validation score   (accuracy)
	5.24s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	0.8912	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 89.75s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("agModels-predictClass/")
```

</details>

<details>
<summary><b><u>Details - Adult Dataset Run</u></b></summary>

```
                  model  score_test  score_val  pred_time_test  pred_time_val  ...  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0               XGBoost    0.877162     0.8872        0.028305       0.018089  ...                0.018089           5.659502            1       True         11
1   WeightedEnsemble_L2    0.876344     0.8912        0.164798       0.078341  ...                0.002373           0.652639            2       True         14
2              CatBoost    0.874706     0.8820        0.041818       0.007415  ...                0.007415           7.779517            1       True          7
3         LightGBMLarge    0.873784     0.8856        0.039721       0.014614  ...                0.014614           5.239187            1       True         13
4              LightGBM    0.873477     0.8824        0.026291       0.010212  ...                0.010212           1.541906            1       True          4
5            LightGBMXT    0.871430     0.8792        0.038357       0.014338  ...                0.014338           2.267840            1       True          3
6        NeuralNetTorch    0.859249     0.8612        0.036834       0.014275  ...                0.014275          32.254715            1       True         12
7      RandomForestGini    0.859044     0.8604        0.173848       0.046831  ...                0.046831           0.919182            1       True          5
8      RandomForestEntr    0.858020     0.8604        0.204746       0.044882  ...                0.044882           0.976402            1       True          6
9       NeuralNetFastAI    0.856997     0.8636        0.119002       0.030747  ...                0.030747          29.726533            1       True         10
10       ExtraTreesGini    0.852288     0.8508        0.308248       0.047067  ...                0.047067           0.625617            1       True          8
11       ExtraTreesEntr    0.851776     0.8460        0.291663       0.046508  ...                0.046508           0.646460            1       True          9
12       KNeighborsUnif    0.773365     0.7752        0.029469       0.018716  ...                0.018716           0.250967            1       True          1
13       KNeighborsDist    0.762514     0.7660        0.034238       0.009613  ...                0.009613           0.012723            1       True          2
```

</details>

**Comment by imempress** [comment]
Thanks for these detailed install instuctions @gradientsky!

I'm getting this error when following the above:
```ERROR: Package 'autogluon-common' requires a different Python: 3.10.8 not in '<3.10,>=3.7'```

**Comment by gradientsky** [comment]
@imempress merged #2692, this should enable it.

**Comment by imempress** [comment]
That updated seems to have resolved my issue above, thanks @gradientsky! At least I'm now able to run everything in an example [MultiModalPredictor tutorial](https://auto.gluon.ai/stable/tutorials/multimodal/multimodal_prediction/beginner_multimodal.html), which is what I was attempting originally.

**Comment by giswqs** [comment]
`autogluon` now supports `pytorch-gpu` and arm64, including Apple M1/M2 chips. conda-forge will install the GPU version if a user's machine supports it (i.e. if CUDA drivers can be found). Otherwise, it will install the CPU version. To install `autogluon`:

```bash
conda create -n ag python=3.9
conda activate ag
conda install -c conda-forge mamba
mamba install -c conda-forge autogluon
```

To install only a specific autogluon subpackage, e.g., `autogluon.tabular`:
```bash
mamba install -c conda-forge autogluon.tabuar
```
Here is a list of pull requests to add support for GPU and arm64:

**autogluon.core**
- [x] add `ray` to required dependencies for win and linux ([PR](https://github.com/conda-forge/autogluon.core-feedstock/pull/5))
- [ ] add `ray` support for osx and arm64 ([PR](https://github.com/conda-forge/ray-packages-feedstock/pull/83))

**autogluon.tabular**

- [ ] add `fastai` and `imodeals` to conda-forge ([PR](https://github.com/conda-forge/staged-recipes/pull/21887))
- [ ] add `fastai` to required dependencies
- [x] add `catboost` support osx arm64 ([PR](https://github.com/conda-forge/catboost-feedstock/pull/95))
- [x] add optional dependencies (`lightgbm`, `catboost`, `xgboost`) ([PR](https://github.com/conda-forge/autogluon.tabular-feedstock/pull/9))
- [x] add support for `pytorch-gpu`

**autogluon.multimodal**
- [x] add `nlpaug` support for `pytorch-gpu` ([PR](https://github.com/conda-forge/nlpaug-feedstock/pull/7))
- [x] add support for `pytorch-gpu` ([PR](https://github.com/conda-forge/autogluon.multimodal-feedstock/pull/10))
- [x] do not require `torchtext` and `fairscale` for windows ([PR](https://github.com/conda-forge/autogluon.multimodal-feedstock/pull/8))
- [ ] add `torchtext` support for arm64 ([Issue](https://github.com/conda-forge/torchtext-feedstock/issues/6))
- [ ] add support for windows

**autogluon.timeseries**
- [x] add optional dependencies (`sktime`, `pmdarima`, `tbats`) ([PR](https://github.com/conda-forge/autogluon.timeseries-feedstock/pull/6))

**autogluon**
- [x] add support for `pytorch-gpu`

**Comment by acmeguy** [comment]
@giswqs - mamba 1.2.0 installs sktime 0.15.1 that is not supported by autogluon (>=0.13.1 and <0.14).
Can you please advise?

**Comment by giswqs** [comment]
@acmeguy Did you get any error message when using it? The reason I had to raise the sktime version upper bound is because the sktime package on conda-forge does not have any version meeting the autogluon requirement (`>=0.13.1 and <0.14`). See https://anaconda.org/conda-forge/sktime/files. It has version `v0.12.1` then jumps to `v0.14.0`. 

@Innixma @sxjscience Does `autogluon.timeseries` support `sktime>=0.14`?

**Comment by acmeguy** [comment]
Yea, the library did not load during import

**Comment by giswqs** [comment]
@acmeguy A temporal workaround is to `pip install sktime==0.13.1`.  The autogluon team needs to raise the `sktime` version upper bound (at least support `v0.14.0`) so that the conda-forge can be built. 

![image](https://user-images.githubusercontent.com/5016453/216687310-02061240-71e8-4c7d-9b84-7d60916acb38.png)

After `pip install sktime==0.13.1 `:
![image](https://user-images.githubusercontent.com/5016453/216687387-2cba0ca8-d790-438d-b438-bc678ae7a49b.png)

**Comment by acmeguy** [comment]
Thank you

**Comment by acmeguy** [comment]
@giswqs - how can I verify that the M1 is being fully utilized?

**Comment by acmeguy** [comment]
Sorry, @giswqs, I'm running into more problems, and I'm neither sure you are the right person to impose on nor if this is the right place. This might have direct relations with the M1 Issue being discussed here.

Jupyter silents dies while fitting a simple set.

This is the complete output and I find no logs:

Starting training. Start time is 2023-02-03 19:50:37
Models that will be trained: ['Naive', 'SeasonalNaive', 'ETS', 'Theta', 'ARIMA', 'AutoGluonTabular', 'DeepAR']
Training timeseries model Naive. 
	-1.0000       = Validation score (-MAPE)
	0.00    s     = Training runtime
	5.27    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive. 
	-0.5858       = Validation score (-MAPE)
	0.00    s     = Training runtime
	4.77    s     = Validation (prediction) runtime
Training timeseries model ETS. 
	-0.1244       = Validation score (-MAPE)
	0.00    s     = Training runtime
	4.99    s     = Validation (prediction) runtime
Training timeseries model Theta. 
	-0.1076       = Validation score (-MAPE)
	0.00    s     = Training runtime
	0.35    s     = Validation (prediction) runtime
Training timeseries model ARIMA. 
	-0.0790       = Validation score (-MAPE)
	0.00    s     = Training runtime
	5.69    s     = Validation (prediction) runtime
Training timeseries model AutoGluonTabular. 
	-0.0811       = Validation score (-MAPE)
	32.52   s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Training timeseries model DeepAR.

**Comment by acmeguy** [comment]
This seems to be working, but there seems to be no way to verify that the M1 is being fully utilized and the Jupyter cell-output has become extremely sluggish, regardless of what is being outputted. A simple dataframe takes a minute to be displayed.

**Comment by acmeguy** [comment]
@giswqs - It seems that the documentation has been chance to state that Apple silicon is not supported. The link to this issue is gone. Can you reflect on that a bit?

**Comment by acmeguy** [comment]
@Innixma - can you please tell me why this issue now has 0 priority?

**Comment by acmeguy** [comment]
Thanks for the instructions, @gradientsky!

Are there any caveats that I should know about?

**Comment by Innixma** [comment]
> @Innixma - can you please tell me why this issue now has 0 priority?

priority 0 = maximum priority

**Comment by Innixma** [comment]
@giswqs I created a GitHub issue to track upgrading sktime.

**Comment by Innixma** [comment]
sktime range has been updated to `>=0.14,<0.16`! Starting in AG v0.7, all modules should now be supported on M1 via conda install.

**Comment by giswqs** [comment]
@Innixma Great! I will update the `autogluon.timeseries` conda-forge package tomorrow.

**Comment by Innixma** [comment]
Next steps:

- [ ] @gradientsky can you update our website install doc for M1 to provide conda install steps?

**Comment by Innixma** [comment]
@giswqs Now ray is lazily imported in multimodal, so you should be able to get multimodal installed and running on MacOS in conda

**Comment by Innixma** [comment]
@giswqs Would you be able to verify if things will work in conda for M1? Or allow users with an M1 to test?

**Comment by giswqs** [comment]
@Innixma Both `autogluon.tabular`  ([PR](https://github.com/conda-forge/autogluon.tabular-feedstock/pull/13)) and `autolguon.multimodal` ([PR](https://github.com/conda-forge/autogluon.multimodal-feedstock/pull/17)) conda-forge recipes have passed all checks. They should support M1 once v0.7 is released. Waiting to test `autogluon.timeseries` after `autogluon.tabular` v0.7 becomes available on conda-forge.

**Comment by giswqs** [comment]
`autogluon` [v0.7.0](https://anaconda.org/conda-forge/autogluon) is now available on conda-forge. To install it on Linux and macOS:
```bash
conda create -n ag python=3.9
conda activate ag
conda install -c conda-forge mamba
mamba install -c conda-forge autogluon
```

The `autogluon.multimodal` conda-forge package does not yet support Windows. To install `autogluon.tabular` and `autogluon.timeseries` on Windows:

```bash
conda create -n ag python=3.9
conda activate ag
conda install -c conda-forge mamba
mamba install -c conda-forge autogluon.tabular autogluon.timeseries
```

This issue can be closed now.

**Comment by maver1ck** [comment]
Any chance to properly detect Mac M1 GPU ?
```
		The total system num_gpus=0 is less than minimum num_gpus=1 to fit MultiModalPredictorModel. Consider using a machine with more GPUs.
Detailed Traceback:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1502, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1447, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 695, in fit
    kwargs = self._preprocess_fit_args(**kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 428, in _preprocess_fit_args
    kwargs = self._preprocess_fit_resources(**kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 597, in _preprocess_fit_resources
    assert system_num_gpus >= minimum_model_num_gpus, f'The total system num_gpus={system_num_gpus} is less than minimum num_gpus={minimum_model_num_gpus} to fit {self.__class__.__name__}. Consider using a machine with more GPUs.'
AssertionError: The total system num_gpus=0 is less than minimum num_gpus=1 to fit MultiModalPredictorModel. Consider using a machine with more GPUs.
```

**Comment by maver1ck** [comment]
@Innixma 
Mac M1 is supported in Torch.

Please find this article helpful:
https://towardsdatascience.com/installing-pytorch-on-apple-m1-chip-with-gpu-acceleration-3351dc44d67c

I was able to run torch==2.0.0 on M1 without problems. Didn't try different versions.

**Comment by Innixma** [comment]
Thanks @maver1ck! I've created an issue to track adding support: #3126
