### ISSUE TITLE
Conditional Search Spaces for hyperparameter tuning

### ISSUE THREAD

**Issue by aswanthkrishna** [autogluon/autogluon#1390]
How can i perform hyper parameter search on conditional search spaces?

**Comment by Innixma** [comment]
You may want to refer to the ConfigSpace documentation, as I am not very familiar with using conditional search spaces nor how to do so in AutoGluon. Note that for new releases (v0.4+) we are likely removing ConfigSpace and may no longer support conditional search spaces.

https://automl.github.io/ConfigSpace/master/
