### ISSUE TITLE
what() -> "catboost/cuda/cuda_lib/cuda_base.h:183: CUDA error 2: out of memory"

### ISSUE THREAD

**Issue by otaviobhz** [autogluon/autogluon#1401]
I am testing the Docker of autogluon o my PC, tha have a 1060 3gb.

Using the Docker autogluon:0.3.1-rapids0.19-cuda10.2-jupyter-ubuntu18.04-py3.7

When I use presets='best_quality' and I am receiveing the following error:

what() -> "catboost/cuda/cuda_lib/cuda_base.h:183: CUDA error 2: out of memory"

Is that something regarding my PC? I tryied yesterday and works perfectly.

Thank you very much,

KR

Otavio

**Comment by Innixma** [comment]
We have not tested the docker on that low-end of a GPU. You may want to obtain a GPU with more memory to effectively use AG with GPU models.

**Comment by otaviobhz** [comment]
Actually I am using Ubuntu 20.04, not windows.

Is it that possible to reduce the batch size in order to reduce the amount of memory used of my graphic card to use autogluon?

Thank you very much

KR

**Comment by Innixma** [comment]
There is no such thing as batch size in CatBoost. CatBoost is a tree model. Better to search for specific ways to use less GPU memory in CatBoost, but its probably just worthwhile to use CPU CatBoost instead or get a larger GPU, 3 GB GPU memory is extremely small for ML workloads.

**Comment by otaviobhz** [comment]
I am checking what Graphic Cards fits my budget.
I will probably upgrade my GTX 1060 for new GPU now. I am in doubt of buying a GTX 1080 (not TI version)  8gb or a RTX 2060 6gb.
Witch one you suggest to work better with autogluon and Tensor Flow?
To work with tabular and classification problem, do you suggest an old one 1080 with more memory or a 2060 with less memory but with a more modern chip? Does RTX makes difference in Deeplearning?
I know they are old Graphic Cards, but it is what fits my budget and I would like to keep testing and helping the development of the Automl Tools.
Thanks you very much Innixma.
Kr,
Otavio

**Comment by Innixma** [comment]
6 GB is likely sufficient, 8 GB is definitely enough. Both are reasonable options, so pick what works best for your budget.
