### ISSUE TITLE
Does AutoGluon support named-entity recognition (NER)?

### ISSUE THREAD

**Issue by rxjx** [autogluon/autogluon#1622]
I'm hoping to use TextPredictor for NER so I'm wondering if anyone has tried this already. As the tutorial notes:

> Although the TextPredictor currently supports classification and regression tasks, it can directly be used for many NLP tasks if you properly format them into a data table. Note that there can be many text columns in this data table. Refer to the [TextPredictor documentation](https://auto.gluon.ai/stable/api/autogluon.predictor.html#autogluon.text.TextPredictor.fit) to see all available methods/options.

So I was wondering if I could either just add a column with the entity words or add two columns: one with start offset and one with end offset. But neither of these would work well when a row has multiple entities. Looking to hear from anyone who's done something similar.

**Comment by Innixma** [comment]
AutoGluon does not currently support named-entity recognition as it does not fit nicely in the classification / regression problem type. This may be added in future, but we are currently focused on classification, regression, and time series tasks.

**Comment by sxjscience** [comment]
@rxjx Yeah, we are actively discussing about adding the NER task. One potential design is to add one column with "entity" data type. That requires some additional works on designing the feature but it's on our roadmap.

**Comment by sxjscience** [comment]
Currently the team here is discussing about it since it’s a major feature. If you are interested, feel free to reach out to me via email.

**Comment by sxjscience** [comment]
@rxjx Check our latest document: https://auto.gluon.ai/dev/tutorials/multimodal/text_prediction/ner.html
