### ISSUE TITLE
get the details of model

### ISSUE THREAD

**Issue by JerryShuaiWANG** [autogluon/autogluon#1629]
### Describe the issue linked to the documentation

Hi, 

Thanks for the great work of Autugluon.

I am using the Tabular Prediction functions for regression tasks and kindly wonder if we could know all the details of the trained model, for instance, if the best model is KNeighborDist, can I know all the details about this ML model such as n_neighbors,leaf_size,p and so on.
(because when I print best_model, only some basic info of the details can be seen)

Many thanks!

**Comment by JerryJonesWang** [comment]
Could Anyone do a favor?

Or how do we do K-fold cross-validation like normal ML procedures? Thanks!

**Comment by Innixma** [comment]
You can use `predictor.info()` to get relevant low-level information such as model hyperparameters.
