### ISSUE TITLE
[BUG] TabularPredictor.fit() raises IndexError when problem_type="multiclass" but only 2 classes are in dataset.

### ISSUE THREAD

**Issue by soy-yo-con-bonete** [autogluon/autogluon#1640]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon

**Describe the bug**
In autogluon 0.4.0, an error is raised when fitting a "multiclass" model with 2 classes. This did not fail in 0.3.1. The error is not raised if you set problem_type="binary".

**Expected behavior**
It should work as in 0.3.1: a multiclass model with 2 classes should still be able to be considered "multiclass".

**To Reproduce**
```
import pandas as pd
import numpy as np
test_df = pd.DataFrame(["red", "blue"], columns=["target"])
test_df = test_df.sample(100, replace=True)
test_df["feature"] = np.random.uniform(size=len(test_df.index))
test_df.reset_index(inplace=True)

TabularPredictor(label="target",
    eval_metric='log_loss', problem_type='multiclass', ) \
    .fit(test_df)
```

Output:
```
...
2022-04-01 11:52:35,668 - autogluon.tabular.learner.default_learner - INFO - AutoGluon training complete, total runtime = 27.68s ... Best model: "WeightedEnsemble_L2"
*** IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Screenshots**

**Installed Versions**
Which version of AutoGluon are you are using?  
If you are using 0.4.0 and newer, please run the following code snippet:
<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

INSTALLED VERSIONS
------------------
date                 : 2022-04-01
time                 : 11:58:14.643275
python               : 3.8.7.final.0
OS                   : Darwin
OS-release           : 21.3.0
Version              : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
machine              : x86_64
processor            : i386
num_cores            : 8
cpu_ram_mb           : 16384
cuda version         : None
num_gpus             : 0
gpu_ram_mb           : []
avail_disk_size_mb   : 230823

autogluon.common     : 0.4.0
autogluon.core       : 0.4.0
autogluon.features   : 0.4.0
autogluon.tabular    : 0.4.0
autogluon.text       : 0.4.0
autogluon_contrib_nlp: None
boto3                : 1.21.31
catboost             : 1.0.4
dask                 : 2021.11.2
distributed          : 2021.11.2
fairscale            : 0.4.6
fastai               : 2.5.5
lightgbm             : 3.3.2
matplotlib           : 3.5.1
networkx             : 2.7.1
nptyping             : 1.4.4
numpy                : 1.21.5
omegaconf            : 2.1.1
pandas               : 1.3.5
PIL                  : 9.0.1
psutil               : 5.8.0
pytorch_lightning    : 1.5.10
ray                  : None
requests             : 2.25.1
scipy                : 1.7.3
sentencepiece        : None
skimage              : 0.19.2
sklearn              : 1.0.2
smart_open           : 5.2.1
timm                 : 0.5.4
torch                : 1.10.2
torchmetrics         : 0.7.3
tqdm                 : 4.63.1
transformers         : 4.16.2
xgboost              : 1.4.2

</details>

**Additional context**

**Comment by Innixma** [comment]
The following code works without error in latest mainline:

```python3
from autogluon.tabular import TabularPredictor

import pandas as pd
import numpy as np
test_df = pd.DataFrame(["red", "blue"], columns=["target"])
test_df = test_df.sample(100, replace=True)
test_df["feature"] = np.random.uniform(size=len(test_df.index))
test_df.reset_index(inplace=True)

predictor = TabularPredictor(label="target", eval_metric='log_loss', problem_type='multiclass').fit(test_df)

```

```python3
predictor.leaderboard()
```

Output:

```
                  model     score_val  pred_time_val  fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0        NeuralNetTorch -2.332181e-07       0.004542  5.948062                0.004542           5.948062            1       True         12
1   WeightedEnsemble_L2 -2.332181e-07       0.005052  6.507298                0.000510           0.559236            2       True         14
2              LightGBM -2.463530e-05       0.001183  0.113383                0.001183           0.113383            1       True          4
3            LightGBMXT -2.463530e-05       0.001689  0.919757                0.001689           0.919757            1       True          3
4         LightGBMLarge -2.481816e-05       0.001753  0.148087                0.001753           0.148087            1       True         13
5       NeuralNetFastAI -4.777282e-04       0.014977  1.301494                0.014977           1.301494            1       True         10
6              CatBoost -1.185481e-03       0.002131  0.656810                0.002131           0.656810            1       True          7
7      RandomForestEntr -1.660689e-02       0.035347  0.364795                0.035347           0.364795            1       True          6
8        ExtraTreesEntr -1.723790e-02       0.035672  0.356910                0.035672           0.356910            1       True          9
9      RandomForestGini -1.814009e-02       0.036771  0.417157                0.036771           0.417157            1       True          5
10       ExtraTreesGini -1.826601e-02       0.030139  0.337227                0.030139           0.337227            1       True          8
11              XGBoost -2.487675e-02       0.004719  0.108312                0.004719           0.108312            1       True         11
12       KNeighborsUnif -6.736328e-01       0.004595  4.287292                0.004595           4.287292            1       True          1
13       KNeighborsDist -7.775871e-01       0.001653  0.003628                0.001653           0.003628            1       True          2
```
