### ISSUE TITLE
[BUG] SageMaker endpoint appears unable to load model file / use image paths as features

### ISSUE THREAD

**Issue by ijmiller2** [autogluon/autogluon#1644]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
```python
...
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from primary with message "[Errno 2] No such file or directory: '/.sagemaker/mms/models/model/predictor.pkl'
...
FileNotFoundError: [Errno 2] No such file or directory: '/.sagemaker/mms/models/model/predictor.pkl'
```

It appears that the SageMaker endpoint isn't able to find / open the model file. I was able to use the example code in the tutorial [Deploying AutoGluon Models with AWS SageMaker](https://auto.gluon.ai/stable/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-deployment.html) and managed to deploy an endpoint to SageMaker. But I get this error when I go to make predictions with test data. I wonder if this might be related to transition from MXNet to Pytorch and how their artifacts are typically stored? I'm using `v0.4.0` but the predictor object is `sagemaker.mxnet.model.MXNetPredictor`. This discrepancy in framework seems supported be a related error that I found in a GitHub issue [here](https://github.com/aws/amazon-sagemaker-examples/issues/1238).

Note also that I am attempting to adapt the example model trained in the [Multi-Modal documentation](https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-multimodal.html) (i.e., using the PetFinder dataset), because I'm ultimately try to deploy a multi-modal model and figure out how to pass image_paths to the SageMaker endpoint. 

Here's the full traceback:

```
---------------------------------------------------------------------------
ModelError                                Traceback (most recent call last)
<ipython-input-51-abf97eb84e0a> in <module>
----> 1 predictions = predictor.predict(test_data[:1].values)

~/anaconda3/envs/betterbin/lib/python3.8/site-packages/sagemaker/predictor.py in predict(self, data, initial_args, target_model, target_variant, inference_id)
    159             data, initial_args, target_model, target_variant, inference_id
    160         )
--> 161         response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
    162         return self._handle_response(response)
    163 

~/anaconda3/envs/betterbin/lib/python3.8/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    389                     "%s() only accepts keyword arguments." % py_operation_name)
    390             # The "self" in this scope is referring to the BaseClient.
--> 391             return self._make_api_call(operation_name, kwargs)
    392 
    393         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/betterbin/lib/python3.8/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    717             error_code = parsed_response.get("Error", {}).get("Code")
    718             error_class = self.exceptions.from_code(error_code)
--> 719             raise error_class(parsed_response, operation_name)
    720         else:
    721             return parsed_response

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from primary with message "[Errno 2] No such file or directory: '/.sagemaker/mms/models/model/predictor.pkl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sagemaker_inference/transformer.py", line 110, in transform
    self.validate_and_initialize(model_dir=model_dir)
  File "/usr/local/lib/python3.8/dist-packages/sagemaker_inference/transformer.py", line 158, in validate_and_initialize
    self._model = self._model_fn(model_dir)
  File "/opt/ml/model/code/tabular_serve.py", line 11, in model_fn
    model = TabularPredictor.load(model_dir)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/tabular/predictor/predictor.py", line 2816, in load
    predictor = cls._load(path=path)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/tabular/predictor/predictor.py", line 2772, in _load
    predictor: TabularPredictor = load_pkl.load(path=path + cls.predictor_file_name)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/common/loaders/load_pkl.py", line 37, in load
    with compression_fn_map[compression_fn]['open'](validated_path, 'rb', **compression_fn_kwargs) as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/.sagemaker/mms/models/model/predictor.pkl'
```

**Expected behavior**

**To Reproduce**

1. Train a multi modal model, using code adapted from [Multimodal Data Tables: Tabular, Text, and Image Tutorial](https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-multimodal.html): [petfinder_train.py](https://gist.github.com/ijmiller2/f5837977077674fe741fee031d2bad2a)
2. Deploy the pet finder model: [petfinder_deploy.py](https://gist.github.com/ijmiller2/f6b21c2b0b40211161d1fb0252542189)

**Screenshots**
NA

**Installed Versions**
Which version of AutoGluon are you are using?  
`0.4.0`
<details>

```python
# Replace this code with the output of the following:
INSTALLED VERSIONS
------------------
date                 : 2022-04-02
time                 : 19:45:52.692253
python               : 3.9.7.final.0
OS                   : Linux
OS-release           : 5.4.0-66-generic
Version              : #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021
machine              : x86_64
processor            : x86_64
num_cores            : 12
cpu_ram_mb           : 64324
cuda version         : None
num_gpus             : 0
gpu_ram_mb           : []
avail_disk_size_mb   : 289302

autogluon.common     : 0.4.0
autogluon.core       : 0.4.0
autogluon.features   : 0.4.0
autogluon.tabular    : 0.4.0
autogluon.text       : 0.4.0
autogluon.vision     : 0.4.0
autogluon_contrib_nlp: None
boto3                : 1.21.21
catboost             : 1.0.4
dask                 : 2021.11.2
distributed          : 2021.11.2
fairscale            : 0.4.6
fastai               : 2.5.3
gluoncv              : 0.11.0
lightgbm             : 3.3.2
matplotlib           : 3.5.1
networkx             : 2.7.1
nptyping             : 1.4.4
numpy                : 1.22.3
omegaconf            : 2.1.1
pandas               : 1.3.5
PIL                  : 9.0.1
psutil               : 5.8.0
pytorch_lightning    : 1.5.10
ray                  : 1.8.0
requests             : 2.27.1
scipy                : 1.7.3
sentencepiece        : None
skimage              : 0.19.2
sklearn              : 1.0.2
smart_open           : 5.2.1
timm                 : 0.5.4
torch                : 1.10.1+cpu
torchmetrics         : 0.7.2
tqdm                 : 4.63.0
transformers         : 4.16.2
xgboost              : 1.4.2
```

</details>

**Additional context**

I am attempting to follow the [tutorial to deploy a model via Sagemaker](https://auto.gluon.ai/stable/tutorials/cloud_fit_deploy/cloud-aws-sagemaker-deployment.html), however, adapting to use the example model trained in the [Multi-Modal documentation](https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-multimodal.html) (i.e., using the PetFinder dataset).

**Comment by ijmiller2** [comment]
Okay, I made a little bit of progress with this issue, but am still unable to use images / image_path's for a multi-modal (or ImagePredictor)-based SageMaker endpoint.

I was able to reproduce the example provided in the GitHub repo: [amazon-sagemaker-examples/advanced_functionality/autogluon-tabular-containers/AutoGluon_Tabular_SageMaker_Containers.ipynb](https://github.com/aws/amazon-sagemaker-examples/blob/main/advanced_functionality/autogluon-tabular-containers/AutoGluon_Tabular_SageMaker_Containers.ipynb). In doing so, I identified one of my issues with the directory structure: the **model.tar.gz file needs to be compressed within the AutoGluon output folder and not outside of it.** After making this change to my multi-modal endpoint adaption, I got a new error from the SageMaker endpoint that at least suggested it was able to load the model based on the provided path.

The new error I got was: `Exception: Invalid data format. Input data has 25 while the model expects 22`. This error appears to be derived from the `transform_fn` in the [tabular_serve.py](https://github.com/aws/amazon-sagemaker-examples/blob/main/advanced_functionality/autogluon-tabular-containers/scripts/tabular_serve.py) script (used as the `entry_point` in the endpoint deployment of the `AutoGluonInferenceModel`).

By restricting the features to those obtained from: `model.feature_metadata_in.get_features()`, which I noticed was being set as the global `column_names` variable in the `tabular_serve.py` script, I was able to get predictions based from the endpoint: 

```python
# load test data
import pandas as pd
test_data = pd.read_csv("petfinder_test_data.csv")

# load model locally (to get features recognized by SageMaker endpoint)
from autogluon.tabular import TabularPredictor
local_predictor = TabularPredictor.load("model/")
feature_cols = local_predictor.feature_metadata_in.get_features()
...
# omitting code to deploy endpoint for brevity
...
# test deployed endpointon first 5 examples
ex_test_data = test_data[feature_cols][:5].values
predictions = predictor.predict(ex_test_data)

```

In case it's helpful, here are the features returned by `local_predictor.feature_metadata_in.get_features()`:
<details>

```python
['Type',
 'Name',
 'Age',
 'Breed1',
 'Breed2',
 'Gender',
 'Color1',
 'Color2',
 'Color3',
 'MaturitySize',
 'FurLength',
 'Vaccinated',
 'Dewormed',
 'Sterilized',
 'Health',
 'Quantity',
 'Fee',
 'State',
 'RescuerID',
 'VideoAmt',
 'Description',
 'PhotoAmt']
```
</details>

Note that this subset of 22 features excludes the image_paths, so I'm still not sure how to handle those. I also tried the same general approach with just the [ImagePredictor]example(https://auto.gluon.ai/stable/tutorials/image_prediction/beginner.html), but encountered similar issues when trying to deploy a SageMaker endpoint via this example code.

So, I'm guessing what is needed to accomplish that is a different script such as `multi_modal_serve.py` or `image_predictor_serve.py` that has the appropriate `model_fn` and `transform_fn` functions.

I hope this is helpful in any troubleshooting. I'd very much appreciate any thoughts or feedback and would be happy to provide more info if it'd be helpful.

Thank you!
Ian

P.S. I just noticed that I missed a line in the training step to set properly set image_paths: 

`feature_metadata = feature_metadata.add_special_types({image_col: ['image_path']})`

I will try to update after retraining and deploying with this fix. However, I'm guessing I will still have issues deploying, so will  post any further updates here.

**Comment by Innixma** [comment]
Since this issue appears stale and we have recently released [AutoGluon-Cloud](https://auto.gluon.ai/cloud/stable/index.html) with image data support, I'll mark this as completed. Please open a new issue if the problem persists, thanks!
