### ISSUE TITLE
Enable GPU controls for inference

### ISSUE THREAD

**Issue by gradientsky** [autogluon/autogluon#1677]
As a customer using GPU for inference, I want to control if model can use GPU. If a model trained with GPU, but no GPU is available at the inference time, then the models should fall-back to CPU inference without issues.

**Comment by sxjscience** [comment]
A simple solution is to set CUDA_VISIBLE_DEVICES in the environmental variable.

**Comment by jturner116** [comment]
Hi! Any updates here? I'm trying to transition a TabularPredictor trained on GPU to CPU for inference (by setting no CUDA_VISIBLE_DEVICES) and am getting the following error
![image](https://user-images.githubusercontent.com/59941858/216140544-542b1d65-77a4-4623-b7d7-61fc8cc2c523.png)

**Comment by Innixma** [comment]
@sxjscience What is the status for CPU inference on GPU trained models for MultimodalPredictor? Refer to the above comment by @jturner116

**Comment by sxjscience** [comment]
@Innixma @jturner116 We support training the model with GPU and running inference with CPU.

**Comment by jturner116** [comment]
@sxjscience The MultimodalPredictor (thanks @Innixma , quite right) I was trying to use had a TextPredictor component. That's why it failed when taking over to CPU? Could I skip loading that model manually when loading on CPU?

**Comment by jturner116** [comment]
@sxjscience Yes, I was loading a saved TabularPredictor with these models
![image](https://user-images.githubusercontent.com/59941858/216169670-abcdf311-5927-44af-a749-00f09194cef8.png)
The model loaded on CPU but errored on inference.

**Comment by Innixma** [comment]
@jturner116 can you try training with the latest mainline / pre-release? A lot has changed since v0.6.2 regarding multimodal support in Tabular.

**Comment by Innixma** [comment]
@sxjscience Can we open a PR to add a section in quick-start tutorial on how to force CPU inference?

**Comment by sxjscience** [comment]
@Innixma @jturner116 I mean, if the instance has only CPUs, we will be using CPU inference by default and there is nothing else you need to do.

This is the most common scenarios we have right now.

**Comment by jturner116** [comment]
@sxjscience @Innixma This model was trained with v0.5.2, I will retrain on GPU with v0.6.2, I'm sure that will fix it.

**Comment by Innixma** [comment]
@jturner116 can you instead try pre-release?

```
pip install --pre autogluon
```

As I mentioned, a lot has changed in mainline in preparation for v0.7, so it would be most useful to check that things work in the pre-release.

**Comment by Innixma** [comment]
I am going to mark this as resolved for now, as I suspect it should work without issue in latest mainline / upcoming v0.7 release. Please re-open if you continue having issues.
