### ISSUE TITLE
[BUG] TabularPredictor with multimodal text and num_bag_folds>1 gets stuck

### ISSUE THREAD

**Issue by zhilongli** [autogluon/autogluon#1687]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
We have a tabular dataset with text features, when running TabularPredictor with `hyperparameters=multimodal`, and the `num_bag_folds=K` with K>1, the training gets stuck indefinitely with the warning 
```The actor or task with ID e2d939f6dfb9eeefb8a1f96179901fdf10863f2904f1272b cannot be scheduled right now. It requires {CPU: 3.000000}, {GPU: 1.000000} for placement, however the cluster currently cannot provide the requested resources. The required resources may be added as autoscaling takes place or placement groups are scheduled. Otherwise, consider reducing the resource requirements of the task.```

I am running the training in a docker container on WSL2, with 1 GPU resource provisioned to the container. I verified that the container is able to access the GPU, as running the training with the `ag_args_ensemble={'fold_fitting_strategy': "sequential_local"}` setting doesn't result in this warning and runs to completion; the training container logs also showed the GPU being utilized. 

The error seems to only occur when `fold_fitting_strategy="parallel_local"` and when the `TextPredictor_BAG_L1` model is being run. 

**Expected behavior**
The training should utilize the available GPU resource and run to completion with the `parallel_local` fold fitting strategy. 

**To Reproduce**
```
model = TabularPredictor(
    label=label_col, eval_metric="acc", path="./model_out", verbosity=2
)
model.fit(
    train_df,
    hyperparameters="multimodal",
    num_bag_folds=5,
    num_bag_sets=1,
    ag_args_ensemble={'fold_fitting_strategy': "parallel_local"}
)
```

**Screenshots**

**Installed Versions**
Which version of AutoGluon are you are using?  
v0.4.0

**Additional context**

**Comment by Innixma** [comment]
Fixed in upcoming v0.7 release
