### ISSUE TITLE
[v0.7] Properly min-cap torch version

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#1704]
Currently as of v0.4, the minimum torch version range is 1.0. This is likely too old and won't work, especially with the use of HuggingFace and PyTorch Lightning in `autogluon.text`. We should identify the valid minimum torch version and update our ranges.

**Comment by ddelange** [comment]
similarly, is the maximum pin intentional as there are breaking changes in [`1.11.0`](https://github.com/pytorch/pytorch/releases/tag/v1.11.0) that affect `autogluon.text`?

**Comment by ddelange** [comment]
on py3.8 the lowest version of torch available to pip is 1.8.0, which runs fine on py3.8 as far as I can tell:
```console
$ pip install -qU torch==1.8.* && python -c 'from autogluon.text import TextPredictor; print("yay")'
yay
```

was dropping py3.7 support considered before? also with security in mind ref https://github.com/awslabs/autogluon/blob/v0.4.1/core/src/autogluon/core/_setup_utils.py#L18

**Comment by Innixma** [comment]
@ddelange Thanks for looking into this! We want to keep Python 3.7 support for now as it is still widely used. For example, in AWS SageMaker Notebooks, the newest Python version in available kernels is unfortunately 3.7, making installation a massive pain if we don't support 3.7.

@sxjscience What you think about min capping torch to 1.8.0?

**Comment by sxjscience** [comment]
Mincap to 1.8.0 sounds good to me

**Comment by ddelange** [comment]
> similarly, is the maximum pin intentional as there are breaking changes in [`1.11.0`](https://github.com/pytorch/pytorch/releases/tag/v1.11.0) that affect `autogluon.text`?

and what about the API changes in 1.11? they look pretty harmless to me

**Comment by ddelange** [comment]
ah actually I got the heading nesting mixed up, more to review than I thought 😅

unless you trust CI it is probably not a blind bump

**Comment by sxjscience** [comment]
@ddelange i tried running the multilingual model (internally it is mdeberta-base) of autogluon.text and it will trigger an error in huggingface/transformers. I think it’s due to some internal change of PyTorch but haven’t investigated it yet.

**Comment by sxjscience** [comment]
I checked PT lightning and it has the version min-cap of torch: https://github.com/Lightning-AI/lightning/blob/176ca1fdccefbb99ad610ad422c74f0c59653a9c/requirements/base.txt#L2 We can rely on that for min-cap our own torch version.

**Comment by Innixma** [comment]
For v0.7 release, we are using `torch>=1.9,<1.14` as the range.
