### ISSUE TITLE
ValueError: Unknown keyword argument specified: problem_type

### ISSUE THREAD

**Issue by beansandroasters** [autogluon/autogluon#1760]
HI,
I'm trying to run autogluon based on this sample notebook, [AutoGluon_Tabular_SageMaker_Containers.ipynb](https://github.com/aws/amazon-sagemaker-examples/blob/main/advanced_functionality/autogluon-tabular-containers/AutoGluon_Tabular_SageMaker_Containers.ipynb).

I have checked that the original sample code can be run successfully.
After that, I added some changes;
- The dataset, which is for regression task.
- The columns in the sample code.
- the label in config file.

Then the error happens as below
```
ValueError: Unknown keyword argument specified: problem_type
Valid kwargs: ['ag_args', 'ag_args_ensemble', 'ag_args_fit', 'auto_stack', 'calibrate', 'excluded_model_types', 'feature_generator', 'feature_prune_kwargs', 'holdout_frac', 'hyperparameter_tune_kwargs', 'keep_only_best', 'name_suffix', 'num_bag_folds', 'num_bag_sets', 'num_stack_levels', 'pseudo_data', 'quantile_levels', 'refit_full', 'save_space', 'set_best_to_refit_full', 'unlabeled_data', 'use_bag_holdout', 'verbosity']
```
I didn't add `problem_type` explicitly and that is predicted by autogluon.

I need a help to solve this problem.

Thank you.

**Comment by Innixma** [comment]
Resolving as this problem has likely been addressed. Please re-open if it persists after v0.7 release.
