### ISSUE TITLE
Avoid failed install on Python 3.10+

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#1767]
Related issues: (Python 3.10: #1766)

In `autogluon<=0.0.15` releases, the `python_requires` value in `setup.py` was not max capped.

[Example for v0.0.15](https://github.com/awslabs/autogluon/blob/0fe281c44ddb83a629661e717d94fc27f47f892a/setup.py#L35): `MIN_PYTHON_VERSION = '>=3.6.*'`

[This was fixed starting in v0.1.0](https://github.com/awslabs/autogluon/blob/c75eaf2a79b38c03618cc926df661da655c0c733/core/src/autogluon/core/_setup_utils.py#L13): `PYTHON_REQUIRES = '>=3.6, <3.9'`

[As of v0.4, we also support Python 3.9](https://github.com/awslabs/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py#L13): `PYTHON_REQUIRES = '>=3.7, <3.10'`

The problem: Whenever someone tries to install AutoGluon with a newer version of Python than we currently support, such as 3.10 and 3.11, they will install AutoGluon v0.0.15. This will then fail in a variety of confusing ways as AutoGluon v0.0.15 does not actually support these new Python versions.

Solutions:

1. The nuclear option: Delete AutoGluon v0.0.15 and older from PyPi so they can't be pip installed.
    Pros: Users won't run into the issue anymore.
    Cons: Anyone using v0.0.15 or older will not be able to pip install it anymore ([not good](https://doughellmann.com/posts/so-youve-released-a-broken-package-to-pypi-what-do-you-do-now/)).
2. As (1) but re-release all versions identical to what they were but with proper version capping.
    Pros: Same as (1)
    Cons: Still altering a release (not good), but probably less bad than deleting it forever.
3. Release AutoGluon v0.0.16 that warns the user that they are using an unsupported python version. (Potentially crashing on install with the message if possible).
    Pros: If it can error on install, then it prevents the issue plus guides users towards documentation on the proper way to install.
    Cons: None?
4. [Yank](https://pypi.org/help/#yanked) all releases earlier than v0.1.0 from PyPi.
    Pros: Fixes the issue.
    Cons: None?
    Note: @zhanghang1989 : Can you please transfer AutoGluon package PyPi ownership to me for all subpackages? I need ownership to yank releases.

Based on these, I'd recommend we do option 3 or option 4.

**Comment by GuillemGSubies** [comment]
Python 3.10 is already a standard and I would love to see autogluon supporting it. Furthermore, this month, python 3.11 is being released.

**Comment by bra-fsn** [comment]
Any chance python >=3.10 will be supported/the above will be fixed in the near future?

**Comment by arturdaraujo** [comment]
@zhanghang1989 !

**Comment by arturdaraujo** [comment]
@Innixma Is there any projection for the release on python 3.11? This new release is much fsater

**Comment by Innixma** [comment]
Update to this issue: The original issue topic has been resolved via yanking all releases prior to v0.1.0 from PyPi, so I will be marking the issue as resolved.

@arturdaraujo, @bra-fsn, @GuillemGSubies
For a dedicated thread on Python version support, I created new GitHub issues: 
- Python 3.10 (#2686) - Planned for v0.7 in Feb 2023
- Python 3.11 (#2687) - Planned for v0.8 (tentative) in May 2023
