### ISSUE TITLE
.trial_0 folder with estimator.log file in ImagePredictor.[BUG] 

### ISSUE THREAD

**Issue by agupta284** [autogluon/autogluon#1801]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
.trial_0 folder with estimator.log file for each ImagePredictor training run in.

**Expected behavior**
Folder for logging file are getting stacked in the memory for each run. In live application each time training is done one additional folder is getting created for log file and all previous log file are also engage while app is live.(As I tried to delete the previous log files by writing addition line of code.)

**To Reproduce**
        train_data = ImageDataset.from_folder(folder_path)

        model = ImagePredictor(path=logger_folder)
        model.fit(train_data,hyperparameters = {'epochs':2})

**Screenshots**
![image](https://user-images.githubusercontent.com/60695339/173009698-46b2d13c-70a9-473a-ad61-c5ed4ab0610b.png)

**Installed Versions**
Which version of AutoGluon are you are using?  
I am using 0.4.3 version. Also tried 0.4.2 , but same issue there as well.

OS Name	     - Microsoft Windows 10 Pro
Version	     - 10.0.19043 Build 19043
System Type - x64-based PC
Processor      - 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz, 2496 Mhz, 8 Core(s), 16 Logical Processor(s)

**Comment by Innixma** [comment]
Marking as resolved, since v0.7 removes autogluon.vision in favor of autogluon.mulitmodal for vision tasks. Please create a new issue if problem persists in pre-release v0.7 or v0.7 official release.
