### ISSUE TITLE
Using AutoGluon in Colab

### ISSUE THREAD

**Issue by zhiqiangdon** [autogluon/autogluon#1971]
Takeaway:
You need to restart the runtime after installing autogluon.

Why?
Colab has a known issue that it has to restart the runtime to use the correct installed packages. See here: https://stackoverflow.com/questions/57831187/need-to-restart-runtime-before-import-an-installed-package-in-colab

We have found that, without a restart, Colab still uses the old pillow package (7.1.2) instead of the version ('>=9.0.1,<9.1.0') required by autogluon. This would cause opening images errors, resulting in that `MultiModalPredictor` can't detect image data.

**Comment by talhaanwarch** [comment]
this is default behavior of colab. mostly you need to restart kernal and run the pips again

**Comment by sxjscience** [comment]
@zhiqiangdon I'm closing the issue.
