### ISSUE TITLE
Tabular Data - Key Error with Customer Metric and Out of Memory Error with default metric

### ISSUE THREAD

**Issue by bkhandel** [autogluon/autogluon#1998]
Hi,

I am trying run AG fit with custom metric on tabular train data. I am getting error (error_1.txt file). When I run without custom metric - it gives error 2. Looking for support to resolve these two errors.

I am able to run separate LGBM model on the same data. Not sure what's breaking. Training script, sample train data, custom metric definition, error attached. Custom metric is defined in a separate file named "custom_metric.py". 

Some useful info:

train.shape
(458913, 1367)

test.shape
(924621, 1366)

[AG Train Script.txt](https://github.com/awslabs/autogluon/files/9223971/AG.Train.Script.txt)
[custom_metric.txt](https://github.com/awslabs/autogluon/files/9223972/custom_metric.txt)
[Error_1.txt](https://github.com/awslabs/autogluon/files/9223973/Error_1.txt)
[Error_2.txt](https://github.com/awslabs/autogluon/files/9223974/Error_2.txt)
[LGBM.txt](https://github.com/awslabs/autogluon/files/9223981/LGBM.txt)

**Comment by Innixma** [comment]
You are out of disk space. You need to increase available disk space on your machine.
