### ISSUE TITLE
[Multimodal] Add Documentation for using Tensorboard in AutoMM

### ISSUE THREAD

**Issue by atabari-bci** [autogluon/autogluon#2049]
Hi,

I have three questions:

1. When calling fit, you can set visualizer='tensorboard'. Is there a way to do the same thing in AutoMM?
2. My data is a long text field plus a veriety of tabular features. I want the text be processed with a Transformer and all features are important (text and tabular). Which predictor is better to use (text, tabular, AutoMM)? both for best performance, and deploying for production.
3. Tabular has the preset for fast inference, but AutoMM does not have this preset. Is there a reason for that?

Thanks,
Armin

**Comment by sxjscience** [comment]
Hi @atabari-bci , actually, tensorboard is automatically turned on in AutoMM. You can visualize the training results by running 

```bash
tensorboard --logdir MODEL_DIR
```

We need to improve our documentation to demonstrate that.

**Comment by sxjscience** [comment]
@atabari-bci

For 2 , I will suggest first try AutoMM to check the performance (following https://auto.gluon.ai/stable/tutorials/multimodal/multimodal_text_tabular.html). It will give you a single DL-based model that can be easily deployed. After that, you can try tabular with "multimodal" presets (following https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-multimodal.html) to obtain better performance.

For 3, AutoMM also has the presets `presets="medium_quality_faster_train"`.

**Comment by sxjscience** [comment]
FYI @suzhoum

**Comment by sxjscience** [comment]
I think it is partially resolved via the PR https://github.com/autogluon/autogluon/pull/2859

**Comment by Innixma** [comment]
@sxjscience please resolve this issue if you think the overall ask is resolved, or else indicate the next-steps that would need to be taken

**Comment by sxjscience** [comment]
Resolved since we now have tensorboard instructions in .fit()
