### ISSUE TITLE
how to config  TextPredictor batch size and text max_length

### ISSUE THREAD

**Issue by springwings** [autogluon/autogluon#2087]
preprocessing:
  categorical:
    convert_to_text: False
    maximum_num_cat: 20
    minimum_cat_count: 100
  numerical:
    convert_to_text: False
    impute_strategy: mean
    scaler_with_mean: True
    scaler_with_std: True
  text:
    auto_max_length: True
    auto_max_length_quantile: 0.95
    auto_max_length_round_to: 32
    max_length: 512
    merge: True

**Comment by sxjscience** [comment]
@springwings 


For max length, you may configure with the following:
```python
predictor.fit(hyperparameters={"model.hf_text.max_text_len": 512})
```

For batch size, you may configure with the following:
```python
predictor.fit(hyperparameters={"env.batch_size": 128})
```

You can revise the hyperparameters to configure how the predictor preprocess the data, build the models, and perform model training. For more details, check https://auto.gluon.ai/stable/tutorials/multimodal/customization.html#environment. You may note that it's the document for `MultiModalPredictor`, but `MultiModalPredictor` is actually a super-set of `TextPredictor`. You can configure the `TextPredictor` the same way as you are configuring `MultiModalPredictor`.

**Comment by sxjscience** [comment]
@springwings Do you still have issues? If not, I'm going to close this issue.
