### ISSUE TITLE
[BUG] EvalMetric "spearmanr" doesn't work on GPU

### ISSUE THREAD

**Issue by hey24sheep** [autogluon/autogluon#2165]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
Bug is, 
`TypeError: Expected 'preds' and 'target' to have the same data type. Got preds: torch.float16 and target: torch.float32.`

This bug occurs when "MultiModalPredictor" is used with "eval_metric='spearmanr;".

**Expected behavior**
It should work normally without any errors

**To Reproduce**
Just create any demo data and run it with 'spearmanr' as `eval_metric`
`predictor = MultiModalPredictor(label='target', path='save_path', eval_metric='spearmanr')
predictor.fit(df)
`

**Installed Versions**
Which version of AutoGluon are you are using?  
If you are using 0.4.0 and newer, please run the following code snippet:
<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```
INSTALLED VERSIONS
------------------
date                   : 2022-09-25
time                   : 18:04:47.405997
python                 : 3.7.12.final.0
OS                     : Linux
OS-release             : 5.15.65+
Version                : #1 SMP Fri Sep 16 09:01:09 UTC 2022
machine                : x86_64
processor              : x86_64
num_cores              : 2
cpu_ram_mb             : 16006
cuda version           : 11.470.82.01
num_gpus               : 1
gpu_ram_mb             : [15217]
avail_disk_size_mb     : 19342

autogluon.common       : 0.5.2
autogluon.core         : 0.5.2
autogluon.features     : 0.5.2
autogluon.multimodal   : 0.5.2
autogluon.tabular      : 0.5.2
autogluon.text         : 0.5.2
autogluon.timeseries   : 0.5.2
autogluon.vision       : 0.5.2
autogluon_contrib_nlp  : 0.0.1
boto3                  : 1.24.72
catboost               : 1.0.6
dask                   : 2021.11.2
distributed            : 2021.11.2
fairscale              : 0.4.6
fastai                 : 2.7.9
gluoncv                : 0.11.0
gluonts                : 0.9.9
hyperopt               : 0.2.7
lightgbm               : 3.3.2
matplotlib             : 3.5.3
networkx               : 2.5
nlpaug                 : 1.1.10
nltk                   : 3.7
nptyping               : 1.4.4
numpy                  : 1.21.6
omegaconf              : 2.1.2
pandas                 : 1.3.5
PIL                    : 9.0.1
protobuf               : None
psutil                 : 5.8.0
pytorch-metric-learning: None
pytorch_lightning      : 1.6.5
ray                    : 1.13.0
requests               : 2.28.1
scipy                  : 1.7.3
sentencepiece          : None
skimage                : 0.19.3
sklearn                : 1.0.2
smart_open             : 5.2.1
timm                   : 0.5.4
torch                  : 1.11.0
torchmetrics           : 0.7.3
torchtext              : 0.12.0
torchvision            : 0.12.0
tqdm                   : 4.64.0
transformers           : 4.20.1
xgboost                : 1.4.2
</details>

**Additional context**
<summary>
<details>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_3775/1065712823.py in <module>
      9               hyperparameters={
     10                   "optimization.max_epochs": 240,
---> 11                   "optimization.patience": 200
     12               })

/opt/conda/lib/python3.7/site-packages/autogluon/multimodal/predictor.py in fit(self, train_data, presets, config, tuning_data, time_limit, save_path, hyperparameters, column_types, holdout_frac, teacher_predictor, seed, hyperparameter_tune_kwargs)
    509             return predictor
    510 
--> 511         self._fit(**_fit_args)
    512         return self
    513 

/opt/conda/lib/python3.7/site-packages/autogluon/multimodal/predictor.py in _fit(self, train_df, val_df, validation_metric_name, minmax_mode, max_time, save_path, ckpt_path, resume, enable_progress_bar, presets, config, hyperparameters, teacher_predictor, hpo_mode, **hpo_kwargs)
   1089                 task,
   1090                 datamodule=train_dm,
-> 1091                 ckpt_path=ckpt_path if resume else None,  # this is to resume training that was broken accidentally
   1092             )
   1093 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    769         self.strategy.model = model
    770         self._call_and_handle_interrupt(
--> 771             self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    772         )
    773 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    721                 return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
    722             else:
--> 723                 return trainer_fn(*args, **kwargs)
    724         # TODO: treat KeyboardInterrupt as BaseException (delete the code below) in v1.7
    725         except KeyboardInterrupt as exception:

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    809             ckpt_path, model_provided=True, model_connected=self.lightning_module is not None
    810         )
--> 811         results = self._run(model, ckpt_path=self.ckpt_path)
    812 
    813         assert self.state.stopped

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
   1234         self._checkpoint_connector.resume_end()
   1235 
-> 1236         results = self._run_stage()
   1237 
   1238         log.detail(f"{self.__class__.__name__}: trainer tearing down")

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _run_stage(self)
   1321         if self.predicting:
   1322             return self._run_predict()
-> 1323         return self._run_train()
   1324 
   1325     def _pre_training_routine(self):

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _run_train(self)
   1343 
   1344         with isolate_rng():
-> 1345             self._run_sanity_check()
   1346 
   1347         # enable train mode

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _run_sanity_check(self)
   1411             # run eval step
   1412             with torch.no_grad():
-> 1413                 val_loop.run()
   1414 
   1415             self._call_callback_hooks("on_sanity_check_end")

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py in run(self, *args, **kwargs)
    202             try:
    203                 self.on_advance_start(*args, **kwargs)
--> 204                 self.advance(*args, **kwargs)
    205                 self.on_advance_end()
    206                 self._restarting = False

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py in advance(self, *args, **kwargs)
    153         if self.num_dataloaders > 1:
    154             kwargs["dataloader_idx"] = dataloader_idx
--> 155         dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
    156 
    157         # store batch level output per dataloader

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/base.py in run(self, *args, **kwargs)
    202             try:
    203                 self.on_advance_start(*args, **kwargs)
--> 204                 self.advance(*args, **kwargs)
    205                 self.on_advance_end()
    206                 self._restarting = False

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py in advance(self, data_fetcher, dl_max_batches, kwargs)
    126 
    127         # lightning module methods
--> 128         output = self._evaluation_step(**kwargs)
    129         output = self._evaluation_step_end(output)
    130 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py in _evaluation_step(self, **kwargs)
    224             output = self.trainer._call_strategy_hook("test_step", *kwargs.values())
    225         else:
--> 226             output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
    227 
    228         return output

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _call_strategy_hook(self, hook_name, *args, **kwargs)
   1763 
   1764         with self.profiler.profile(f"[Strategy]{self.strategy.__class__.__name__}.{hook_name}"):
-> 1765             output = fn(*args, **kwargs)
   1766 
   1767         # restore current_fx when nested context

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/strategies/strategy.py in validation_step(self, *args, **kwargs)
    342         """
    343         with self.precision_plugin.val_step_context():
--> 344             return self.model.validation_step(*args, **kwargs)
    345 
    346     def test_step(self, *args, **kwargs) -> Optional[STEP_OUTPUT]:

/opt/conda/lib/python3.7/site-packages/autogluon/multimodal/optimization/lit_module.py in validation_step(self, batch, batch_idx)
    216             custom_metric_func=self.custom_metric_func,
    217             logits=output[self.model.prefix][LOGITS],
--> 218             label=batch[self.model.label_key],
    219         ),
    220         self.log(

/opt/conda/lib/python3.7/site-packages/autogluon/multimodal/optimization/lit_module.py in _compute_metric_score(self, metric, custom_metric_func, logits, label)
    154             metric.update(custom_metric_func(logits, label))
    155         else:
--> 156             metric.update(logits.squeeze(dim=1), label)
    157 
    158     def _shared_step(

/opt/conda/lib/python3.7/site-packages/torchmetrics/metric.py in wrapped_func(*args, **kwargs)
    265             self._update_called = True
    266             with torch.set_grad_enabled(self._enable_grad):
--> 267                 return update(*args, **kwargs)
    268 
    269         return wrapped_func

/opt/conda/lib/python3.7/site-packages/torchmetrics/regression/spearman.py in update(self, preds, target)
     88             target: Ground truth values
     89         """
---> 90         preds, target = _spearman_corrcoef_update(preds, target)
     91         self.preds.append(preds)
     92         self.target.append(target)

/opt/conda/lib/python3.7/site-packages/torchmetrics/functional/regression/spearman.py in _spearman_corrcoef_update(preds, target)
     63     if preds.dtype != target.dtype:
     64         raise TypeError(
---> 65             "Expected `preds` and `target` to have the same data type."
     66             f" Got preds: {preds.dtype} and target: {target.dtype}."
     67         )

TypeError: Expected `preds` and `target` to have the same data type. Got preds: torch.float16 and target: torch.float32.
</details>
</summary>

**Comment by hey24sheep** [comment]
There is a temporary solution to this. I hope this solution is right.

```python
from autogluon.core.metrics import make_scorer

def custom_spearmanr(x, y):
    return scipy.stats.spearmanr(x.to(torch.float16), y.to(torch.float16))

custom_spearmanr_scorer = make_scorer(name='custom_spearmanr',
                                 score_func=custom_spearmanr,
                                 optimum=1,
                                 greater_is_better=True)
```

**Comment by Innixma** [comment]
@sxjscience Looks like #2857 has been merged. Feel free to resolve if the issue has been fixed.
