### ISSUE TITLE
Can't train Multimodal model with models like categorical transformer and numerical transformer

### ISSUE THREAD

**Issue by Priyadrasta-2111CS10** [autogluon/autogluon#2170]
When I try to train the multimodal model with models such as `"categorical_transformer"` and  `numerical_transformer` , it throws some errors:

With `numerical_transformer`, I encountered  error that says **UnboundLocalError: local variable 'fusion_model' referenced before assignment** as shown below

<img width="877" alt="image" src="https://user-images.githubusercontent.com/92008353/192512745-17ee5faa-4002-4d91-9e43-2035561b57d7.png">

whereas With `categorical_transformer`,`fusion_transformer`,`categorical_mlp` I encountered an error that says **ValueError: No model is available for this dataset.**  as shown below

<img width="877" alt="image" src="https://user-images.githubusercontent.com/92008353/192513198-e52bb784-dffd-4be4-bcc6-0f5b5819f046.png">

The datatypes of my current dataset are as follows:
```
Var1                     object
numWhitePixels_left       int64
numWhitePixels_right      int64
diff_pixel                int64
left_area               float64
right_area              float64
diff_area               float64
Score (AP)              float64
image                    object
dtype: object

```

**Comment by sxjscience** [comment]
@Priyadrasta-2111CS10 Is it possible to share the command you used for training? We can take a look.

**Comment by Priyadrasta-2111CS10** [comment]
`from autogluon.multimodal import MultiModalPredictor
predictor = MultiModalPredictor(label="Score")
predictor.fit(
    train_data=df_train, time_limit=60, # seconds
    hyperparameters={"model.names": ["categorical_transformer"]}
)`

this is the command I am using for training

**Comment by sxjscience** [comment]
you may try to use:

hyperparameters={"model.names": ["categorical_transformer", " numerical_transformer", "fusion_transformer" ]}

**Comment by Priyadrasta-2111CS10** [comment]
`from autogluon.multimodal import MultiModalPredictor
predictor = MultiModalPredictor(label="Score")
predictor.fit(
    train_data=df_train, time_limit=60, # seconds
    hyperparameters={"model.names": ["categorical_transformer", " numerical_transformer", "fusion_transformer" ]}
)`

After training with the above code, I am still facing the same issue mentioned above.

<img width="914" alt="image" src="https://user-images.githubusercontent.com/92008353/193453104-9b3184f9-8a11-48e0-9349-0e5c15ad5273.png">

**Comment by sxjscience** [comment]
I see. You should also set “data.categorical.convert_to_text” to False

**Comment by Priyadrasta-2111CS10** [comment]
**it's still not  working**

<img width="911" alt="image" src="https://user-images.githubusercontent.com/92008353/193453664-173b01e1-f107-4378-8db8-255be04d0b66.png">

**Comment by sxjscience** [comment]
Can you share a example data file with us? Also, can you train the model if you just do not specify the hyperparameter?

**Comment by sxjscience** [comment]
Also, just to verify if the latest version works. Can you try to install AutoGluon multimodal via “python3 -m pip install autogluon.multimodal --pre”

**Comment by Priyadrasta-2111CS10** [comment]
> Can you share a example data file with us? Also, can you train the model if you just do not specify the hyperparameter?

Yes,  it's working without any hyperparameter.
and my dataset snap is as follows
<img width="916" alt="image" src="https://user-images.githubusercontent.com/92008353/193454396-7907d801-8cb4-4b1b-8156-f4564a04bef5.png">

**Comment by sxjscience** [comment]
The dataset seems to contain images. Do you like to use the combination of categorical transformer, numerical transformer, fusion_transformer, and timm?

**Comment by Priyadrasta-2111CS10** [comment]
Yes, the dataset contains images in the first place. That's why I am using the MultiModal framework.  I would like to use any type of suitable model or combination of models if it improves the accuracy.If you have any idea how to achieve promising results in terms of accuracy, please suggest

**Comment by sxjscience** [comment]
@Priyadrasta-2111CS10 can you try again with the latest pre-release of autogluon?

```bash
python3 -m pip install --pre autogluon
```

In addition, if possible, you may share a sample dataset with me via email so I can help take a look

**Comment by Priyadrasta-2111CS10** [comment]
I mailed on this mail id : xshiab@connect.ust.hk.Please get back to me here after you get any idea regarding the issue with the dataset or code.

Please find the below link for the sample repository of the same sent via email.
 [https://drive.google.com/drive/folders/1-oViyCaiMiHZ6HN-7xSBM1t8UcSmihoF?usp=sharing](url)

**Comment by Innixma** [comment]
Marking as resolved for now. Please create a new issue if problem persists in latest pre-release or v0.7+ releases.

**Comment by Innixma** [comment]
@sxjscience feel free to re-open if I am closing pre-maturely
