### ISSUE TITLE
Add M2 Mac Support

### ISSUE THREAD

**Issue by gradientsky** [autogluon/autogluon#2271]
M2 Apple Silicon Support Discussion Thread

See also #1242 for M1 issues

**Comment by gradientsky** [comment]
@giswqs made a big contribution in getting `autogluon` and it's missing dependencies into conda-forge. If anyone with M2 chip want to give it a try, I suggest taking a look at instructions here: https://github.com/autogluon/autogluon/issues/1242#issuecomment-1408831067
Please let us know if it works.

**Comment by GeorgeNassef** [comment]
About to try it on MacBook Pro M2 (2023) maximum config.

**Comment by Innixma** [comment]
I believe AutoGluon should now be supported on M2 Mac, please mention if you run into issues.
