### ISSUE TITLE
[BUG] autogluon.multimodal incompatible with latest versions of pytorch lightning (v1.7 and v1.8)

### ISSUE THREAD

**Issue by akanakia** [autogluon/autogluon#2299]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
When attempting to install autogluon alongside pytorch-lightning via Poetry package manager in python, I run into the following dependency issue:

```bash
  Because no versions of autogluon match >0.5.2,<0.6.0
   and autogluon (0.5.2) depends on autogluon.multimodal (0.5.2), autogluon (>=0.5.2,<0.6.0) requires autogluon.multimodal (0.5.2).
  And because autogluon.multimodal (0.5.2) depends on pytorch-lightning (>=1.6.0,<1.7.0), autogluon (>=0.5.2,<0.6.0) requires pytorch-lightning (>=1.6.0,<1.7.0).
  So, because mlabs-de-novo-design depends on both pytorch-lightning (^1.7.7) and autogluon (^0.5.2), version solving failed.
```

**Expected behavior**
Autogluon should work with pytorch-lightning>=1.6. 

**To Reproduce**
Requires Poetry. 

```bash
poetry add pytorch-lightning
poetry add autogluon
```

**Screenshots**

**Installed Versions**
Which version of AutoGluon are you are using?  
0.5.2

**Comment by gradientsky** [comment]
Looks like you are restricting `pytorch-lightning` to `^1.7.7` while autogluon needs `>=1.6.0,<1.7.0`. We will be releasing updates soon. This would be fixed in `0.5.3` and `0.6.0`.

**Comment by akanakia** [comment]
We are unfortunately locked in to pytorch-lightning ^1.7.7 due to other dependencies in our project. Just wondering if there is way around this near term or if we have to wait for 0.5.3.

**Comment by sxjscience** [comment]
@akanakia You may wait for 0.6 that we will release very soon. The 0.6 version has upgraded lightning: https://github.com/awslabs/autogluon/blob/d9aab7852604a3f1b4b8a6d2f051aadfb8b3a60c/multimodal/setup.py#L42.

You can also try:

```
python3 -m pip install autogluon --pre
```

**Comment by Innixma** [comment]
Marking as resolve, please re-open if issue persists in v0.6+
