### ISSUE TITLE
[BUG] Different behavior of setup.py

### ISSUE THREAD

**Issue by yinweisu** [autogluon/autogluon#2368]
In our CI, we install our package through `python3 -m pip install -e ./module`
This setup, for some reason, has packages like `sys` and `os` by default even when we didn't import it.
For example, put this line at the top of setup.py won't fail the installation process
```python
assert isinstance(sys.platform, str)
```

However, `sys` is not there when we build the package for distribution:
```bash
$ python setup.py sdist bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    assert isinstance(sys.platform, str)
NameError: name 'sys' is not defined
```

This difference in behavior would allow bug regarding installation slip away in the CI but fail the actual distribution. Will need to investigate

**Comment by Innixma** [comment]
@yinweisu Please double check status of this and mark as resolved if fixed.

**Comment by yinweisu** [comment]
Close as we are testing wheels building in our CI now.
