### ISSUE TITLE
Jupyter Kernel crashes in Windows

### ISSUE THREAD

**Issue by slavakx** [autogluon/autogluon#2399]
Hi, 

Jupyter kernel crashes each time. I suppose it has something to do with Ray. 
autogluon: 0.5.2
ray: 1.13.0

![image](https://user-images.githubusercontent.com/6716523/201985535-8a34694a-58e9-4c54-891c-274151a1e367.png)

**Comment by Innixma** [comment]
Marking as resolved for now, please re-open if issue persists with v0.6.2 or pre-release.
