### ISSUE TITLE
[Post 0.6] Speed up AutoMM tutorial build

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#2428]
Currently as of v0.6 release, AutoMM tutorials take >90 minutes to run, accounting for ~75% of the wall-clock time of the CI. This is too long and makes development cumbersome.

It should be shorted to ideally wall-clock 30 minutes, and 45 minutes at most.

**Comment by sxjscience** [comment]
Can we separate the tutorial build pipeline to build tutorial for each folder under "multimodal"?

- [text_prediction](https://github.com/awslabs/autogluon/tree/master/docs/tutorials/multimodal/text_prediction)
- [object_detection](https://github.com/awslabs/autogluon/tree/master/docs/tutorials/multimodal/object_detection)
- [multimodal_prediction](https://github.com/awslabs/autogluon/tree/master/docs/tutorials/multimodal/multimodal_prediction)
- [matching](https://github.com/awslabs/autogluon/tree/master/docs/tutorials/multimodal/matching)
- [image_prediction](https://github.com/awslabs/autogluon/tree/master/docs/tutorials/multimodal/image_prediction)
- [advanced_topics](https://github.com/awslabs/autogluon/tree/master/docs/tutorials/multimodal/advanced_topics)
