### ISSUE TITLE
custom model training fails in the multi-layer stack ensemble

### ISSUE THREAD

**Issue by tornshaw** [autogluon/autogluon#2438]
Hi
**Describe the bug**
When I add a custom model to ag， it can't be fitted with multi-layer stacking. 
However, the custom model works fine with single-layer stacking.
I have tried the examples of the official website, ag tutorials in github and LI Mu's, the issue still exists.
My ag and python version is 0.5.2 and 3.9.13.

**Code**
custom_hyperparameters = get_hyperparameter_config('default')
custom_hyperparameters[CustomRandomForestModel] = best_model_info['hyperparameters']
predictor = TabularPredictor(label=label).fit(train_data, hyperparameters=custom_hyperparameters, presets='best_quality') 

**Screenshots**
![image](https://user-images.githubusercontent.com/39145280/202610223-32bffc8d-885a-494f-8c80-9df98710cb86.png)

**Comment by Innixma** [comment]
You need to have your custom model be in a separate file from your run script, otherwise it isn't serializable.
