### ISSUE TITLE
Missing dataset to run the Time Series Forecasting Quick Start and In-Depth examples

### ISSUE THREAD

**Issue by fantauzzi** [autogluon/autogluon#2496]
### Describe the issue linked to the documentation

The [quick start](https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-quickstart.html#) and [the in-depth](https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-indepth.html) for Time Series Forecasting give samples of code I am unable to run, because the necessary dataset is missing. 

The documentation mentions that the required dataset (`m4_hourly.csv`) comes from the M4 Forecasting Competition, but it provides no instruction to download it. I have downloaded the dataset from Kaggle's M4 Forecasting Competition, but none of those files is suitable, and they don't work with the sample code: their content is very different from what is supposed to be, based on screenshots in AutoGluon documentation, e.g.

![Screenshot 2022-11-30 at 11-17-20 Forecasting Time Series - Quick Start — AutoGluon Documentation 0 6 0 documentation](https://user-images.githubusercontent.com/2722433/204770124-2b47e76e-5796-4244-a2c2-511b573bed0c.png)

I have also looked in AutoGluon GitHub repo, and cannot find a file called `m4_hourly.csv`

### Suggest a potential alternative/fix

You could provide instructions to download the required dataset `m4_hourly.csv`. 
The issue would be less impactful  if you provided working examples for time series predictions in your GitHub repo, but I cannot find any. It would be good to have at least one of those (better if it exemplifies the use of multi-window backtesting too).

**Comment by gidler** [comment]
In the [quick_start](https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-quickstart.html#) tutorial in Section `Loading time series data as a TimeSeriesDataFrame`, there is clickable icon that looks like "> Details" than reveals the code snippet used to download the dataset. There is a similar entry in the [in-depth](https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-indepth.html) tutorial. Does this code address your issue? Perhaps the expandable section is too inconspicuous.

**Comment by fantauzzi** [comment]
Yes that solved my issue. I had overlooked the "Details" with the little arrow. Thank you.
