### ISSUE TITLE
[timeseries] DeepAR - cuDNN version incompatibility check

### ISSUE THREAD

**Issue by gradientsky** [autogluon/autogluon#2534]
I am doing sanity checks for 0.6.0 DLCs and getting the following line in logs about cublas:
```
Training timeseries model DeepAR.
Could not load symbol cublasGetSmCountTarget from libcublas.so.11. Error: /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.11: undefined symbol: cublasGetSmCountTarget
	-1.5870       = Validation score (-sMAPE)
	5.36    s     = Training runtime
	0.30    s     = Validation (prediction) runtime
```
The model is trained though. Versions:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

In inference container I’m seeing this:
```
Training timeseries model DeepAR.
	Warning: Exception caused DeepAR to fail during training... Skipping this model.
	cuDNN version incompatibility: PyTorch was compiled against (8, 3, 2) but linked against (8, 1, 1)
Fitting simple weighted ensemble.
	-0.3044       = Validation score (-sMAPE)
	5.11    s     = Training runtime
	6.46    s     = Validation (prediction) runtime

```

**Comment by gradientsky** [comment]
Analysis by @shchur:

DeepAR uses LSTM, and PyTorch uses the CUDNN backend for LSTM (and other RNN models). In version 1.12.0, there is a check that validates if the compile/runtime version of CUDNN match, and raises an exception if they don’t https://github.com/pytorch/pytorch/blob/v1.12.0/torch/backends/cudnn/__init__.py.

Here are the possible fixes:
1. Ignore this problem and tell users that they shouldn’t train forecasting models on the inference image (is using the inference image for forecasting a common use case?)
2. Upgrade torch to 1.12.1 and disable the check by setting an environment variable
`export PYTORCH_SKIP_CUDNN_COMPATIBILITY_CHECK=1`
    (this flag was only introduced in 1.12.1, not available in 1.12.0 that we currently have in the image)
3. I can disable the CUDNN backend completely with `torch.backends.cudnn.enabled = False` if the detected torch version is `<= 1.12.0` in AGTS code, but this can lead to performance regressions for users (CUDNN implementation of RNNs is way faster than others)

**Comment by canerturkmen** [comment]
I ran the updated sanity check script on both the 0.6.2 training and inference containers. Both seem to be doing OK. 

I propose to punt and keep an eye on this issue going forward. 

Side note, on the training container DeepAR now logs the following warnings:

```
[2023-02-10 15:02:03.393: W smdistributed/modelparallel/torch/nn/predefined_hooks.py:78] Found unsupported HuggingFace version 4.23.1 for automated tensor parallelism. HuggingFace modules will not be automatically distributed. You can use smp.tp_register_with_module API to register desired modules for tensor parallelism, or directly instantiate an smp.nn.DistributedModule. Supported HuggingFace transformers versions for automated tensor parallelism: ['4.17.0', '4.20.1', '4.21.0']
[2023-02-10 15:02:03.437 a4ec2f580b40:161 INFO utils.py:28] RULE_JOB_STOP_SIGNAL_FILENAME: None
/opt/conda/lib/python3.8/site-packages/smdebug-1.0.24b20230106-py3.8.egg/smdebug/profiler/system_metrics_reader.py:78: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/opt/conda/lib/python3.8/site-packages/smdebug-1.0.24b20230106-py3.8.egg/smdebug/profiler/system_metrics_reader.py:78: SyntaxWarning: "is not" with a literal. Did you mean "!="?
[2023-02-10 15:02:03.598 a4ec2f580b40:161 INFO profiler_config_parser.py:111] Unable to find config at /opt/ml/input/config/profilerconfig.json. Profiler is disabled.
```

**Comment by shchur** [comment]
Most likely, this will be automatically resolved once we switch to the new base image for our container with PyTorch v1.13.1 and new CUDNN version. Will need to investigate after the container is released (or at least when we know the specs of the container).
