### ISSUE TITLE
A way visualize batches of images from the MultiModalPredictor?

### ISSUE THREAD

**Issue by KirderfEman** [autogluon/autogluon#2546]
### Describe the issue linked to the documentation

Hi,
Is there a way to get the processed/augmented images from a MultiModalPredictor?
The only way I managed getting out some processed images is via the get_processed_batch_for_deployment and _process_batch, but the they only show unprocessed raw images not after augmentations.

Anyway, I found nothing about in the documentation, so would be great creating such.

Thanks!

**Comment by sxjscience** [comment]
May be you can fetch `predictor._data_processors`, which will contain the processor for all the columns in the dataframe.

https://github.com/autogluon/autogluon/blob/8116f275f30e2c0f360808382b2905cf41796eee/multimodal/src/autogluon/multimodal/predictor.py#L410

Within these processors, one will be `ImageProcessor`: https://github.com/autogluon/autogluon/blob/8116f275f30e2c0f360808382b2905cf41796eee/multimodal/src/autogluon/multimodal/data/process_image.py#L74

You can then call the following function https://github.com/autogluon/autogluon/blob/8116f275f30e2c0f360808382b2905cf41796eee/multimodal/src/autogluon/multimodal/data/process_image.py#L474-L475

**Comment by KirderfEman** [comment]
Thanks!
Here is how to do it:

from PIL import Image
import matplotlib.pyplot as plt 
img = Image.open(##image##)
img = img.convert('RGB')
img = predictor._data_processors['image'][0].train_processor(img)
plt.imshow(img.permute(1, 2, 0))
