### ISSUE TITLE
[Improvement] Improve AutoMM Early Stopping Criteria

### ISSUE THREAD

**Issue by sxjscience** [autogluon/autogluon#2555]
Currently, the early stopping callback only uses `patience` and `mode`.

https://github.com/autogluon/autogluon/blob/8116f275f30e2c0f360808382b2905cf41796eee/multimodal/src/autogluon/multimodal/predictor.py#L1397-L1401

This is not optimal because some models may:

- Saturate the performance in the early stage of training 

   In the following, the model has reached `val_roc_auc` to be `1.0` but still keeps training.

   ```python
   Epoch 3, global step 55263: 'val_roc_auc' reached 1.00000 (best 1.00000), saving model to '/home/ec2-user/SageMaker/t
   ```

One option is to use the `stopping_threshold` flag in the EarlyStopping callback: https://pytorch-lightning.readthedocs.io/en/stable/common/early_stopping.html

**Comment by Innixma** [comment]
@sxjscience @zhiqiangdon Please update status or mark as resolved if addressed.

**Comment by sxjscience** [comment]
Resolved via https://github.com/autogluon/autogluon/pull/2633
