### ISSUE TITLE
How to use Weights and Biases with AutoGluon?

### ISSUE THREAD

**Issue by pj-mathematician** [autogluon/autogluon#2570]
### Discussed in https://github.com/autogluon/autogluon/discussions/2527

<div type='discussions-op-text'>

<sup>Originally posted by **pj-mathematician** December  6, 2022</sup>
I am using MultiModal predictor to classify images. I want to use [wandb](https://wandb.ai/) with it, so that I can use its features along with autogluon. Can you please guide me if this is possible without customizing the source code?

Since multimodal image prediction primarily uses PyTorch and PyTorch lightning, the example codes are as follows:
PyTorch:
```python
import wandb
# 1. Start a new run
wandb.init(project="gpt-3")
# 2. Save model inputs and hyperparameters
config = wandb.config
config.learning_rate = 0.01
# 3. Log gradients and model parameters
wandb.watch(model)
for batch_idx, (data, target) in enumerate(train_loader):
    if batch_idx % args.log_interval == 0:
    # 4. Log metrics to visualize performance
    wandb.log({"loss": loss})
```

PyTorch Lightning:
```python
from pytorch_lightning.loggers import WandbLogger
from pytorch_lightning import Trainer


wandb_logger = WandbLogger()
trainer = Trainer(logger=wandb_logger)
```

If this isnt currently possible then can you guide me a bit of the technicalities of the predictors and the frameworks they use so that I can fork and edit it accordingly 🙂 

Thanks
</div>

**Comment by robbiemccorkell** [comment]
I've posted a message in another issue describing how to use wandb's native tensorboard support: https://github.com/autogluon/autogluon/issues/420#issuecomment-2088320893

**Comment by shchur** [comment]
Closing this issue in favor of #420
