### ISSUE TITLE
[BUG] TimeSeriesPredictor accepts invalid fit and __init__ kwargs arguments.

### ISSUE THREAD

**Issue by rjattrill** [autogluon/autogluon#2600]
EDITED by @Innixma:

> Note: The real issue here is that TimeSeriesPredictor is not raising an exception upon being passed an invalid kwarg. TimeSeriesPredictor should adopt TabularPredictor's invalid kwarg handling logic to properly error in this scenario. Code in TabularPredictor for this logic should be moved to a generic location and re-used.

========= Original Message =========

When using `excluded_model_types` argument in the `fit` method of `TimeSeriesPredictor` the excluded model is still used.   Note that `presets` argument has also been used.

Using the sample code from the tutorial and adding 'excluded_model_types':

```
predictor = TimeSeriesPredictor(
    path="autogluon-m4-hourly",  
    target="Value",  
    prediction_length=48,  
    eval_metric="MAPE", 
).fit(
    train_data=ts_dataframe,
    presets="fast_training",  
    time_limit=30,  
    excluded_model_types=["ETS"]
)

```
When executing we see the following:
`Models that will be trained: ['Naive', 'SeasonalNaive', 'ETS', 'Theta', 'ARIMA', 'AutoGluonTabular', 'DeepAR']`

Full code: https://gist.github.com/rjattrill/74d2aee51f02ab98dc7a8aa461699f32
Input file: https://gist.github.com/rjattrill/ff6fb7f06c771919759c33dcb095214e

Note: The reason for trying to exclude this is that the ETS model doesn't seem to observe the time_limit for training - which might be a separate issue.

**Installed Versions**
>>> from autogluon.core.utils import show_versions
>>> show_versions()
NOTE: Redirects are currently not supported in Windows or MacOs.

```
INSTALLED VERSIONS
------------------
date                   : 2022-12-23
time                   : 15:25:59.818857
python                 : 3.9.15.final.0
OS                     : Windows
OS-release             : 10
Version                : 10.0.19044
machine                : AMD64
processor              : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
num_cores              : 8
cpu_ram_mb             : 16103
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : None

accelerate             : 0.13.2
albumentations         : 1.1.0
autogluon.common       : 0.6.1
autogluon.core         : 0.6.1
autogluon.features     : 0.6.1
autogluon.multimodal   : 0.6.1
autogluon.tabular      : 0.6.1
autogluon.text         : 0.6.1
autogluon.timeseries   : 0.6.1
autogluon.vision       : 0.6.1
boto3                  : 1.26.36
catboost               : 1.1.1
dask                   : 2021.11.2
defusedxml             : 0.7.1
distributed            : 2021.11.2
evaluate               : 0.3.0
fairscale              : 0.4.6
fastai                 : 2.7.10
gluoncv                : 0.11.0
gluonts                : 0.11.6
hyperopt               : 0.2.7
joblib                 : 1.2.0
jsonschema             : 4.8.0
lightgbm               : 3.3.3
matplotlib             : 3.6.2
networkx               : 2.8.8
nlpaug                 : 1.1.10
nltk                   : 3.8
nptyping               : 1.4.4
numpy                  : 1.22.4
omegaconf              : 2.1.2
openmim                : None
pandas                 : 1.5.2
PIL                    : 9.3.0
psutil                 : 5.8.0
pytorch-metric-learning: None
pytorch_lightning      : 1.7.7
ray                    : 2.0.1
requests               : 2.28.1
scipy                  : 1.8.1
sentencepiece          : 0.1.97
seqeval                : None
setuptools             : 65.6.3
skimage                : 0.19.3
sklearn                : 1.1.3
smart_open             : 5.2.1
statsmodels            : 0.13.5
text-unidecode         : None
timm                   : 0.6.12
torch                  : 1.12.0+cpu
torchmetrics           : 0.8.2
torchtext              : 0.13.0
torchvision            : 0.13.0+cpu
tqdm                   : 4.64.1
transformers           : 4.23.1
xgboost                : 1.7.2
```

**Comment by rjattrill** [comment]
There was a separate issue raised on this previously but the reporter had a syntax error.  https://github.com/autogluon/autogluon/issues/1013

**Comment by shchur** [comment]
Currently `excluded_model_types` is not a part of the `TimeSeriesPredictor.fit` [API](https://auto.gluon.ai/stable/api/autogluon.predictor.html#autogluon.timeseries.TimeSeriesPredictor.fit). This is something we consider adding in a future version. We're also looking into ways of ensuring that `ETS` and other models based on [statsmodels](https://www.statsmodels.org/stable/tsa) respect the time limit but that is still work in progress, unfortunately.

Currently, as a workaround, you can manually specify what models should be trained using the `hyperparameters` argument to fit, as in follows:
```python
predictor.fit(
    train_data=ts_dataframe,
    hyperparameters={
        "Naive": {},
        "SeasonalNaive": {},
        "Theta": {},
        "ARIMA": {},
        "AutoGluonTabular": {},
        "DeepAR": {},
    }
)
```

As a general comment, 30 seconds is a very restrictive limit for the M4 hourly dataset as it has >300K rows, so only a few baseline models can be trained within this time limit.

**Comment by Innixma** [comment]
@shchur The real issue here is that TimeSeriesPredictor is not raising an exception upon being passed an invalid kwarg. TimeSeriesPredictor should adopt TabularPredictor's invalid kwarg handling logic to properly error in this scenario. Code in TabularPredictor for this logic should be moved to a generic location and re-used.

I've renamed the issue to make this clearer.

**Comment by shchur** [comment]
This was a very fruitful issue that led to us fixing multiple problems in the library 😄. Thanks!
