### ISSUE TITLE
[BUG] - AttributeError: 'NoneType' object has no attribute '_user_params_aux'

### ISSUE THREAD

**Issue by pford221** [autogluon/autogluon#2603]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
The bug I'm encountering appears to be the same one in the documentation [here](https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-indepth.html). It appears to occur when `num_bag_folds > 0`.

**Expected behavior**
Training to complete without errors

**To Reproduce**
See bug in documentation linked above.

**Installed Versions**
date              : 2022-12-26
time              : 15:47:37.703839
python            : 3.9.13.final.0
OS                : Darwin
OS-release        : 21.6.0
Version           : Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
machine           : x86_64
processor         : i386
num_cores         : 12
cpu_ram_mb        : 16384
cuda version      : None
num_gpus          : 0
gpu_ram_mb        : []
avail_disk_size_mb: 384474

autogluon.common  : 0.6.1
autogluon.core    : 0.6.1
autogluon.features: 0.6.1
autogluon.tabular : 0.6.1
boto3             : 1.26.37
catboost          : 1.1.1
dask              : 2021.11.2
distributed       : 2021.11.2
fastai            : None
hyperopt          : None
lightgbm          : 3.3.3
matplotlib        : 3.6.2
networkx          : 2.8.8
numpy             : 1.23.4
pandas            : 1.5.1
psutil            : 5.9.3
ray               : None
requests          : 2.28.1
scipy             : 1.9.2
setuptools        : 65.5.0
sklearn           : 1.1.2
torch             : None
tqdm              : 4.64.1
xgboost           : 1.7.2

**Comment by shchur** [comment]
This is probably related to #2581

**Comment by yinweisu** [comment]
Yap. Same issue as https://github.com/autogluon/autogluon/issues/2581.

**Comment by SebastienZh** [comment]
I have encountered the same issue while training on Linux Platform. Yet this Problem did not occur on the Windows version.

**Comment by Innixma** [comment]
Fixed in v0.6.2, refer to #2581
