### ISSUE TITLE
Timestamps in dataset change to incorrect format after training model. 

### ISSUE THREAD

**Issue by whoopydev** [autogluon/autogluon#2604]
Hey guys, 

I'm currently training a model with historical data for a single stock. I'm using the quickstart tutorial in the AutoGluon Docs. 

The model trains successfully, however the timestamps for my predictions change to much earlier timestamps. The first timestamp in my data is in the year 2005, however this function shows the first timestamp being 1900: 

```
predictions = predictor.predict(train_data)
predictions.head()
```

Also, the database is supposed to show timestamps in daily intervals, however the intervals turn to every second. 

I should mention that I have set `ignore_time_index=True` since the data has a lot of missing days, and I don't know whether this could have anything to do with the issue. Also, since the dataset didn't come with any ID column, I manually created one and set an ID. 

EDIT: Hey, I just read this in the documentation for when I use `ignore_time_index`: 
`In this case, the predictor will completely ignore the timestamps in train_data, and the predictions made by the model will have a dummy timestamp index with frequency equal to 1 second. Also, the seasonality will be disabled for models like as ETS and ARIMA.`

How to account for this in my prediction and ensure I get a correctly formatted output? 
Thanks!

Thanks!

**Comment by shchur** [comment]
Since the training data doesn't have regularly sampled timestamps, TimeSeriesPredictor doesn't have a way of knowing what timestamps to assign to the prediction (what if the next `prediction_length` timestamps also have some missing values because of weekends/holidays?).

You can try forward-filling the training data to make sure that it has a regular frequency:
```python
def forward_fill_missing(ts: TimeSeriesDataFrame, freq="D") -> TimeSeriesDataFrame:
    original_index = ts.index.get_level_values("timestamp")
    start = original_index[0]
    end = original_index[-1]
    filled_index = pd.date_range(start=start, end=end, freq=freq, name="timestamp")
    return ts.droplevel("item_id").reindex(filled_index, method="ffill")

df = df.groupby("item_id").apply(forward_fill_missing)
```

**Comment by whoopydev** [comment]
Thanks for the quick reply! 
If I do this, will I need to set `ignore_time_index=True`?

Also, I'm currently using your code, however I'm getting an error: 
`KeyError: 'item_id`. 

For reference, my current dataset (before applying the `forward_fill_missing` looks like this: 

<img width="332" alt="Screenshot 2022-12-27 at 18 53 16" src="https://user-images.githubusercontent.com/117911275/209673198-33b5d170-a8a6-4a32-a758-569e6bcdb38f.png">

**Comment by whoopydev** [comment]
I figured out how to this. I was using tf as a variable instead of changing it to what I had set. Thank you so much!
