### ISSUE TITLE
How to take into account other variables for time series forecasting?

### ISSUE THREAD

**Issue by whoopydev** [autogluon/autogluon#2610]
Hey guys, 

I am currently using autogluon to predict the closing price of stocks. I would like to know whether it's possible to also allow the model to take into account other data such as opening price, daily high, daily low, etc. 

I know that it's possible to add covariates into the model, however the document says you can only add covariates which are known into the future, and the covariates I'm talking about are only know until the present. 

Any help would be appreciated. 
Thanks!

**Comment by shchur** [comment]
Past-only covariates are currently not supported, but we are currently working on this feature and hope to ship it in the next major release.
