### ISSUE TITLE
How does weighted ensemble work between local and global models? 

### ISSUE THREAD

**Issue by whoopydev** [autogluon/autogluon#2669]
Hey guys, 

I'm currently training a model with 'best-quality' preset on data from thousands of stocks. I'm wondering how exactly does the weighted ensemble work? 

I understand that local models fit every time-series data to their own model and global models just combine everything and cross-learn, so after the model is ready and I pass in the historical data for just one stock in weighted ensemble, I'm wondering how exactly it would work?

Also, after training my model on data from multiple timeseries, will I be able to simply perform inference by passing the historical data for a certain stock? 

Thanks!

**Comment by shchur** [comment]
The predictor does not differentiate between local and global models. The only difference is that when a local model is asked to predict for a new time series that it hasn't seen before, it will be refit again and the predictions for this time series will be cached. This means, when you predict for a new time series, local models will take longer to predict than global models.

AutoGluon currently uses a simple weighted ensemble that returns a weighted sum of the predictions of individual models. The weighting is the same for all time series in the dataset.
