### ISSUE TITLE
Autogluon Predict-Error

### ISSUE THREAD

**Issue by oguzhanakk** [autogluon/autogluon#2681]
tv_attribution.py
--------------------
class autogluon:
    
    def read_data(path,brand,freq='30min',prediction_length=48):
        df = pd.read_csv(path,index_col=[0]).reset_index()
        df.columns = ['Date','Value']
        df['Date'] = pd.to_datetime(df['Date'])
        df = df.set_index('Date').resample(freq).sum()
        df['Brand'] = brand
        
        train_data = TimeSeriesDataFrame.from_data_frame(
        df.reset_index(),
        id_column='Brand',
        timestamp_column='Date'
        )
        
        test_data = train_data.copy() 
        
        train_data = train_data.slice_by_timestep(slice(None, -prediction_length))
        
        return train_data,test_data
    
    
    def build_model(train_data,test_data,target,path,prediction_length,eval_metric='MAPE'):
        predictor = TimeSeriesPredictor(
        path=path,
        target=target,
        prediction_length=prediction_length,
        eval_metric=eval_metric,
        )
        predictor.fit(
            train_data=train_data,
        )
        
        predictor.leaderboard(test_data,silent=True)
        
        return predictor
    
    def predict(predictor,test_data):
        
        predictions = predictor.predict(test_data)
        print(test_data.head())
        
        ytrue = test_data.loc['item_id']["Sessions"]
        ypred = predictions.loc['item_id']
        ypred.loc[ytrue.index[-1]] = [ytrue[-1]] * 10
        ypred = ypred.sort_index()
        
        
        ytrue_test = test_data.loc['item_id']["Sessions"]
        
        plt.plot(ytrue[-30:], label="Training Data")
        plt.plot(ypred["mean"], label="Mean Forecasts")
        plt.plot(ytrue_test, label="Actual")
        
        plt.fill_between(
        ypred.index, ypred["0.1"], ypred["0.9"], color="red", alpha=0.1
        )

        plt.title("Prediction Results")
        _ = plt.legend()
        
        plt.savefig('autogluon_prediction_results.png')
        
autgluon.py
------------------
from tv_attribution import sample,autogluon
import pandas as pd

train_data,test_data = autogluon.read_data('setur-new.csv','Brand')

predictor = autogluon.build_model(train_data,test_data,'Value','setur',48)

autogluon.predict(predictor,test_data)

I have 2 python files, one is tv_attribution.py and the other is autogluon.py
When I run the autogluon.py file, I get the following error. May I know your reason? can you help me ?

This is the sample first 15 data of my setur.csv file.
--------------------------------------------------------
<img width="233" alt="setur" src="https://user-images.githubusercontent.com/92020160/212073540-4045ed78-1013-4eba-830e-ed4b289cff85.png">

Error code : 
--------------
![Screenshot_1](https://user-images.githubusercontent.com/92020160/212082899-aa97c363-3b3a-4c77-bf23-16653830f08d.png)

**Comment by shchur** [comment]
Can you please 
- show the full stack trace
- tell us what version of AutoGluon you are using 
- add line `print(df.head())` before `    train_data = TimeSeriesDataFrame.from_data_frame(` inside the `autogluon` class and show the output?

**Comment by Innixma** [comment]
Resolving as stale. Please re-open once the requested information is provided so we can move forward with assisting.
