### ISSUE TITLE
[v0.7] Remove autogluon.vision

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#2694]
Remove autogluon.vision module in v0.7, as it is fully replaced by autogluon.multimodal.

Additionally:

- [x] Remove gluoncv dependency. It is only used in `autogluon.vision`. This should also remove `autocfg` dependency.
- [x] Update tutorials to indicate the change

**Comment by bryanyzhu** [comment]
PR 2790 and 2819 have been merged, the tasks in this issue are completed.

**Comment by Innixma** [comment]
Awesome! Marking as resolved.
