### ISSUE TITLE
[BUG]Segmentation fault: core dumped

### ISSUE THREAD

**Issue by yyLeaves** [autogluon/autogluon#2702]
- [ ] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
I wrote a script to test the inference time of an autogluon tabular model. When I ran it in Jupyter Notebook, the kernel crashed. I tried to ran it in terminal, it showed.

**Expected behavior**

**To Reproduce**
```python
from autogluon.tabular import TabularPredictor
import pandas as pd
import numpy as np
from time import time
from tqdm import tqdm
test_paths = ['../feature.xlsx',]
test = pd.concat([pd.read_excel(p,engine='openpyxl') for p in test_paths]).reset_index(drop=True)

ag_path = "../autogluon_checkpoint_230113_180942/"
predictor = TabularPredictor.load(ag_path)

predictor.refit_full()
predictor.persist_models()

d = dict()
for i in range(1):
    for j in tqdm(range(len(test))):
        t1 = time()
        res = predictor.predict(test.iloc[j:j+1])
        t2 = time()
        d[(i,j)] = t2-t1
```

**Screenshots**
When I ran the scripts, it simply showed
![image](https://user-images.githubusercontent.com/76979429/212654641-8aea75ec-55c8-48ce-ab37-83b1105bf32b.png)
When enabled faulthandler, the two error messages from different runs were like.
```python
import faulthandler
faulthandler.enable()
```
![image](https://user-images.githubusercontent.com/76979429/212654141-dba7be75-1161-446b-aa4b-f0c8f4e09c0c.png)
![image](https://user-images.githubusercontent.com/76979429/212655301-cf0a967f-9ac8-4a18-ab75-834d6db97941.png)

**Installed Versions**
Which version of AutoGluon are you are using?  
If you are using 0.4.0 and newer, please run the following code snippet:
<details>
```python
INSTALLED VERSIONS
------------------
date                   : 2023-01-16
time                   : 18:12:09.154239
python                 : 3.9.15.final.0
OS                     : Linux
OS-release             : 5.15.0-25-generic
Version                : #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022
machine                : x86_64
processor              : x86_64
num_cores              : 16
cpu_ram_mb             : 64246
cuda version           : 11.470.141.03
num_gpus               : 1
gpu_ram_mb             : [10998]
avail_disk_size_mb     : 2873601

accelerate             : 0.13.2
albumentations         : 1.1.0
autogluon.common       : 0.6.0
autogluon.core         : 0.6.0
autogluon.features     : 0.6.0
autogluon.multimodal   : 0.6.0
autogluon.tabular      : 0.6.0
autogluon.text         : 0.6.0
autogluon.timeseries   : 0.6.0
autogluon.vision       : 0.6.0
boto3                  : 1.26.11
catboost               : 1.1.1
dask                   : 2021.11.2
defusedxml             : 0.7.1
distributed            : 2021.11.2
evaluate               : 0.2.2
fairscale              : 0.4.6
fastai                 : 2.7.10
gluoncv                : 0.11.0
gluonts                : 0.11.1
hyperopt               : 0.2.7
joblib                 : 1.2.0
jsonschema             : 4.8.0
lightgbm               : 3.3.3
matplotlib             : 3.6.2
networkx               : 2.8.8
nlpaug                 : 1.1.10
nltk                   : 3.7
nptyping               : 1.4.4
numpy                  : 1.22.4
omegaconf              : 2.1.2
openmim                : None
pandas                 : 1.5.1
PIL                    : 9.0.1
psutil                 : 5.9.0
pycocotools            : None
pytorch-metric-learning: None
pytorch_lightning      : 1.7.7
ray                    : 2.0.1
requests               : 2.28.1
scipy                  : 1.8.1
sentencepiece          : 0.1.97
seqeval                : None
setuptools             : 65.5.0
skimage                : 0.19.3
sklearn                : 1.1.3
smart_open             : 5.2.1
statsmodels            : 0.13.5
text-unidecode         : None
timm                   : 0.6.11
torch                  : 1.12.1+cu102
torchmetrics           : 0.8.2
torchtext              : 0.13.1
torchvision            : 0.13.1+cu102
tqdm                   : 4.64.1
transformers           : 4.23.1
xgboost                : 1.7.1
```

</details>

**Additional context**

**Comment by Innixma** [comment]
First, please upgrade to AutoGluon v0.6.2, you are using v0.6.0.
Second, please try without using tqdm to minimize chances of that being the reason.
Third, consider trying a copy.deepcopy() of the 1 row of data prior to sending to the predict call, see if that changes the behavior.

Also consider adding a small sleep command and monitoring memory usage as it runs, it would be interesting to see if the memory usage keeps increasing which is causing the segfault.

**Comment by yyLeaves** [comment]
> First, please upgrade to AutoGluon v0.6.2, you are using v0.6.0. Second, please try without using tqdm to minimize chances of that being the reason. Third, consider trying a copy.deepcopy() of the 1 row of data prior to sending to the predict call, see if that changes the behavior.
> 
> Also consider adding a small sleep command and monitoring memory usage as it runs, it would be interesting to see if the memory usage keeps increasing which is causing the segfault.

Hi, thanks for your suggestions. I did some experiments according to some of your advices but it seemed that this error could have impacts on the workstation and even caused the workstation to shutdown, so I don't think I can further troubleshooting this issue any more. I have to apologize for that.

First, I didn't test the issue on v6.0.2, cause apparently it had a mismatch on the model version and ag version, and the model took some times to retrain. 

Secondly, I disabled tqdm but the same problem still exists.

Thirdly, I tried to copy each row of data without passing it to the predictor and it seemed to work out fine. But when I passed that copy to the predictor, the same issue exists.

I have added sleep commands in my previous experiments (before I raised this issue). Surprisingly, when I added sleep time to 0.1s, the error didn't pop out. But when the sleep time is 0.01s and 0.05s, the error still existed. (I'm not sure if there's any coincidents cause I didn't repeat experiments). Besides, I don't think the memory usage keeps increasing during the test cause the memory usage consistently took 1.5% of 64G.
![image](https://user-images.githubusercontent.com/76979429/212793359-0a85467c-3e7d-4fc4-8ef2-4ab9b1fedfb2.png)

Here's some additional information. I suspected there might have something to do with the training presets. As I recall, last Friday I did the inference test 10 rounds on about 300 examples and didn't see this issue. 
```python
TabularPredictor(
            label=label, 
            path=save_path,
            problem_type='regression',
            eval_metric='mape'
            )\
        .fit(
            train, 
            presets=['best_quality'],
            excluded_model_types=['FASTAI'],
            )
```


Due to the long infer time for each record, I retrained the model using different presets, I saw the error for the first time (I ran the test on about 1k rows for 1 round).
```python
TabularPredictor(
            label=label, 
            path=save_path,
            problem_type='regression',
            eval_metric='mape'
            )\
        .fit(
            train, 
            presets=['good_quality_faster_inference_only_refit'],
            excluded_model_types=['FASTAI'],
            )
```

**Comment by Innixma** [comment]
Thanks for this! Diving into the logs, it appears that the issue is coming from the copy operation of pandas. If anything is going on, it is a bug in pandas when a copy operation on a DataFrame is occurring extremely fast and frequently. Interestingly, in v0.6.2 we did an optimization where we copy the DataFrame less often, so v0.6.2 might fix your issue. But beyond that, the bug lies in pandas, specifically the line that is triggering the seg-fault is [here](https://github.com/autogluon/autogluon/blob/0.6.0/features/src/autogluon/features/generators/abstract.py#L326), which is simply a call to subset columns of a pandas DataFrame.

I am going to mark as resolved for now unless it is shown that this bug continues occurring in v0.6.2 and that there is a way to fix beyond asking pandas developers to patch.

**Comment by yyLeaves** [comment]
> Thanks for this! Diving into the logs, it appears that the issue is coming from the copy operation of pandas. If anything is going on, it is a bug in pandas when a copy operation on a DataFrame is occurring extremely fast and frequently. Interestingly, in v0.6.2 we did an optimization where we copy the DataFrame less often, so v0.6.2 might fix your issue. But beyond that, the bug lies in pandas, specifically the line that is triggering the seg-fault is [here](https://github.com/autogluon/autogluon/blob/0.6.0/features/src/autogluon/features/generators/abstract.py#L326), which is simply a call to subset columns of a pandas DataFrame.
> 
> I am going to mark as resolved for now unless it is shown that this bug continues occurring in v0.6.2 and that there is a way to fix beyond asking pandas developers to patch.

Thank you for the solutions!
