### ISSUE TITLE
item_id in dataset

### ISSUE THREAD

**Issue by nebiyebulan** [autogluon/autogluon#2711]
I don't have an item_id column in my own dataset and all sample datasets have this column. How can I implement a solution for this column.
<img width="188" alt="samplepng" src="https://user-images.githubusercontent.com/62153842/212853676-360d26d3-f1a6-49f3-82f3-44fb7eb96279.png">

**Comment by shchur** [comment]
You can create a new column with all ones if your dataset only contains a single time series.

**Comment by nebiyebulan** [comment]
so can the item_id column all have the same name? In my data, the timestamp changes by 2 minutes.

**Comment by shchur** [comment]
Each item_id corresponds to a single time series. If your dataset only contains a single time series, the item_id should be the same for each row. If your dataset contains multiple time series, you need multiple item_ids.
