### ISSUE TITLE
[v0.7] Update README.md tutorial links for text, vision, and object detection

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#2751]
Update tutorials links in README to ensure they point to the autogluon.multimodal tutorials.

Also update documentation on install page to remove mention of autogluon.text.

**Comment by bryanyzhu** [comment]
README and tutorials have been updated in PR #2790 . Please let me know if there is any outstanding issue, thank you.

**Comment by Innixma** [comment]
LGTM, thanks @bryanyzhu!
