### ISSUE TITLE
[Multimodal] Add AutoGluon version check during load

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#2807]
Multimodal should adopt the version compatibility check logic in Tabular to prevent users from unknowingly loading a model artifact from an incompatible version of AutoGluon. This will prevent many nasty issues and hard to understand bug reports.

We should move the logic to a generic place and apply it in an identical manner.

**Comment by sxjscience** [comment]
For the multimodal module, we have backward compatibility tests which aim at ensuring the newer version of AutoGluon Multimodal is able to load the model trained by previous version of AutoGluon Multimodal: https://github.com/autogluon/autogluon/blob/master/multimodal/tests/unittests/others_2/test_backward_compatibility.py

We can expand the test to cover more scenarios.

**Comment by Innixma** [comment]
> For the multimodal module, we have backward compatibility tests which aim at ensuring the newer version of AutoGluon Multimodal is able to load the model trained by previous version of AutoGluon Multimodal: https://github.com/autogluon/autogluon/blob/master/multimodal/tests/unittests/others_2/test_backward_compatibility.py
> 
> We can expand the test to cover more scenarios.

We should probably still store some metadata like is done in tabular regarding versions, at minimum to help us debug user issues.

For example, Tabular saves `metadata.json` when saving the predictor:

```
{
  "system": "Darwin",
  "version": "0.6.2b20230103",
  "lite": false,
  "py_version": "3.8",
  "py_version_micro": "3.8.10",
  "packages": {
    "autogluon": "0.6.2b20230103",
    "autogluon.eda": "0.6.2b20230103",
    "autogluon.common": "0.6.2b20230103",
    "autogluon.core": "0.6.2b20230103",
    "autogluon.features": "0.6.2b20230103",
    "autogluon.tabular": "0.6.2b20230103",
    "autogluon.text": "0.6.2b20230103",
    "autogluon.vision": "0.6.2b20230103",
    "autogluon.multimodal": "0.6.2b20230103",
    "autogluon.timeseries": "0.6.2b20230103",
    "regex": "2022.10.31",
    "tifffile": "2022.10.10",
    "fsspec": "2022.10.0",
    "certifi": "2022.9.24",
    "pytz": "2022.6",
    "dask": "2021.11.2",
    "distributed": "2021.11.2",
    "tbb": "2021.7.0",
    "daal4py": "2021.6.3",
    "scikit-learn-intelex": "2021.6.3",

    ...

    "click": "8.0.4",
    "ipywidgets": "8.0.2",
    "jupyter-client": "7.4.4",
    "nbconvert": "7.2.5",
    "pytest": "7.2.0",
    "autogluon-contrib-nlp": "0.0.1b20220208"
  }
}
```

BTW, not saying you have to implement this, but rather that we should re-use what I've done in Tabular regarding this. A minimally intrusive way is for the verison check to be False by default, and then we can tell users who are having weird bugs to set it to True and try to load, and then it might show us the info necessary to understand the problem, such as a torch version difference, python version difference, or OS difference

**Comment by Innixma** [comment]
I'm open to add this to multimodal since I wrote the logic originally in Tabular.

**Comment by sxjscience** [comment]
Currently w store the version of the autogluon multimodal in `assets.json` : https://github.com/autogluon/autogluon/blob/dc21d0b248680cf926e1fdc58f00fb5fe79b4db9/multimodal/src/autogluon/multimodal/predictor.py#L2397-L2418

**Comment by Innixma** [comment]
Closing as stale. We can consider revisiting in future if bandwidth is allocated.
