### ISSUE TITLE
[BUG]RuntimeError on kaggle: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"

### ISSUE THREAD

**Issue by ytzfhqs** [autogluon/autogluon#2812]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
I'm using the TabularPredictor() function to train a classification model on the kaggle platform and I get a “too_many_pings” warning：

```python
E0202 00:42:26.112165293     343 chttp2_transport.cc:1167]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
```

**To Reproduce**
My training code is：
```python
predictor = TabularPredictor(label="quality",problem_type = 'multiclass',eval_metric='f1_macro',verbosity=0).fit(train_data,presets='best_quality',auto_stack=True,time_limit = 60*60*11,keep_only_best=True)
```

**Installed Versions**
I am using AutoGluon version V0.6.2

**Comment by Innixma** [comment]
@ytzfhqs Please provide full logs of the entire process, plus ideally a reproducible notebook example.

**Comment by KirderfEman** [comment]
I think this is a Ray library issue, have seen it before, here is an example.
https://github.com/ray-project/ray/issues/25012

**Comment by ytzfhqs** [comment]
@KirderfEmanThanks for your reply, I found out what the problem was. It seems to be caused by ray requesting too many CPU threads, when I limited num_cpus=4 the warning didn't appear anymore.
```python
predictor = TabularPredictor(label=label,problem_type = problem_type,eval_metric=eval_metric,verbosity=0).fit(train_data,presets='best_quality',auto_stack=True,time_limit = 60*60*int(hour_limt),keep_only_best=True,num_cpus = 4)
```
Thank you again for your reply！

**Comment by ytzfhqs** [comment]
@Innixma Thank you for your answer, I think my problem has been solved, thanks！
