### ISSUE TITLE
[v0.7] Ensure autogluon.eda dependency version ranges are updated

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#2846]
Current autogluon.eda setup.py file: https://github.com/autogluon/autogluon/blob/master/eda/setup.py#L21-L37

Filtering to relevant eda specific dependencies:

```python3
    'matplotlib>3.3',
    'missingno>=0.5.1,<0.6',
    'phik>=0.12.2,<0.13',
    'seaborn>=0.12.0,<0.13',
    'ipython>=7.34,<9.0',
    'ipywidgets>=8.0,<9.0',
    f'autogluon.core=={version}',
    f'autogluon.common=={version}',
    f'autogluon.features=={version}',
    f'autogluon.tabular=={version}',
```

The following should be checked before v0.7 release:

- [x] matplotlib is missing upper cap
- [x] matplotlib should use `>=3.4` for lower cap to align with rest of package
- [x] missingno is using latest
- [x] phik is using latest
- [x] seaborn is using latest
- [x] ipython is using latest
- [x] ipywidgets is using latest
- [x] ipywidgets>=8.0 is effectively a hard-pin, as 8.0.0 is latest release. Ensure this is low-risk or expand lower bound.
- [x] (Decided to not include optional dep) No usage of optional dependencies, consider adding `[all]` or `[full]` optional dependency that installs `autogluon.tabular[all]`.

**Comment by gradientsky** [comment]
There's no hard requirement to have `[all]` in dependencies. The package will just use `RF` if full `tabular`/`core` is not installed.

**Comment by Innixma** [comment]
Thanks for updating the ranges @gradientsky!
