### ISSUE TITLE
Bias mitigation and fairness boosting in multi class classification use case using Autogluon

### ISSUE THREAD

**Issue by pradeepdev-1995** [autogluon/autogluon#2869]
Is Autogluon support mitigating bias and improving fairness in multi class classification problems?
If so please provide an example of doing the same in a sample multi class classification dataset.

**Comment by Innixma** [comment]
You can refer to the [autogluon-fair repo](https://github.com/autogluon/autogluon-fair), planned to have its first PyPi release in mid-late Feb.

I'd suggest opening an issue in that repo.

**Comment by pradeepdev-1995** [comment]
@Innixma  Thanks. Will do it
