### ISSUE TITLE
Support of Pytorch 1.13 and CUDA 11.7

### ISSUE THREAD

**Issue by tonyhoo** [autogluon/autogluon#2885]
We need to update our Pytorch version to 1.13 with CUDA 11.7 so that TensorRT optimization could be applied.

**Comment by Innixma** [comment]
Don't we already use PyTorch 1.13? Our install range is `torch>=1.9,<1.14` for v0.7.

**Comment by Innixma** [comment]
If this is a DLC related comment, I think we should move the discussion to a different location than the GitHub issues, as this can cause confusion to users.

**Comment by tonyhoo** [comment]
For the latest pre-release on mac, I can see pytorch installed with version `1.12`
```
[master] pip freeze| grep "torch=="
torch==1.12.1
```

Also, the installation guide on our website indicates pytorch 1.12 with CUDA 11.3
<img width="1001" alt="Screenshot 2023-02-10 at 10 20 23 AM" src="https://user-images.githubusercontent.com/2148897/218167863-7b4ec4a5-0dc6-45d6-bc10-1f15e8aa6879.png">
