### ISSUE TITLE
Add lower bounds to Multimodal dependencies

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#2901]
The following dependencies lack lower bounds in multimodal setup.py:

- [x] pytesseract -> Suggestion: `>=0.3.9,<0.3.11`
- [x] jsonschema
- [x] text-unidecode
- [x] seqeval
- [x] evaluate
- [x] timm
- [ ] torchvision
- [x] tensorboard  -> Also lacks upper bound, please address
- [ ] torchmetrics -> Currently using 9 month old version, see if we can upgrade

We should add lower bounds to these dependencies to avoid installing with an incompatible old version of these packages.

**Comment by giswqs** [comment]
`"torchmetrics>=0.8.0,<0.9.0"` is equal to v0.8.2, which is 9-month old. Consider raising the upper bound. 
https://github.com/autogluon/autogluon/blob/master/multimodal/setup.py#L42
https://anaconda.org/conda-forge/torchmetrics/files
![image](https://user-images.githubusercontent.com/5016453/218236317-212883bd-9a50-4103-9576-af60e0a8cb09.png)

**Comment by sxjscience** [comment]
Torchmetrics changed the API so we won’t be able to upgrade in 0.7

**Comment by sxjscience** [comment]
@giswqs will you have time to take a look since it’s related to Conda?

**Comment by sxjscience** [comment]
For torchvision, we may need to revise the logic to install the appropriate torchvision version that is associated with torch.

**Comment by sxjscience** [comment]
For tensorboard, we are able to upperbound tensorboard to be like “tensorboard<3”.

**Comment by sxjscience** [comment]
For timm, evaluate, jsonschema, text-unidecode, etc, we should be able to lower-bound to the latest version and force people to upgrade.

However, it depends on whether it will cause conflicts in creating the docker container and Conda environment.

May be @giswqs is in the best position to verify.

**Comment by giswqs** [comment]
@sxjscience @Innixma Here are some suggestions based on versions available on conda-forge. You can click the link to each package to double check. 

-  [pytesseract](https://anaconda.org/conda-forge/pytesseract/files): `>=0.3.9,<0.3.11`
-  [jsonschema](https://anaconda.org/conda-forge/jsonschema/files): `>=4.14,<4.18`
-  [text-unidecode](https://anaconda.org/conda-forge/text-unidecode/files): `>1.2,<1.4`
-  [seqeval](https://anaconda.org/conda-forge/seqeval/files): `>=1.2.2,<1.3.0`
-  [evaluate](https://anaconda.org/conda-forge/evaluate/files): `>=0.2.2,<0.3.0`
-  [timm](https://anaconda.org/conda-forge/timm): `>0.6.10,<0.7.0` 
-  [torchvision](https://anaconda.org/conda-forge/torchvision): `>=0.14.0,<0.15.0`
-  [tensorboard](https://anaconda.org/conda-forge/tensorboard): `>=2.9.1,<2.12`
-  [torchmetrics](https://anaconda.org/conda-forge/torchmetrics/files): `>=0.8.0,<0.12.0`

**Comment by sxjscience** [comment]
Thanks!!!

**Comment by Innixma** [comment]
Marking as resolved by #2906, thanks!

Note that `torchvision` still lacks lower bound and `torchmetrics` is still using an old version. @sxjscience I'd recommend creating a tracking GitHub issue for these marked for v0.8 milestone if we intend to eventually address.

**Comment by giswqs** [comment]
@Innixma I chatted with @sxjscience earlier today. Here are his comments:

> 1. We cannot upgrade torchmetrics for now due to the API change of the package.
> 2. For torchvision, we may not do the lower-bound for now since we require more advanced logics
