### ISSUE TITLE
multimodal v0.7 conda package can't support osx because 'from ray import tune'

### ISSUE THREAD

**Issue by giswqs** [autogluon/autogluon#2903]
- [X] I have checked that this bug exists on the latest stable version of AutoGluon
- [X] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
The `ray` conda-forge package currently does not support osx. See https://github.com/conda-forge/ray-packages-feedstock/pull/80

`autogluon.multimodal` v0.7.0 introduces `from ray import tune` in [presets.py](https://github.com/autogluon/autogluon/blob/master/multimodal/src/autogluon/multimodal/presets.py#L3), which is causing issues for the `autogluon.multimodal` conda-forge osx build. See [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=656907&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445&l=1054). 

https://github.com/conda-forge/autogluon.multimodal-feedstock/pull/17

**Expected behavior**
We should try to make `import autogluon.multimodal` work across platforms.

**To Reproduce**
`import autogluon.multimodal` 

**Screenshots**
![image](https://user-images.githubusercontent.com/5016453/218237252-e7415ffa-1239-494d-947a-360e46cc98a5.png)

**Installed Versions**
Which version of AutoGluon are you are using?  
The latest commit

**Comment by Innixma** [comment]
@zhiqiangdon can we instead use the logic from `autogluon.core.space` to define the ranges, and only import ray when actually starting HPO?

**Comment by giswqs** [comment]
Currently, the `ray` dependency is included in `autogluon.core`. The conda-forge package will skip `ray` installation on osx. In v0.7, the `ray` dependency is kind of hardcoded in the source code because of `from ray import tune`, which will fail the conda-forge osx build becuase `ray` can no longer be skipped.

https://github.com/conda-forge/autogluon.core-feedstock/blob/main/recipe/meta.yaml#L48
![image](https://user-images.githubusercontent.com/5016453/218238314-ffa6f273-4923-4b84-9b68-5b9f6db1f0a5.png)

**Comment by zhiqiangdon** [comment]
Yes, we can do lazy import.

**Comment by Innixma** [comment]
> Yes, we can do lazy import.

Great! Please also confirm that running without HPO will work when ray isn't installed

**Comment by Innixma** [comment]
Fixed in #2916
