### ISSUE TITLE
[BUG]LinearModel

### ISSUE THREAD

**Issue by MedAIerHHL** [autogluon/autogluon#2971]
The following error will be reported after adding the linear model (shown in the following figure). How to solve it? after deletion, it will run normally.
![image](https://user-images.githubusercontent.com/102724737/221135728-43655960-e6d1-4e20-baf1-150f2658caa8.png)
![image](https://user-images.githubusercontent.com/102724737/221135772-56de5d68-b12b-49b0-a3bf-858d9bf1e104.png)

**Comment by Innixma** [comment]
This has likely been resolved in the latest AutoGluon 1.1+ releases. Please create a new issue if problem persists in the latest versions.
