### ISSUE TITLE
MultiModalPredictor ignores hyperparameters on __init__, but not on fit.

### ISSUE THREAD

**Issue by hugolytics** [autogluon/autogluon#2978]
- [ x ] I have checked that this bug exists on the latest stable version of AutoGluon

**Describe the bug**
When you initialize the MultiModalPredictor, it will ignore the hyperparameters when you pass them to the init of the class.

So MultiModalPredictor (problem_type = .., hyperparameters = hyperparameter)
and then you call fit, in the config.json, and in the console print it will state it is using the default setting (categoricalMLP and electra-base for text).
While my settings were, 
"categorical_transformer", "numerical_transformer", "fusion_transformer"
.

When I pass these hyperparameters on .fit() however, now the console print does reflect the hyperparameters I passed, and the config.json in the AutogluonModels folder as well.

**Comment by zhiqiangdon** [comment]
@hugolytics Thanks for raise the issue. Currently, `hyperparameters ` in init() is to support some problem types that can do zero-shot learning, such as `feature_extraction` and `image_similarity`. `hyperparameters ` in fit() is mainly for training. We will improve the logic to make `hyperparameters ` consistent between init() and fit().

**Comment by zhiqiangdon** [comment]
Resolved by #3279.
