### ISSUE TITLE
[BUG] EDA model quick-fit fails if old version of LightGBM already installed in environment

### ISSUE THREAD

**Issue by gidler** [autogluon/autogluon#2984]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
For the EDA functionality that uses AG-tabular to quick fit a model, if an old version of LightGBM is installed in the environment, EDA will try to use the installed version and may fail since the API has changed between `lightgbm-2` and `lightgbm-3`.

**Expected behavior**
EDA checks to see if LightGBM is installed (code [here](https://github.com/autogluon/autogluon/blob/master/eda/src/autogluon/eda/auto/simple.py#L640-L658)). It falls back to Random Forest if it is not installed. It should also somehow check that an appropriate version of LightGBM is installed, and fall back to RF if not.

**To Reproduce**
[EDA Auto Quick Fit](https://colab.research.google.com/github/autogluon/autogluon/blob/new/docs/tutorials/eda/eda-auto-quick-fit.ipynb) or [EDA Auto Covariate Shift](https://colab.research.google.com/github/autogluon/autogluon/blob/new/docs/tutorials/eda/eda-auto-covariate-shift.ipynb) have this problem if `!pip install autogluon.tabular[lightgbm]` is not included.

**Installed Versions**
0.7 dev and stable

</details>

**Additional context**
Temporary workaround is to add `!pip install autogluon.tabular[lightgbm]` to the tutorials to force a usable version of lightgbm to be installed. But it would be better if the tutorials code run with only `!pip install autogluon.eda`

**Comment by gidler** [comment]
I am pushing the `!pip install autogluon.tabular[lightgbm]` change to the `new` docs branch for now as a temporary fix.

**Comment by Innixma** [comment]
Marking as resolved as the docs branch updates have fixed it in notebooks. A long-term fix would be to detect the old version and raise an error / use RF instead, but that would be complex to maintain and probably not ideal.
