### ISSUE TITLE
adding v0.7.0 image to the autogluon-training ECR repository

### ISSUE THREAD

**Issue by ryansingman** [autogluon/autogluon#2994]
Hello!

Currently, in the `autogluon-training` ECR repository (AWS account ID 763...), the latest image built is for autogluon `v0.6.2`. My team is hoping to upgrade our autogluon version to `v0.7.0`, but there is no image pushed to that repository for that version (from what I can tell).

While I _believe_ we can work around this by pulling the `v0.6.2` image and then upgrading the autogluon version ourselves, it would be helpful to have that image pre-built :)

Thanks in advance!

**Comment by shchur** [comment]
Closing as the DLC image is already available.
