### ISSUE TITLE
[AutoMM] Avoid caching weights to disk during training

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#3005]
During testing, it appears for small datasets that the majority of training time is simply the process of saving the model to disk for checkpointing purposes and top_k greedy soup.

If the model is small enough in memory, why not instead keep the model checkpoint weights in memory instead of caching to disk to reduce the training time overhead of the operation? We generally only need to keep the top_k (3) for greedy soup, so as long as we can fit the model into memory (k+1) times without issue, it should be do-able.

I'd expect doing this kind of in-memory caching would speed up training by 3x+ on small datasets (<1000 rows).

**Comment by Innixma** [comment]
Happy to hear your thoughts @sxjscience @bryanyzhu @liangfu

**Comment by bryanyzhu** [comment]
I guess one reason of saving to disk is, if the training crashes in the middle, we can have at least some checkpoints to do inference or resume training. Besides, it is hard to know how large memory user has, which model do they pick, how many epochs and the evaluation interval, so the logic of fitting to memory will be quite tricky. 

But I agree to disable greedy soup, it is just too slow and not worth it. I think making "best" or "uniform soup" as the default model selection strategy is better.

**Comment by liangfu** [comment]
Since there isn't one strategy that fits all, I think maybe we could introduce a checkpointing strategy or a model selection strategy called "auto", and make it data-dependent.

**Comment by Innixma** [comment]
@bryanyzhu I would imagine it wouldn't be that hard once we start training to identify how many copies of the model we can safely keep in memory (although I'm not certain). I'm less interested in disabling greedy soup as I am making it more efficient in terms of checkpointing overhead.

Regarding "crashing in the middle", I think most users probably won't mind having to fully restart after a crash if they can train 3x faster. I'm not suggesting we always use the memory-based checkpointing. For example, on large datasets where checkpointing time cost is small compared to the actual training, then it would probably be ok to not do memory-based checkpointing. I think this is in-line with what @liangfu suggests.

**Comment by liangfu** [comment]
Checkpointing is mostly IO intensive, while the training process is mostly compute intensive. For training on large datasets, , if we can overlap the two (checkpointing during training), we can maximize the benefits of both worlds.

**Comment by zhiqiangdon** [comment]
Saving checkpoints to disk is a de-facto practice in training deep learning models. There are several reasons of doing this: 1) the model is large and memory can't hold multiple copies; 2) resume training if crashed in the middle; 3) Users may want evaluate specific checkpoints later. Optimizing for the small-data and small-model case is not high-priority for AutoMM.

**Comment by zhiqiangdon** [comment]
Closing this issue since the behavior is normal for training deep learning models.
