### ISSUE TITLE
AutoMM incorrectly infers problem_type

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#3017]
AutoMM problem_type infer logic doesn't work correctly when label column contains strings of integers.

AutoMM logic should work correctly in this scenario. Additionally, AutoMM should adopt the same problem_type infer logic as TabularPredictor.

```python3
import pandas as pd
from autogluon.multimodal.data.infer_types import infer_column_types
label = 'label'
data = pd.DataFrame(
    {
        label: [
            '0', '1', '2', 3, 4, 5, 5, 5, 0
        ]
    }
)
dtype = infer_column_types(data=data, label_columns=label)[label]
print(dtype)
```

Out (incorrect):

```
numerical
```

It should instead return:

```
categorical
```

This is handled correctly in Tabular:

```python3
from autogluon.core.utils.utils import infer_problem_type
problem_type = infer_problem_type(y=data[label])
print(problem_type)
```

Out (correct):

```
multiclass
```

**Comment by zhiqiangdon** [comment]
Resolved by #3227
