### ISSUE TITLE
[BUG] inference time

### ISSUE THREAD

**Issue by xxyliuyang** [autogluon/autogluon#3049]
It takes 4s for 100 pieces of data reasoning, and 10s for 10,000 pieces of data reasoning. Is this reasonable?

**Comment by xxyliuyang** [comment]
Can I load the trained basic models by yourself and reason by myself?

**Comment by xxyliuyang** [comment]
Can I load the trained basic models by yourself and reason by myself?

**Comment by shchur** [comment]
Yes, inference on multiple data points is faster due to batching.
