### ISSUE TITLE
[BUG] catboost crash in autogluon gpu run

### ISSUE THREAD

**Issue by devvidhani** [autogluon/autogluon#3063]
- [X ] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
See error message below.
Fitting model: CatBoost ...
        Training CatBoost with GPU, note that this may negatively impact model quality compared to CPU training.
        Warning: CatBoost on GPU is experimental. If you encounter issues, use CPU for training CatBoost instead.
Application terminated with error: ??+0 (0x7F4862637B94)
??+0 (0x7F4863A3973B)
??+0 (0x7F4863A387AD)
??+0 (0x7F4863A39968)
??+0 (0x7F48628BF2F3)
??+0 (0x7F48628BF15A)
??+0 (0x7F4AF9294B43)
??+0 (0x7F4AF9326A00)

(TCatBoostException) catboost/cuda/cuda_lib/cuda_base.h:261: CUDA error 9: invalid configuration argument
uncaught exception:
    address -> 0x3087f1b0410
    what() -> "catboost/cuda/cuda_lib/cuda_base.h:261: CUDA error 9: invalid configuration argument"
    type -> TCatBoostException

**Expected behavior**
Works fine on CPU like this.
Fitting model: CatBoost ...
        0.6433   = Validation score   (my_prob_scorer)
        12.39s   = Training   runtime
        0.02s    = Validation runtime

**To Reproduce**
A minimal script to reproduce the issue. Links to Colab notebooks or similar tools are encouraged.  
If the code is too long, feel free to put it in a public gist and link it in the issue: https://gist.github.com.  
In short, we are going to copy-paste your code to run it and we expect to get the same result as you.

Instructions to reproduce

```
git clone git@github.com:devvidhani/catchallbugs.git
cd autogluon_catboost_gpu_crash
```

Setup python environment using following 

```
pip install -r requirements.txt
python ./autogluon_custom_metric_using_serializable.py
```

Error shows up.

**Screenshots**
Put error code aboe

**Installed Versions**
Which version of AutoGluon are you are using?  
If you are using 0.4.0 and newer, please run the following code snippet:
<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

</details>

```
Here is the output

In [1]: from autogluon.core.utils import show_versions
   ...: show_versions()
   ...:

INSTALLED VERSIONS
------------------
date                   : 2023-03-17
time                   : 15:58:26.665802
python                 : 3.10.9.final.0
OS                     : Linux
OS-release             : 5.19.0-32-generic
Version                : #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2
machine                : x86_64
processor              : x86_64
num_cores              : 64
cpu_ram_mb             : 515617
cuda version           : 12.525.78.01
num_gpus               : 2
gpu_ram_mb             : [24211, 24136]
avail_disk_size_mb     : 3480702

accelerate             : 0.16.0
autogluon.common       : 0.7.0
autogluon.core         : 0.7.0
autogluon.features     : 0.7.0
autogluon.multimodal   : 0.7.0
autogluon.tabular      : 0.7.0
autogluon.timeseries   : 0.7.0
boto3                  : 1.26.80
catboost               : 1.1.1
defusedxml             : 0.7.1
evaluate               : 0.3.0
fairscale              : 0.4.13
fastai                 : 2.7.11
gluonts                : 0.12.3
hyperopt               : 0.2.7
jinja2                 : 3.1.2
joblib                 : 1.2.0
jsonschema             : 4.17.3
lightgbm               : 3.3.5
matplotlib             : 3.7.0
networkx               : 2.8.8
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.23.5
omegaconf              : 2.2.3
openmim                : None
pandas                 : 1.5.3
PIL                    : 9.4.0
psutil                 : 5.9.4
pytesseract            : 0.3.10
pytorch-metric-learning: None
pytorch_lightning      : 1.9.3
ray                    : 2.2.0
requests               : 2.28.2
scipy                  : 1.10.0
sentencepiece          : 0.1.97
seqeval                : None
setuptools             : 67.3.1
skimage                : 0.19.3
sklearn                : 1.2.1
statsforecast          : 1.4.0
statsmodels            : 0.13.5
tensorboard            : 2.12.0
text-unidecode         : None
timm                   : 0.6.12
torch                  : 1.12.1
torchmetrics           : 0.8.2
torchvision            : 0.13.1
tqdm                   : 4.65.0
transformers           : 4.26.1
ujson                  : 5.7.0
xgboost                : 1.7.4
```

**Additional context**

**Comment by shchur** [comment]
Closing this issue in favor of #4214 where we track progress on better GPU support.
