### ISSUE TITLE
provide hyperparameter to specify custom gpu to run autogluon on.

### ISSUE THREAD

**Issue by devvidhani** [autogluon/autogluon#3072]
multi gpu systems of (2 or more) RTX 4090 suffer from a bug that Nvidia is planning to fix in the driver. As a result, we are unable to fully utilize the system. Ability to select gpu for specific process will help mitigate the issue by giving manual control to programmers to select which gpu to run the process on and the programmers can manually parallelize their applications.

Here is the RTX 4090 driver issue that Nvidia is planning to fix as of now, but a remediation will be helpful nonetheless.

https://forums.developer.nvidia.com/t/standard-nvidia-cuda-tests-fail-with-dual-rtx-4090-linux-box/233202/32

**Comment by zhiqiangdon** [comment]
Hi, you can choose one GPU through `CUDA_VISIBLE_DEVICES=$id python myscript.py`.

**Comment by shchur** [comment]
Closing this issue assuming that the above comment addressed it.
