### ISSUE TITLE
[Feature request] log which model is loaded in predictor

### ISSUE THREAD

**Issue by austinmw** [autogluon/autogluon#3093]
Hi, I'm trying to follow https://auto.gluon.ai/dev/_modules/autogluon/timeseries/predictor.html#TimeSeriesPredictor.load
But would it be possible to print in endpoint logs which model was loaded, for example, if training ends with:

```
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'ETS', 'Theta', 'ARIMA', 'AutoETS', 'AutoGluonTabular', 'DeepAR']
Total runtime: 61.17 s
Best model: AutoGluonTabular
```

And indeed `AutoGluonTabular` is the one which is loaded in the deployment endpoint (please correct me if it's not as simple as just using best model), then can a log message be added to the effect of:

```
Using best model: AutoGluonTabular
```

**Comment by austinmw** [comment]
Oops, I actually meant to create this under autogluon-cloud

**Comment by Innixma** [comment]
Closing as it appears to have been opened in the wrong repo. Please create a new GitHub issue if the problem persists and is an issue with `autogluon` and not `autogluon-cloud`.
