### ISSUE TITLE
roc_auc metric dropped from 0.5516 to 0.29

### ISSUE THREAD

**Issue by liangfu** [autogluon/autogluon#3095]
- [ ] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**

roc_auc metric dropped from 0.5516 to 0.29 since PR #3079 (changes seem to be unrelated)

**Expected behavior**

https://auto.gluon.ai/dev/tutorials/multimodal/advanced_topics/tensorrt.html#compare-evaluation-metric

roc_auc metric is expected to be consistent, and it should be 0.5519

**To Reproduce**

PR #3078 [(roc_auc=0.5516)](http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-3078/6dcd597/tutorials/multimodal/advanced_topics/tensorrt.html#compare-evaluation-metric)
PR #3079 [(roc_auc= 0.29)](http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-3079/d71b34a/tutorials/multimodal/advanced_topics/tensorrt.html#compare-evaluation-metric) <--- roc_auc dropped starting from this PR, although the changes seem to be unrelated.
PR #3083 [(roc_auc= 0.29)](http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-3083/7507a13/tutorials/multimodal/advanced_topics/tensorrt.html#compare-evaluation-metric)

**Comment by Innixma** [comment]
Appears to be fixed in latest dev (roc_auc=0.5184): https://auto.gluon.ai/dev/tutorials/multimodal/advanced_topics/tensorrt.html#compare-evaluation-metric

Unsure what caused the fix.

One thing to note is this tutorial doesn't specify roc_auc as the eval metric. This should probably be updated so it is explicitly optimizing roc_auc (@zhiqiangdon)

**Comment by liangfu** [comment]
Thanks for pointing out the roc_auc(=0.5184) on the latest dev.

There is still a gap between 0.5184 and [0.5516](http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-3078/6dcd597/tutorials/multimodal/advanced_topics/tensorrt.html#compare-evaluation-metric).
