### ISSUE TITLE
short prediction range (between 0.2 and 0.3) with binary classification and auto_stack=True

### ISSUE THREAD

**Issue by fcoppey** [autogluon/autogluon#3105]
Help wanted! 
See post in the discussion below:
https://github.com/autogluon/autogluon/discussions/3104

There must something wrong... 

Thanks!

**Comment by Innixma** [comment]
Hi @fcoppey. Can you please provide a minimal reproducible example, such as a colab notebook? If you data is confidential, then consider finding a public dataset that allows you to reproduce the strange behavior, or anonymizing your data and providing it?

**Comment by fcoppey** [comment]
[autogluon-test.xlsx](https://github.com/autogluon/autogluon/files/11569306/autogluon-test.xlsx)
sorry I still struggle here on the same dataset, if someone is willing to give it a try to help me understand the reason...
I use groups and presets: best_quality + optimise for deployment

thanks a lot!
