### ISSUE TITLE
[BUG] Use CatBoost categorical features encoding instead of Autogluon encoding

### ISSUE THREAD

**Issue by javiermoralh** [autogluon/autogluon#3111]
The Autogluon documentation lists two types of categorical variable treatments: integer encoding or TextFeatureGenerators if the categories contain text. If these variables are encoded automatically, libraries such as Catboost or LightGBM cannot take advantage of their full potential. These models have their own way of dealing with such variables in an efficient way to improve predictive power.

**Comment by Innixma** [comment]
Thanks for creating this issue @javiermoralh! This is what we do internally, we keep track of which features were originally categorical, and then pass them as categorical into LightGBM and CatBoost.

**Comment by javiermoralh** [comment]
Thank you so much!
