### ISSUE TITLE
The problem I have met When I use autogluon to solve regression quertion

### ISSUE THREAD

**Issue by clive380** [autogluon/autogluon#3141]
It gives me a waring like tihs when I use TabularPredictor:
   **FutureWarning: Calling `predictor.predict_proba` when problem_type=regression will raise an AssertionError starting in AutoGluon v0.8. Please call `predictor.predict` instead.**
And then it won't run the rest code which is the process of evaluating model

**Comment by AnhQuoc533** [comment]
Upvote.

**Comment by shchur** [comment]
This should be fixed in the latest release (v1.1.1)
