### ISSUE TITLE
Mac Intel install instructions are broken

### ISSUE THREAD

**Issue by elarbee** [autogluon/autogluon#3169]
### Describe the issue linked to the documentation

On Intel Mac, Ventura
Using Python 3.10.8
https://auto.gluon.ai/stable/install.html
Select mac/pip/cpu

`pip install torch==1.13.1+cpu torchvision==0.14.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html`

This command fails with error

`ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cpu (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.13.1+cpu`

I'm not en expert on pip so I'm debugging myself, but I'm guessing the html link pip is checking doesn't properly list `1.13.1+cpu`.
`https://download.pytorch.org/whl/cpu/torch_stable.html`

### Suggest a potential alternative/fix

Probably the link `https://download.pytorch.org/whl/cpu/torch_stable.html` needs to be updated.

**Comment by elarbee** [comment]
Removing `+cpu` from install command seems to work.
`pip install torch==1.13.1 torchvision==0.14.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html`

Since the download link specifies `cpu` in it's URL path, maybe the `+cpu` is redundant?

I've completed install now, but have not thoroughly tested that the install performs correctly.

**Comment by fuomag9** [comment]
Broken on m1 as well

**Comment by shchur** [comment]
The latest install instructions seem to work fine on Mac https://auto.gluon.ai/stable/install.html, so closing this issue. Please feel free to re-open
