### ISSUE TITLE
[BUG] TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok' on clone_for_deployment()

### ISSUE THREAD

**Issue by v0juse** [autogluon/autogluon#3173]
"Hello, first time here :). 

I encountered an issue while using Autogluon 0.6.2 with Python 3.7.16. The error message was: 'TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'.' I found out that the 'dirs_exist_ok' argument was only added to the shutil library in Python 3.8 and higher, but it's being used in the predictor's copy method. To solve the problem, I removed the check and handled a FileExistError instead.

However, my project still has some dependencies restricted to Python 3.7. Since Autogluon 0.6.x should maintain compatibility with this version, would it be possible to address this issue with a patch?"
    

</details>

**Comment by shchur** [comment]
Closing this issue for now as it seems to be stale.
