### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by noviceswing** [autogluon/autogluon#3181]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

i follow the mamba install -c conda-forge autogluon.tabular autogluon.timeseries

---------------------------------------------------------------------------
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 4
      1 # To maximize the prediction performance of autogluon, we can try using the following code to tune hyperparameters:
      3 from autogluon.tabular import TabularDataset, TabularPredictor
----> 4 from autogluon.core.scheduler.resource import get_cpu_count, get_gpu_count
      5 from autogluon.core.scheduler.reporter import CLIReporter
      6 from autogluon.core import Real, Int

ModuleNotFoundError: No module named 'autogluon.core.scheduler.resource'
```
**Expected behavior**

**To Reproduce**

**Screenshots / Logs**

**Installed Versions**

<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

</details>

**Comment by noviceswing** [comment]
conda create -n ag python=3.9
conda activate ag
conda install -c conda-forge mamba
mamba install -c conda-forge autogluon.tabular autogluon.timeseries

**Comment by noviceswing** [comment]
i want to maximize the prediction performance of autogluon
from autogluon.core.scheduler.resource import get_cpu_count, get_gpu_count
from autogluon.core.scheduler.reporter import CLIReporter
from autogluon.core import Real, Int
then :
ModuleNotFoundError Traceback (most recent call last)
Cell In[1], line 4
1 # To maximize the prediction performance of autogluon, we can try using the following code to tune hyperparameters:
3 from autogluon.tabular import TabularDataset, TabularPredictor
----> 4 from autogluon.core.scheduler.resource import get_cpu_count, get_gpu_count
5 from autogluon.core.scheduler.reporter import CLIReporter
6 from autogluon.core import Real, Int

ModuleNotFoundError: No module named 'autogluon.core.scheduler.resource'

**Comment by noviceswing** [comment]
sorry, i know it

**Comment by yinweisu** [comment]
Looks like this issue has been figured out. Will close for now and feel free to reopen
