### ISSUE TITLE
[BUG] Some categories were encoded as NAN

### ISSUE THREAD

**Issue by CDchenlin** [autogluon/autogluon#3200]
I resently use TabularPredictor.transform_features(data=tarin_data) to transform my data for further up and down sampling. However I found some categories with very small sample size were encoded as NAN.

**Comment by shchur** [comment]
AutoGluon replaces rare categories with NaN, see https://auto.gluon.ai/stable/tutorials/tabular/tabular-feature-engineering.html for more details.
