### ISSUE TITLE
TabularNueralNetTorchModel not yet able to use more than 1 GPU

### ISSUE THREAD

**Issue by hanxuh-hub** [autogluon/autogluon#3224]
I am trying to train the tabular models on 2 GPUs but it seems NeuralNetTorch only supports 1 GPU. Here is the log message:

"
TabularNeuralNetTorchModel not yet able to use more than 1 GPU. 'num_gpus' is set to >1, but we will be using only 1 GPU. 
"

Is there any plan to support multiple GPUs in the future? Thanks in advance for your help.

**Comment by shchur** [comment]
Closing this issue in favor of #4214
