### ISSUE TITLE
label_count_threshold parameter

### ISSUE THREAD

**Issue by saranya-work** [autogluon/autogluon#3243]
Hello,

I am using Autogluon 0.7.0 . When I pass the label_count_parameter to change the value to 3 instead of default 10, to the Tabularpredictor, I get the following error. 
Could you please recommend a solution:

predictor = TabularPredictor(label=label_column, label_count_threshold=3).fit(train_data,num_bag_folds=5)

Error:
ValueError: Invalid kwargs passed: ['label_count_threshold']
Valid kwargs: ['learner_type', 'quantile_levels', 'learner_kwargs']

Thanks,
Saranya

**Comment by shchur** [comment]
This parameter has been deprecated. Please see https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.html for up-to-date documentation.
