### ISSUE TITLE
Support Pandas 2.0

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#3251]
Support Pandas 2.0

**Comment by Zethson** [comment]
That would be great. Pandas is a fundamental dependency and this blocks other projects that are depending on autogluon such as dowhy. I would like to kindly lobby to address this in 0.8.0

**Comment by shchur** [comment]
It seems that this change is inevitable and will happen before the v1.0 release of AutoGluon. Should we bump the dependency in [`_setup_utils.py`](https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py#L22C24-L22C24) to include pandas 2.0 to give us more time to catch the potential related bugs while we are working on the v1.0 release?

**Comment by shchur** [comment]
Pandas 2.1 also [requires](https://pandas.pydata.org/docs/getting_started/install.html#python-version-support) Python >= 3.9, so we will need to bump our Python dependency first.

**Comment by Innixma** [comment]
Pandas 2.0 is supported in upcoming v1.0 release
