### ISSUE TITLE
[BUG]If the structure with a large number of training samples has a memory exception in the data, it will fail. How to train large data sets, such as how to implement methods such as batch training?

### ISSUE THREAD

**Issue by ClearTorch** [autogluon/autogluon#3254]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

**Expected behavior**

**To Reproduce**

**Screenshots / Logs**

**Installed Versions**

<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

</details>

**Comment by shchur** [comment]
The recommended approach is to train on a subset of the data, and then pass data in smaller batches for prediction.
