### ISSUE TITLE
[BUG]Code execution interrupted unexpectedly when following the AutoGluon Tabular tutorial with tabpfn model enabled

### ISSUE THREAD

**Issue by ggzzz** [autogluon/autogluon#3326]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

I was following the AutoGluon Tabular tutorial at https://colab.research.google.com/github/autogluon/autogluon/blob/master/docs/tutorials/tabular/tabular-essentials.ipynb and encountered an interruption during the process of fitting with presets='experimental_extreme_quality'. 
**Expected behavior**

script executed normally

**To Reproduce**

Changed 
``` !pip install autogluon.tabular[all]``` 
 to
 ``` !pip install autogluon.tabular[all,tabpfn]``` 

Changed 
``` predictor = TabularPredictor(label=label, path=save_path).fit(train_data) ```
to 
``` predictor = TabularPredictor(label=label, path=save_path).fit(train_data, presets='experimental_extreme_quality')``` 

**Screenshots / Logs**

Fitting model: LightGBMXT_BAG_L1 ...
<frozen importlib._bootstrap>:914: ImportWarning: APICoreClientInfoImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _PyDriveImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _OpenCVImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _BokehImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _AltairImportHook.find_spec() not found; falling back to find_module()
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy
**Interrupted Here**

**Installed Versions**

autogluon==0.8.0

<details>

```python
INSTALLED VERSIONS
------------------
date                : 2023-06-18
time                : 16:31:21.002424
python              : 3.10.12.final.0
OS                  : Linux
OS-release          : 5.15.107+
Version             : #1 SMP Sat Apr 29 09:15:28 UTC 2023
machine             : x86_64
processor           : x86_64
num_cores           : 2
cpu_ram_mb          : 12982
cuda version        : None
num_gpus            : 0
gpu_ram_mb          : []
avail_disk_size_mb  : 79893

autogluon           : None
autogluon.common    : 0.8.0
autogluon.core      : 0.8.0
autogluon.features  : 0.8.0
autogluon.tabular   : 0.8.0
boto3               : 1.26.155
catboost            : 1.2
fastai              : 2.7.12
hyperopt            : 0.2.7
imodels             : None
lightgbm            : 3.3.5
matplotlib          : 3.7.1
networkx            : 3.1
numpy               : 1.22.4
onnxruntime-gpu     : None
pandas              : 1.5.3
psutil              : 5.9.5
ray                 : 2.3.1
requests            : 2.27.1
scikit-learn        : 1.2.2
scikit-learn-intelex: None
scipy               : 1.10.1
setuptools          : 67.7.2
skl2onnx            : None
tabpfn              : 0.1.9
torch               : 1.13.1
tqdm                : 4.65.0
vowpalwabbit        : None
xgboost             : 1.7.5
```

</details>

**Comment by shchur** [comment]
Related: #3326

**Comment by Innixma** [comment]
This is likely an environment issue and not a TabPFN issue. If this issue still persists in the latest AutoGluon release, please open a new issue.

**Comment by Innixma** [comment]
Actually, this might be an issue with TabPFN, as this issue is related: #3345. Closing this issue in favor of tracking in #3345.
