### ISSUE TITLE
[BUG] AutoGluon >= 0.7 is not compatible with mxnet 1.9.1

### ISSUE THREAD

**Issue by c3-ziqin** [autogluon/autogluon#3357]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

`autogluon.timeseries` supports several gluonts model implemented in mxnet. However, the latest stable `mxnet` (1.9.1) is not compatible with `numpy>=1.20`. And AG>=0.7 requires `numpy>=1.21`. 
Install AutoGluon before / after / with mxnet will results in either resolution failure or version conflict at import.

**Expected behavior**

Add clear indication in docs that this conflict exists. 
Also catch AssertionError here if import mxnet fails https://github.com/autogluon/autogluon/blob/174d67c72ee1adcc437efbe4392975e23085c542/timeseries/src/autogluon/timeseries/__init__.py#L12-L24

**To Reproduce**

Set up env
```bash
# Install either cpu or gpu version of autogluon
pip install -U pip
pip install -U setuptools wheel
pip install torch==1.13.1+cpu torchvision==0.14.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
pip install autogluon
# Install mxnet
pip install mxnet
```
Import package
```python
import autogluon.timeseries 
```
Above will raise this error:
```
/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/mxnet/numpy/utils.py:37: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  bool = onp.bool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/autogluon/timeseries/__init__.py", line 14, in <module>
    from mxnet import __version__ as mxnet_version
  File "/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/mxnet/__init__.py", line 33, in <module>
    from . import contrib
  File "/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/mxnet/contrib/__init__.py", line 30, in <module>
    from . import text
  File "/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/mxnet/contrib/text/__init__.py", line 23, in <module>
    from . import embedding
  File "/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/mxnet/contrib/text/embedding.py", line 36, in <module>
    from ... import numpy as _mx_np
  File "/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/mxnet/numpy/__init__.py", line 23, in <module>
    from .multiarray import *  # pylint: disable=wildcard-import
  File "/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/mxnet/numpy/multiarray.py", line 47, in <module>
    from .utils import _get_np_op
  File "/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/mxnet/numpy/utils.py", line 37, in <module>
    bool = onp.bool
  File "/home/c3/.conda/envs/agcpu/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doingthis will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
If I manually change numpy to <1.20, other version conflict will happen.

**Screenshots / Logs**

**Installed Versions**

<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

INSTALLED VERSIONS
------------------
date                   : 2023-06-27
time                   : 19:08:58.009565
python                 : 3.9.16.final.0
OS                     : Linux
OS-release             : 5.4.231-137.341.amzn2.x86_64
Version                : #1 SMP Tue Feb 14 21:50:55 UTC 2023
machine                : x86_64
processor              : x86_64
num_cores              : 8
cpu_ram_mb             : 31758
cuda version           : 11.470.161.03
num_gpus               : 1
gpu_ram_mb             : [22731]
avail_disk_size_mb     : 25382

accelerate             : 0.16.0
autogluon              : 0.8.0
autogluon.common       : 0.8.0
autogluon.core         : 0.8.0
autogluon.features     : 0.8.0
autogluon.multimodal   : 0.8.0
autogluon.tabular      : 0.8.0
autogluon.timeseries   : 0.8.0
boto3                  : 1.26.161
catboost               : 1.2
defusedxml             : 0.7.1
evaluate               : 0.3.0
fairscale              : 0.4.13
fastai                 : 2.7.12
gluonts                : 0.13.2
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.2
joblib                 : 1.2.0
jsonschema             : 4.17.3
lightgbm               : 3.3.5
matplotlib             : 3.7.1
mlforecast             : 0.7.3
networkx               : 3.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.4
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.7
pandas                 : 1.5.3
Pillow                 : 9.5.0
psutil                 : 5.9.5
PyMuPDF                : 1.21.1
pytesseract            : 0.3.10
pytorch-lightning      : 1.9.5
pytorch-metric-learning: 1.7.3
ray                    : 2.3.1
requests               : 2.31.0
scikit-image           : 0.19.3
scikit-learn           : 1.2.2
scikit-learn-intelex   : None
scipy                  : 1.11.0
sentencepiece          : 0.1.99
seqeval                : 1.2.2
setuptools             : 68.0.0
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.0
tabpfn                 : None
tensorboard            : 2.13.0
text-unidecode         : 1.3
timm                   : 0.9.2
torch                  : 1.13.1+cpu
torchmetrics           : 0.11.4
torchvision            : 0.14.1+cpu
tqdm                   : 4.65.0
transformers           : 4.26.1
ujson                  : 5.8.0
vowpalwabbit           : None
xgboost                : 1.7.6

</details>

**Comment by shchur** [comment]
Closing this issue as it's resolved by #3396.
