### ISSUE TITLE
[BUG]'NoneType' object has no attribute 'fit'

### ISSUE THREAD

**Issue by jiajiadedaima** [autogluon/autogluon#3393]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

**Expected behavior**

**To Reproduce**

**Screenshots / Logs**

**Installed Versions**

<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

</details>

**Comment by zhiqiangdon** [comment]
No information about the bug. Please provide more details if still have the issue.
