### ISSUE TITLE
[BUG] [EDA] IndexError: positional indexers are out-of-bounds

### ISSUE THREAD

**Issue by YifeiYang210** [autogluon/autogluon#3401]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [?] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

I'm not sure if the stable version changes and I installed v0.8 of autogluon in June, 2023.

**Describe the bug**

Problem: Function `autogluon.eda.auto.detect_anomalies()` reports the train_data and test_data anomalies for 2-sigma outlier scores figures, but ends when it reports the dataframe by `IndexError: positional indexers are out-of-bounds`.

Solve: In the file of `eda.auto.simple` and `eda.analysis.anomaly`, changing `iloc` to `loc` can fix it.

In Pandas, both iloc and loc are used to access data in a DataFrame. 

iloc is used for selecting data using integer-based indexing. It accesses rows and columns of the DataFrame by their integer positions. It takes integers or integer slices as input and returns the corresponding data. For example, df.iloc[0] selects the first row of the DataFrame, and df.iloc[:, 0] selects the first column of the DataFrame. 

loc is used for selecting data using label-based indexing. It accesses rows and columns of the DataFrame by their labels. It takes labels or label slices as input and returns the corresponding data. For example, df.loc[0] selects the row with the label 0, and df.loc[:, 'column_name'] selects the column with the label 'column_name'.

The difference between iloc and loc is the way they handle the indexing. iloc uses integer-based indexing, while loc uses label-based indexing.

When we split the dataframe which has 10 rows to train_df and test_df randomly, the train_df index may range in [0,1,2,4,5,7,9,10] and the test_df index may range in [3,6,8]. And we call `detect_anomalies()` function to get the anomaly_idx,  the result of anomaly_idx may be [4, 10] in train_df. Using train_df.iloc[anomaly_idx] equals the 4th and 10th rows of train_df then cause IndexError. And train_df.loc[anomaly_idx] equals the index of "4" and index of "10", which can fix it.

Source file:
```python
// simple.py line:1667
_state.anomaly_detection.anomalies[ds] = df.iloc[anomaly_idx].join(anomaly_scores)

// anomaly.py line:346
rows=args[dataset].iloc[dataset_row_ids],
```

Fixed file:
```python
// simple.py line:1667
_state.anomaly_detection.anomalies[ds] = df.loc[anomaly_idx].join(anomaly_scores)

// anomaly.py line:346
rows=args[dataset].loc[dataset_row_ids],
```

**Expected behavior**

It should output not only the **figure** but also the **dataframes of the detected anomalies** like the official document.
URL: https://auto.gluon.ai/stable/tutorials/eda/eda-auto-anomaly-detection.html#run-anomaly-analysis-on-cleaned-data

**To Reproduce**

A short script provided by Gist:
https://gist.github.com/YifeiYang210/c42406f72dba400b2c831d26bd771491

**Screenshots / Logs**

Figure1:
![image](https://github.com/autogluon/autogluon/assets/35833143/6c57fc3c-8aa6-4df4-93af-f34523dc17a9)

Figure2:
![image](https://github.com/autogluon/autogluon/assets/35833143/9ae2fba8-0704-4bc2-ae77-1c08a3ba10af)

Figure3:
![image](https://github.com/autogluon/autogluon/assets/35833143/6e4caba1-7fda-4a26-bfae-22f7b844be69)

Figure4:
![image](https://github.com/autogluon/autogluon/assets/35833143/30902979-d753-4b25-ba3b-9da1b8bb540f)

**Installed Versions**

<details>

```python
INSTALLED VERSIONS
------------------
date                   : 2023-07-09
time                   : 02:10:39.385611
python                 : 3.8.16.final.0
OS                     : Windows
OS-release             : 10
Version                : 10.0.22621
machine                : AMD64
processor              : Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
num_cores              : 32
cpu_ram_mb             : 65154
cuda version           : None
num_gpus               : 1
gpu_ram_mb             : [15556]
avail_disk_size_mb     : None

accelerate             : 0.16.0
autogluon              : 0.8.0
autogluon.common       : 0.8.0
autogluon.core         : 0.8.0
autogluon.eda          : 0.8.0
autogluon.features     : 0.8.0
autogluon.multimodal   : 0.8.0
autogluon.tabular      : 0.8.0
autogluon.timeseries   : 0.8.0
boto3                  : 1.26.133
catboost               : 1.2
defusedxml             : 0.7.1
evaluate               : 0.3.0
fairscale              : 0.4.13
fastai                 : 2.7.12
gluonts                : 0.13.2
hyperopt               : 0.2.7
imodels                : 1.3.17
ipython                : 8.12.0
ipywidgets             : 8.0.6
jinja2                 : 3.1.2
joblib                 : 1.2.0
jsonschema             : 4.17.3
lightgbm               : 3.3.3
matplotlib             : 3.6.3
missingno              : 0.5.2
mlforecast             : 0.7.3
networkx               : 3.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.3
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.7
pandas                 : 1.5.3
phik                   : 0.12.3
Pillow                 : 9.5.0
psutil                 : 5.9.5
PyMuPDF                : 1.21.1
pyod                   : 1.0.9
pytesseract            : 0.3.10
pytorch-lightning      : 1.9.5
pytorch-metric-learning: 1.7.3
ray                    : 2.3.1
requests               : 2.30.0
scikit-image           : 0.19.3
scikit-learn           : 1.2.2
scikit-learn-intelex   : None
scipy                  : 1.10.1
seaborn                : 0.12.2
sentencepiece          : 0.1.99
seqeval                : 1.2.2
setuptools             : 67.7.2
shap                   : 0.41.0
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.0
suod                   : 0.0.8
tabpfn                 : None
tensorboard            : 2.13.0
text-unidecode         : 1.3
timm                   : 0.9.2
torch                  : 1.13.1+cu116
torchmetrics           : 0.11.4
torchvision            : 0.14.1+cu116
tqdm                   : 4.65.0
transformers           : 4.26.1
ujson                  : 5.8.0
vowpalwabbit           : 9.0.0
xgboost                : 1.6.2
yellowbrick            : 1.5

Process finished with exit code 0
```

</details>

**Comment by AmirZidi** [comment]
I'm facing exactly the same issue, any update ?

**Comment by gradientsky** [comment]
Thanks for your contribution and all the necessary background. The change is merged.
