### ISSUE TITLE
Error in Time Series Forecasting with AutoGluon: Data being irregularly sampled

### ISSUE THREAD

**Issue by toshimasoni** [autogluon/autogluon#3481]
### Discussed in https://github.com/autogluon/autogluon/discussions/3478

<div type='discussions-op-text'>

<sup>Originally posted by **toshimasoni** August 25, 2023</sup>
I am encountering an issue while using AutoGluon for time series forecasting. Here's the problem I'm facing:

Problem:
I have a dataset with employee IDs, quarterly timestamps (e.g., 1-2015, 2-2015, ...), and sales data spanning from 2015 to 2021 (quarterly data). I am attempting to use AutoGluon for time series forecasting with this data. This is my training data.

Error Message:
When trying to use AutoGluon, I am encountering the following error:

ValueError: Frequency not provided and cannot be inferred. This is often due to the time index of the data being irregularly sampled. Please ensure that the dataset used has a uniform time index, or create the TimeseriesPredictor setting "ignore_time_index-True".
Even after setting ignore_time_index=True, I am still encountering the same error.

Request for Assistance:
I need help in resolving this issue. I have already tried the suggested solution of setting ignore_time_index=True, but the error persists. I am unsure how to proceed further to resolve this frequency inference issue.

Dataset Structure:

Employee IDs
Quarterly Timestamps (1-2015, 2-2015, ...)
Sales Data
Any guidance or suggestions on how to overcome this frequency inference problem would be greatly appreciated.</div>

**Comment by shchur** [comment]
Hello, thank you for the question.

Can you please try converting your data (assuming it's already a `TimeSeriesDataFrame`) to a regular frequency as follows:
```python
train_data = ... # load your data as a TimeSeriesDataFrame
train_data = train_data.to_regular_index(freq="Q")
```
If that doesn't work, you can try this:
```python
train_data = TimeSeriesDataFrame(
    train_data.groupby(level="item_id", sort=False).resample("Q", level="timestamp").mean()
)
```

Finally, it's possible that your data contains some time series that have only 1 or 2 observations, which makes it impossible to determine the frequency. You can remove these extremely short time series with
```python
ts_lengths = train_data.num_timesteps_per_item()
items_to_keep = ts_lengths.index[ts_lengths >= 3]
train_data = train_data.query("item_id in @items_to_keep")
```

**Comment by Warit314** [comment]
Did you solve the problem @toshimasoni  i'm facing the same problem right now.

**Comment by shchur** [comment]
Hi @Warit314, you can find the instructions for converting your data to a regular time index here: https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-indepth.html#handling-irregular-data-and-missing-values.

**Comment by cozy-hn** [comment]
@shchur Thanks a lot you are my life saver

**Comment by shchur** [comment]
@wask24 if you want to train a model to predict 5 steps into the future, you need to have time series with at least `2*prediction_length + 1` (11) observations. This is necessary for model selection to be possible.

Alternatively, you can fix the model in advance and skip model selection. This way the restriction on the amount of data will be removed. Here is an example of using the Chronos-Bolt model and skipping model selection:
```python
predictor = TimeSeriesPredictor(...).fit(train_data, presets="bolt_base")
forecast = predictor.predict(train_data)
```
