### ISSUE TITLE
[BUG]eda example: 

### ISSUE THREAD

**Issue by huijuanmeng** [autogluon/autogluon#3486]
run example in https://auto.gluon.ai/stable/tutorials/eda/eda-auto-anomaly-detection.html

received an error:

ValueError: node array from the pickle has an incompatible dtype:
- expected: [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
- got     : {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}

**Comment by gradientsky** [comment]
This should be fixed in https://github.com/autogluon/autogluon/pull/3406
