### ISSUE TITLE
Not able to load FewShotSVMPredictor model in AWS Sagemaker

### ISSUE THREAD

**Issue by AmanMahnot** [autogluon/autogluon#3488]
Hi,
I am not able to load the FewShotSVMPredictor model that I have created on SageMaker. I am able to load the model locally, and it is working fine. However, when I try to load it on SageMaker, it throws the following error:

ERROR - 
LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on. 
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files, and it looks like 'sentence-transformers/msmarco-MiniLM-L-12-v3' is not the path to a directory containing a file named 'config.json'. Check your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

These are the only two files that were created when I developed this model:
1. fewshot_svm_assets.json
2. svm_model.pkl

This is how I created the model:
hyperparameters = {
"env.num_workers": 96,
'model.hf_text.checkpoint_name': '../data/all-mpnet-base-v2',
"model.hf_text.pooling_mode": "mean"
}
predictor = FewShotSVMPredictor(
label="Label",  # column name of the label
hyperparameters=hyperparameters,
eval_metric="acc",
presets='best_quality'
)

This is how I am loading the model:
predictor = FewShotSVMPredictor.load("Model_Name")

Thank you for your assistance.

**Comment by zhiqiangdon** [comment]
Should have been fixed in the latest pre-release and the coming 1.0 release. Checkout our newest tutorial on few shot classification (https://auto.gluon.ai/dev/tutorials/multimodal/advanced_topics/few_shot_learning.html). Now you do few shot classification through `MultiModalPredictor`.

**Comment by zhiqiangdon** [comment]
Tested in this PR: https://github.com/autogluon/autogluon/pull/3695
