### ISSUE TITLE
[BUG] Couldn't install imagepredictor from autogluon.vision

### ISSUE THREAD

**Issue by Aruna2897** [autogluon/autogluon#3496]
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3553 in run_code        │
│                                                                                                  │
│   3550 │   │   │   │   elif async_ :                                                             │
│   3551 │   │   │   │   │   await eval(code_obj, self.user_global_ns, self.user_ns)               │
│   3552 │   │   │   │   else:                                                                     │
│ ❱ 3553 │   │   │   │   │   exec(code_obj, self.user_global_ns, self.user_ns)                     │
│   3554 │   │   │   finally:                                                                      │
│   3555 │   │   │   │   # Reset our crash handler in place                                        │
│   3556 │   │   │   │   sys.excepthook = old_excepthook                                           │
│ in <cell line: 1>:1                                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/autogluon/vision/__init__.py:1 in <module>               │
│                                                                                                  │
│ ❱ 1 from .predictor import ImagePredictor                                                        │
│   2 from .detector import ObjectDetector                                                         │
│   3                                                                                              │
│   4 ImageDataset = ImagePredictor.Dataset                                                        │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/autogluon/vision/predictor/__init__.py:1 in <module>     │
│                                                                                                  │
│ ❱ 1 from .predictor import *                                                                     │
│   2                                                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/autogluon/vision/predictor/predictor.py:20 in <module>   │
│                                                                                                  │
│    17 from autogluon.common.utils.resource_utils import ResourceManager                          │
│    18 from autogluon.core.constants import MULTICLASS, BINARY, REGRESSION                        │
│    19 from autogluon.core.data.label_cleaner import LabelCleaner                                 │
│ ❱  20 from autogluon.core.utils.try_import import try_import_d8                                  │
│    21 from autogluon.core.utils.utils import generate_train_test_split                           │
│    22 from autogluon.multimodal.predictor import MultiModalPredictor                             │
│    23                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'autogluon.core.utils.try_import'

**Comment by zhiqiangdon** [comment]
`autogluon.vision` has been deprecated to in favor of `autogluon.multimodal`. Refer to our tutorial for image classification usage: https://auto.gluon.ai/stable/tutorials/multimodal/image_prediction/beginner_image_cls.html

**Comment by zhiqiangdon** [comment]
Let us know if you have issues in using `autogluon.multimodal`.
