### ISSUE TITLE
[BUG] SHAP waterfall plot does not consistently show positive class

### ISSUE THREAD

**Issue by callinSwitzer** [autogluon/autogluon#3497]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [X] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
When using ShapAnalysis (https://github.com/autogluon/autogluon/blob/master/eda/src/autogluon/eda/analysis/explain.py#L120), to create a waterfall plot, I see that sometimes the positive class is represented as increasing along the horizontal axis, and other times the negative class is increasing along the horizontal axis. Furthermore, I would expect features that increase the probability of being in the positive class to be red, and features that increase the probability of being in the negative class to be blue. 

**Expected behavior**
I would expect that moving right along the horizontal axis of the waterfall plot would mean increasing probability of being in the positive class. The [SHAP documentation](https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/waterfall.html#:~:text=The%20bottom%20of%20a%20waterfall%20plot%20starts%20as%20the%20expected%20value%20of%20the%20model%20output%2C%20and%20then%20each%20row%20shows%20how%20the%20positive%20(red)%20or%20negative%20(blue)%20contribution%20of%20each%20feature%20moves%20the%20value%20from%20the%20expected%20model%20output%20over%20the%20background%20dataset%20to%20the%20model%20output%20for%20this%20prediction.) shows red as a positive contribution.

**To Reproduce**
```
import autogluon.eda.auto as auto

# get predictor, training data, and select a row to explain
predictor = ...
train_data = ...
explain_row = ...

auto.explain_rows(
    train_data=train_data,
    model=predictor,
    display_rows=True,
    rows=explain_row,
    plot="waterfall",
)
```

**Screenshots / Logs**

![image (14)](https://github.com/autogluon/autogluon/assets/7850472/956c9a28-ca4c-4072-99a3-177e6844862b)

**Installed Versions**

```python
INSTALLED VERSIONS
------------------
date                   : 2023-08-29
time                   : 16:24:25.698539
python                 : 3.10.12.final.0
OS                     : Linux
OS-release             : 5.4.250-173.369.amzn2int.x86_64
Version                : #1 SMP Tue Aug 1 20:57:12 UTC 2023
machine                : x86_64
processor              : x86_64
num_cores              : 48
cpu_ram_mb             : 191085
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 258960

accelerate             : 0.16.0
autogluon              : None
autogluon.common       : 0.8.2
autogluon.core         : 0.8.2
autogluon.eda          : 0.8.2
autogluon.features     : 0.8.2
autogluon.multimodal   : 0.7.0
autogluon.tabular      : 0.8.2
boto3                  : 1.28.26
catboost               : 1.1.1
defusedxml             : 0.7.1
evaluate               : 0.3.0
fairscale              : 0.4.13
fastai                 : 2.7.12
grpcio                 : 1.49.1
hyperopt               : 0.2.7
imodels                : None
ipython                : 8.12.2
ipywidgets             : 8.1.0
jinja2                 : 3.1.2
jsonschema             : 4.19.0
lightgbm               : 3.3.5
matplotlib             : 3.6.3
missingno              : 0.5.2
networkx               : 3.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.4
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
pandas                 : 1.5.3
phik                   : 0.12.3
Pillow                 : 9.5.0
psutil                 : 5.9.5
pydantic               : 1.10.12
pyod                   : 1.0.9
pytesseract            : 0.3.10
pytorch-lightning      : 1.9.5
pytorch-metric-learning: 1.7.3
ray                    : 2.3.1
requests               : 2.28.2
scikit-image           : 0.19.3
scikit-learn           : 1.2.2
scikit-learn-intelex   : None
scipy                  : 1.11.1
seaborn                : 0.12.2
sentencepiece          : 0.1.99
seqeval                : 1.2.2
setuptools             : 60.2.0
shap                   : 0.41.0
skl2onnx               : None
suod                   : 0.0.9
tabpfn                 : None
tensorboard            : 2.14.0
text-unidecode         : 1.3
timm                   : 0.6.13
torch                  : 1.12.1
torchmetrics           : 0.8.2
torchvision            : 0.13.1
tqdm                   : 4.65.2
transformers           : 4.26.1
vowpalwabbit           : None
xgboost                : 1.7.6
yellowbrick            : 1.5
```

</details>

**Comment by gradientsky** [comment]
From discussion w/ @Innixma : standard way to get positive class from Tabular:
1) `TabularPredictor.positive_class`
2) Alternatively, it is always the last column in predict proba aka `y_pred_proba[:, 1]`

**Comment by gradientsky** [comment]
Closing since the fix was merged. Library release need to happen though @tonyhoo
