### ISSUE TITLE
Timeseries forecasting DirectTabular no attribute set_index

### ISSUE THREAD

**Issue by tavlox** [autogluon/autogluon#3503]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
When trying to use DirectTabular for timeseries forecasting I encounter the following error: 
Warning: Exception caused DirectTabular to fail during training... Skipping this model.
	'Series' object has no attribute 'set_index'

**Installed Versions**
autogluon 0.8.0

**code**
predictor = TimeSeriesPredictor(prediction_length=args.prediction_length, path=args.path, target="target", eval_metric="sMAPE", verbosity=3)
            predictor.fit(train_prepared, presets=args.model_quality,  hyperparameters={"DirectTabular": {
                "tabular_hyperparameters": {
                    "GBM": {}, }, "subsampling_strategy": {"items"}}}, hyperparameter_tune_kwargs=None, enable_ensemble=False)

</details>

**Comment by shchur** [comment]
I believe this issue has been fixed in v0.8.2 (#3341), can you please check if you encounter it with the latest release?
