### ISSUE TITLE
Time series fit() method very slow , GPU , CPU usage very low. Tabular fit is fine.

### ISSUE THREAD

**Issue by RichardYangHe** [autogluon/autogluon#3505]
<img width="453" alt="image" src="https://github.com/autogluon/autogluon/assets/126909137/8a3d25df-79df-4c43-b00b-36e997e3d85c">
<img width="239" alt="image" src="https://github.com/autogluon/autogluon/assets/126909137/2ee87750-b39f-46dd-8df9-4c5eeafe20ea">

Seems like its not using GPU, and only use one core of CPU.

--------------------------
Models that will be trained: ['Naive', 'SeasonalNaive', 'Theta', 'AutoETS', 'RecursiveTabular', 'TemporalFusionTransformer', 'DirectTabular', 'DynamicOptimizedTheta', 'ARIMA', 'AutoARIMA', 'SimpleFeedForward', 'DLinear']
Training timeseries model Naive. 
	-0.0007       = Validation score (-mean_wQuantileLoss)
	32.89   s     = Training runtime
	7.75    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive. 
	-0.0007       = Validation score (-mean_wQuantileLoss)
	32.30   s     = Training runtime
	7.55    s     = Validation (prediction) runtime
Training timeseries model Theta. 
	-0.0008       = Validation score (-mean_wQuantileLoss)
	32.46   s     = Training runtime
	29.36   s     = Validation (prediction) runtime
Training timeseries model AutoETS. 
	-0.0007       = Validation score (-mean_wQuantileLoss)
	32.36   s     = Training runtime
	23.71   s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular. 
	-0.0006       = Validation score (-mean_wQuantileLoss)
	140.41  s     = Training runtime
	193.35  s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer. 
	-0.0008       = Validation score (-mean_wQuantileLoss)
	45798.88 s    = Training runtime
	32.96   s     = Validation (prediction) runtime
Training timeseries model DirectTabular. 
	Warning: Exception caused DirectTabular to fail during training... Skipping this model. 
Training timeseries model DynamicOptimizedTheta. 
	-0.0007       = Validation score (-mean_wQuantileLoss)
	33.17   s     = Training runtime
	32.22   s     = Validation (prediction) runtime
Training timeseries model ARIMA. 
	-0.0007       = Validation score (-mean_wQuantileLoss)
	32.82   s     = Training runtime
	7.67    s     = Validation (prediction) runtime
Training timeseries model AutoARIMA. 
	-0.0007       = Validation score (-mean_wQuantileLoss)
	32.69   s     = Training runtime
	18.03   s     = Validation (prediction) runtime
Training timeseries model SimpleFeedForward. 
	-0.0018       = Validation score (-mean_wQuantileLoss)
	45294.22 s    = Training runtime
	4.51    s     = Validation (prediction) runtime
Training timeseries model DLinear. 
----------------------

is this normal? if its not , if i can get some directions , i will try my best to debug.
Thank you.

**Comment by shchur** [comment]
Hi, thank you for opening the issue.

In general, the CPU/GPU utilization depends not on AutoGluon, but rather on the underlying libraries like GluonTS and StatsForecast, so we cannot always guarantee full resource utilization. 

However, the reported runtime for `SimpleFeedForward` and `TemporalFusionTransformer` is indeed extremely high, training for these models usually shouldn't take more than 100-500 seconds. Can you please share the code & data that you used to obtain these results?

**Comment by RichardYangHe** [comment]
Hi, thank you for responding.

As my find, if the dataframe length is long , like : 200000000, as freq 1 second 2 line for 3 year, the CPU
GPU useage will be like the PIC above.
I tested the 1 second 2 line for 3month, this length of dataframe will have higher useage of both CPU and GPU.
up to 20%, not 1%.

Here is the code&data:

```import pandas as pd import numpy as np from datetime import datetime, timedelta import time from autogluon.tabular import TabularDataset, TabularPredictor from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor  def get_data(start_month=1, end_month=2,start_year=2023):     start_date = datetime(start_year, start_month, 1)     end_date = datetime(2023, end_month, 1)     delta_seconds = timedelta(seconds=1)      total_seconds = int((end_date - start_date).total_seconds())      timestamps = [start_date + i * delta_seconds for i in range(total_seconds)]      random_walk_a = np.random.choice([-1, 1], total_seconds)     random_walk_b = np.random.choice([-0.1, 0.1], total_seconds)      value_a = 1000     value_b = 100      values_a = [value_a]     values_b = [value_b]      for step_a, step_b in zip(random_walk_a, random_walk_b):         value_a += step_a         value_b += step_b         values_a.append(value_a)         values_b.append(value_b)      df_a = pd.DataFrame({         'timestamp': timestamps,         'item_id': ['a'] * total_seconds,         'target': values_a[:-1]     })      df_b = pd.DataFrame({         'timestamp': timestamps,         'item_id': ['b'] * total_seconds,         'target': values_b[:-1]     })      df = pd.concat([df_a, df_b]).sort_values('timestamp').reset_index(drop=True)      print(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))     print(df.head())      return df  def get_filled_data(df):     if 'Unnamed: 0' in df.columns:         df = df.drop(columns=['Unnamed: 0'])     df['timestamp'] = df['timestamp'].astype(str)      print(df.head())      df_irregular = TimeSeriesDataFrame(df)     print(df_irregular.head(10))      df_regular = df_irregular.to_regular_index(freq="S")     print(df_regular.head(10))     print(df_regular.shape)      start = 60*60*10     print(df.iloc[start:start + 120])      timestamps = df_regular.index.get_level_values("timestamp")     df_regular["weekday"] = timestamps.weekday      df_regular['normalized_time'] = (timestamps.second + timestamps.minute * 60 + timestamps.hour * 3600) / 86400.0      df_filled = df_regular.fill_missing_values()  #    df_filled['target'] = (df_filled['target'] * 10).astype(int)     print(df_filled.iloc[start:start + 120])     print(df_filled.shape)      return df_filled if __name__ == '__main__':     df = get_data(start_year=2020)     train_df = get_filled_data(df)      predictor = TimeSeriesPredictor(         prediction_length=60*1,         target="target",         known_covariates_names=["weekday",'normalized_time'],      ).fit(train_df,           presets="high_quality",           hyperparameters={               "Naive": {},               "SeasonalNaive": {},               'Theta':{},               'AutoETS':{},               'RecursiveTabular':{},               'DirectTabular':{},               'DynamicOptimizedTheta':{},               'ARIMA':{},               'AutoARIMA':{},               'SimpleFeedForward':{},                # 'DeepAR':{}               # 'PatchTST':{},               'TemporalFusionTransformer':{'context_length':600},               'DLinear':{'context_length':600},           },            )```

**Comment by shchur** [comment]
Thank you for providing the detailed code for reproducing the problem!

The problem comes from the fact that the time series are very long and the underlying models struggle to process it. We have not come across benchmark datasets where a single time series has such a high length, which is why we have not really considered this use case when developing the framework.

I would recommend to shorten the data to at most ~10^6-10^7 timesteps (maybe even start with shorter series?). It's very unlikely that any model can benefit from a longer training series, so this shouldn't affect the forecast accuracy but will speed things up significantly.

**Comment by RichardYangHe** [comment]
Thank you for the advice that will help me a lot!
