### ISSUE TITLE
How to get all prediction for a time series 

### ISSUE THREAD

**Issue by maximilianreimer** [autogluon/autogluon#3525]
Hi,
thanks für the great package. 

I was wondering if there is a possibility to get all predictions for a time series dataset of a trained predictor? 

The predict method just gives you the prediction after the last time step of the dataset. I would like to have a function that gives me for all dates in the dataset (which have enough historical data) the prediction for the horizons of the model. The leader board function does probably internally do something similar. 

Thanks.

**Comment by shchur** [comment]
Hi, thank you for the suggestion! You can get the out-of-fold predictions using the following code:
```python
predictor = TimeSeriesPredictor(...).fit(train_data, ...)
trainer = predictor._trainer
oof_predictions = {}
for model in trainer.get_model_names():
    oof_predictions[model] = trainer._get_model_oof_predictions(model)
val_data = trainer._get_ensemble_oof_data(train_data)
```
Note that this is not public API, so this code is not guaranteed to work in future releases.

**Comment by BigW11** [comment]
Hi, with reference to the no guarantee above, exporting the oof predictions into a csv file would be super useful to do further analysis and validate when working with time series. Using the code above when trying to run that in Colab I get the following error. For time series work exporting those oof predictions is an integral part of testing and evaluation so any alternative ways to do that would be good thank you!

predictor = TimeSeriesPredictor(
    prediction_length=5,
    path="autogluon-nord-hourly",
    target="target",
    eval_metric="MASE",
)

predictor.fit(
    train_data,
    presets="medium_quality",
    time_limit=600,
)

#new section to test export funtion
trainer = predictor._trainer
oof_predictions = {}
for model in trainer.get_model_names():
    oof_predictions[model] = trainer._get_model_oof_predictions(model)
val_data = trainer._get_ensemble_oof_data(train_data)


Beginning AutoGluon training... Time limit = 600s
AutoGluon will save models to 'autogluon-nord-hourly'
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Sat Nov 18 15:31:17 UTC 2023
CPU Count:          2
GPU Count:          0
Memory Avail:       10.62 GB / 12.67 GB (83.8%)
Disk Space Avail:   75.49 GB / 107.72 GB (70.1%)
===================================================
Setting presets to: medium_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': MASE,
 'hyperparameters': 'light',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 5,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'target',
 'time_limit': 600,
 'verbosity': 2}

Inferred time series frequency: 'D'
Provided train_data has 4016 rows, 1 time series. Median time series length is 4016 (min=4016, max=4016). 

Provided data contains following columns:
	target: 'target'

AutoGluon will gauge predictive performance using evaluation metric: 'MASE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2024-05-10 15:35:18
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'TemporalFusionTransformer']
Training timeseries model Naive. Training for up to 75.0s of the 599.9s of remaining time.
	-0.0265       = Validation score (-MASE)
	0.05    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive. Training for up to 85.7s of the 599.9s of remaining time.
	-2.3573       = Validation score (-MASE)
	0.04    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular. Training for up to 100.0s of the 599.8s of remaining time.
	-1.6434       = Validation score (-MASE)
	5.66    s     = Training runtime
	0.17    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 118.8s of the 593.9s of remaining time.
	-0.8405       = Validation score (-MASE)
	3.59    s     = Training runtime
	0.10    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 147.6s of the 590.2s of remaining time.
	-0.0265       = Validation score (-MASE)
	0.03    s     = Training runtime
	0.83    s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 196.4s of the 589.3s of remaining time.
	-0.1097       = Validation score (-MASE)
	0.03    s     = Training runtime
	0.30    s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer. Training for up to 294.5s of the 589.0s of remaining time.
	-0.0520       = Validation score (-MASE)
	182.85  s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'Naive': 1.0}
	-0.0265       = Validation score (-MASE)
	0.40    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'TemporalFusionTransformer', 'WeightedEnsemble']
Total runtime: 194.30 s
Best model: Naive
Best model score: -0.0265

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-11-1ac6a78feec6>](https://localhost:8080/#) in <cell line: 17>()
     16 oof_predictions = {}
     17 for model in trainer.get_model_names():
---> 18     oof_predictions[model] = trainer._get_model_oof_predictions(model)
     19 val_data = trainer._get_ensemble_oof_data(train_data)

2 frames

[/usr/local/lib/python3.10/dist-packages/autogluon/common/loaders/load_pkl.py](https://localhost:8080/#) in load(path, format, verbose, **kwargs)
     41 
     42     if compression_fn in compression_fn_map:
---> 43         with compression_fn_map[compression_fn]["open"](validated_path, "rb", **compression_fn_kwargs) as fin:
     44             object = pickle.load(fin)
     45     else:

FileNotFoundError: [Errno 2] No such file or directory: 'autogluon-nord-hourly/models/WeightedEnsemble/utils/oof.pkl'

**Comment by shchur** [comment]
Hi @BigW11, my bad, a small modification is needed since the WeightedEnsemble model does not provide OOF predictions.
```python
predictor = TimeSeriesPredictor(...).fit(train_data, ...)
trainer = predictor._trainer
oof_predictions = {}
for model in trainer.get_model_names():
    if model != "WeightedEnsemble":
        oof_predictions[model] = trainer._get_model_oof_predictions(model)
val_data = trainer._get_ensemble_oof_data(train_data)

```

**Comment by shchur** [comment]
Closing the issue assuming that the above comment addresses it. Please feel free to re-open if that's not the case.

**Comment by BigW** [comment]
Apologies for the delay @shchur but I have been traveling. 

Thank you for the sample code.
I was not aware the WeightedEnsemble model does not provide OOF predictions.
That does not allow me to really test AG in a more thourough way as most of the optimal models generated are WeightedEnsemble. If I cant generate OOF predictions for those its not possible to test and include this in production. 

As a result I am now looking at Chronos as an alternative. 

I tried the following code:
`!pip install -q --upgrade pip
!pip install uv
!uv pip install -q autogluon.timeseries --system
!uv pip uninstall -q torchaudio torchvision torchtext --system # fix incompatible package versions on Colab`

`from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor`

`data = TimeSeriesDataFrame(
    "https://autogluon.s3.amazonaws.com/datasets/timeseries/m4_hourly_tiny/train.csv")data.head()`

`prediction_length = 24
train_data, test_data = data.train_test_split(prediction_length)
predictor = TimeSeriesPredictor(prediction_length=prediction_length).fit(
    train_data, presets="chronos_tiny",
)`

That all works well with the following output

> Beginning AutoGluon training...
AutoGluon will save models to 'AutogluonModels/ag-20240707_163734'
=================== System Info ===================
AutoGluon Version:  1.1.1
Python Version:     3.9.17
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Mon Mar 25 18:16:11 UTC 2024
CPU Count:          16
GPU Count:          0
Memory Avail:       92.91 GB / 123.81 GB (75.0%)
Disk Space Avail:   67108863.98 GB / 67108863.98 GB (100.0%)
===================================================
Setting presets to: chronos_tiny
Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'hyperparameters': {'Chronos': {'model_path': 'tiny'}},
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 24,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': True,
 'target': 'target',
 'verbosity': 2}
Inferred time series frequency: 'H'
Provided train_data has 13520 rows, 20 time series. Median time series length is 676 (min=676, max=676). 
Provided data contains following columns:
target: 'target'
AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================
Starting training. Start time is 2024-07-07 16:37:37
Models that will be trained: ['Chronos[tiny]']
Training timeseries model Chronos[tiny]. 
0.00    s     = Training runtime
Training complete. Models trained: ['Chronos[tiny]']
Total runtime: 1.14 s
Best model: Chronos[tiny]

Reusing your code example but for Chronos Tiny

`from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
Ensure to load the TimeSeriesDataFrame class before calling it
data = TimeSeriesDataFrame("https://autogluon.s3.amazonaws.com/datasets/timeseries/m4_hourly_tiny/train.csv")
prediction_length = 24
train_data, test_data = data.train_test_split(prediction_length)
predictor = TimeSeriesPredictor(prediction_length=prediction_length).fit(
    train_data, presets="chronos_tiny",)
trainer = predictor._trainer
oof_predictions = {}
for model in trainer.get_model_names():
    if model == "Chronos[tiny]":
        oof_predictions[model] = trainer._get_model_oof_predictions(model)
val_data = trainer._get_ensemble_oof_data(train_data)
print(val_data)`

I then get a bunch of errors as below I cant seem fix?

![Snip20240707_1](https://github.com/autogluon/autogluon/assets/6699455/66d0faa7-42f9-4fc0-9dfe-e1b50d635089)

**Comment by shchur** [comment]
Hi @BigW, when using the `presets="chronos_tiny"` (or `chronos_mini`, `chronos_small`, etc.), we skip model selection since only 1 model is used, so OOF predictions are not generated. In theory, you could disable this behavior by setting `predictor.fit(train_data, presets="chronos_small", skip_model_selection=False)`.

However, I would rather recommend to perform evaluation outside the predictor (instead of relying on the private API). This section of the documentation shows how you can obtain predictions for multiple backtest windows in AutoGluon: https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-indepth.html#backtesting-using-multiple-windows.

**Comment by shchur** [comment]
Here is how you can use the splitter to generate OOF predictions with Chronos
```python
from autogluon.timeseries.splitter import ExpandingWindowSplitter

predictor = TimeSeriesPredictor(...).fit(full_data, presets="chronos_base")  # model is pre-trained so full_data is not used
splitter = ExpandingWindowSplitter(prediction_length=prediction_length, num_val_windows=3)
predictions_per_window = dict()
for window_idx, (train_split, val_split) in enumerate(splitter.split(full_data)):
    predictions_per_window[window_idx] = predictor.predict(train_split)
```

**Comment by BigW** [comment]
Thank you again @shchur I will try that
