### ISSUE TITLE
Not able to load the autogluon model Independently

### ISSUE THREAD

**Issue by kartikeya72001** [autogluon/autogluon#3574]
I want to load the saved autogluon model in scala as a pmml file, but for that, I need to resolve dependencies associated with the generated pickle file on doing model_training.

I performed this operation:

`predictor = TabularPredictor(label=y_var, path=output_vars_path, eval_metric=gluon_scorer).fit(train_data, hyperparameters = hyperparameters, hyperparameter_tune_kwargs = hyperparameter_tune_kwargs, time_limit = time_limit)`

Now I want to load the saved models and convert them into a pmml file, but I am not able to remove the autogluon dependencies

**Comment by shchur** [comment]
Please refer to #4237 for this information.
