### ISSUE TITLE
TabularPredictor Calibration

### ISSUE THREAD

**Issue by yudizhangzyd** [autogluon/autogluon#3682]
Hello,

Does the current version of TabularPredictor has probability calibration functionality in it or automatically calibrate the probabilities? The document seems not mention it.

Thanks!

**Comment by Innixma** [comment]
Yes, you can specify `predictor.fit(calibrate=True)`. It also automatically calibrates when eval_metric is `log_loss`.

You can also calibrate the decision threshold: https://auto.gluon.ai/stable/tutorials/tabular/tabular-indepth.html#decision-threshold-calibration
