### ISSUE TITLE
Upgrade pillow version to >=10.0.1 

### ISSUE THREAD

**Issue by shiva404** [autogluon/autogluon#3694]
Autoglon with version 0.8.2 has dependency on Pillow<9.6,>=9.3 but there is a security vulnerable on this version. More details can be found under below link.

https://security.snyk.io/vuln/SNYK-PYTHON-PILLOW-5918878

Can pillow version be upgraded to >= 10.0.1 ?

**Comment by shchur** [comment]
Hello, this issue has been addressed in #3688 and will be available in the upcoming v1.0 release.
