### ISSUE TITLE
[AutoMM] GroundingDino used in AutoMM doesn't support CUDA 12 and Torch 2.1

### ISSUE THREAD

**Issue by tonyhoo** [autogluon/autogluon#3708]
Currently we are installing groundingdino from [here](https://github.com/autogluon/autogluon/blob/ee0967dda2aefb5ae871abd16f093f350a0efac8/.github/workflow_scripts/setup_groundingdino.sh#L2). However, it got issue with Torch 2.1 and CUDA 12. See [log](https://github.com/autogluon/autogluon/actions/runs/6868158330/job/18678972885)

**Comment by rxjx** [comment]
I believe this can be resolved by installing the same version of CUDA as used in PyTorch. Your error log tells you that PyTorch is using 11.7 so you need to install that. I ran into the same error. Installing a matching version of CUDA via apt, adding /usr/local/cuda-11.x to the path and setting CUDA_HOME correctly via .bashrc, and then adding the correct python headers solved this for me.

**Comment by zhiqiangdon** [comment]
@rxjx Thanks for the suggestion! This custom installation is automatic and may cause obstacles for some users with less such knowledge. We will deprecate the current groundingdino implementation and add it back through the MMDetection support later.

**Comment by zhiqiangdon** [comment]
Fixed by # 3974
