### ISSUE TITLE
[BUG] to_regular_index raises ValueError on duplicate indices

### ISSUE THREAD

**Issue by Ai-Ya-Ya** [autogluon/autogluon#3757]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [x] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
Running `TimeSeriesDataFrame.to_regular_index(freq='D')` on an irregularly-sampled dataframe raises `ValueError: cannot reindex on an axis with duplicate labels` even when I made sure there were no duplicate labels with `df.groupby(['grid', 'time']).sum().reset_index()` (so the `df` contained three columns, `[grid, time, target]`) then `train_data = TimeSeriesDataFrame.fromDataFrame(df, id_column='grid', timestamp_column='time')`. 

**Expected behavior**
The method is supposed to fill all days that weren't sampled. However, I get the aforementioned `ValueError` before.  Attached is a full error log.

**To Reproduce**
```python
import pandas as pd
import numpy as np
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
import requests

df = pd.read_csv("chicago_crime_with_grid.csv")

columns_that_matter = ['grid', 'time']
df = df.rename(columns={'GRID_ID' : 'grid', 'Date' : 'time'})
df = df[columns_that_matter]
df['time'] = pd.to_datetime(df['time']).dt.date

df['weighted_crime'] = 1.0
df1 = pd.DataFrame(df['grid'].unique(), columns=['grid'])
df1['time'] = pd.to_datetime(df['time'].min())
df1['weighted_crime'] = 0.0
df = pd.concat([df, df1])
df1 = pd.DataFrame(df['grid'].unique(), columns=['grid'])
df1['time'] = pd.to_datetime(df['time'].max())
df1['weighted_crime'] = 0.0
df = pd.concat([df, df1])

df = df.groupby(['grid', 'time']).sum().reset_index()
df = df.sort_values(by='time')

train_data = TimeSeriesDataFrame.from_data_frame(df, id_column='grid', timestamp_column='time')
train_data = train_data.to_regular_index(freq='D')
```

`chicago_crime_with_grid.csv` is [this dataset](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2) with an extra `grid` column at the end. 

Furthermore, this bug is inconsistent. I ran this on a Jupyter notebook just fine, but this fails multiple times when I copy-paste my Jupyter code into a Python script file. 

I know the `df.sort_values(by='time')` is not necessary, and that `TimeSeriesDataFrame` should sort it anyway, but that line made the error disappear on Jupyter (not in Python script though).

**Screenshots / Logs**
[1752531.txt](https://github.com/autogluon/autogluon/files/13453067/1752531.txt)

**Installed Versions**

<details>

```python
INSTALLED VERSIONS
------------------
date                   : 2023-11-23
time                   : 14:50:01.550589
python                 : 3.9.16.final.0
OS                     : Linux
OS-release             : 4.18.0-477.27.1.el8_8.x86_64
Version                : #1 SMP Thu Aug 31 10:29:22 EDT 2023
machine                : x86_64
processor              : x86_64
num_cores              : 32
cpu_ram_mb             : 385078
cuda version           : 12.535.98
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 107810

accelerate             : 0.16.0
autogluon              : 0.8.2
autogluon.common       : 0.8.2
autogluon.core         : 0.8.2
autogluon.features     : 0.8.2
autogluon.multimodal   : 0.8.2
autogluon.tabular      : 0.8.2
autogluon.timeseries   : 0.8.2
boto3                  : 1.26.128
catboost               : 1.1.1
defusedxml             : 0.7.1
evaluate               : 0.2.2
fastai                 : 2.7.11
gluonts                : 0.13.7
hyperopt               : None
imodels                : None
jinja2                 : 3.1.2
joblib                 : 1.2.0
jsonschema             : 4.17.3
lightgbm               : 3.3.5
matplotlib             : 3.7.1
mlforecast             : 0.7.3
networkx               : 3.2.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.23.5
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.7
pandas                 : 1.5.3
Pillow                 : 9.4.0
psutil                 : 5.9.5
pydantic               : 1.10.7
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 1.9.4
pytorch-metric-learning: 1.7.3
ray                    : 2.2.0
requests               : 2.29.0
scikit-image           : 0.19.3
scikit-learn           : 1.2.2
scikit-learn-intelex   : None
scipy                  : 1.10.1
seqeval                : 1.2.2
setuptools             : 66.0.0
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.13.5
tabpfn                 : None
tensorboard            : 2.11.2
text-unidecode         : 1.3
timm                   : 0.9.10
torch                  : 1.12.1
torchmetrics           : 0.11.0
torchvision            : 0.13.0a0+8069656
tqdm                   : 4.65.0
transformers           : 4.26.1
ujson                  : 5.7.0
vowpalwabbit           : None
xgboost                : 1.7.4
```

</details>

**Comment by shchur** [comment]
Hi, thank you for the detailed bug description. Can you please try converting the frequency using the following code?
```python
train_data = TimeSeriesDataFrame.from_data_frame(df, id_column='grid', timestamp_column='time')
train_data = TimeSeriesDataFrame(train_data.groupby(level="item_id", sort=False).resample("D", level="timestamp").mean())
```

The implementation of `to_regular_index` is rather restrictive in AutoGluon v0.8.2 and it won't work if there are multiple rows with the same `item_id`, `timestamp` values in the DataFrame. We have completely refactored this method for the upcoming v1.0 release (new implementation available [here](https://github.com/autogluon/autogluon/blob/master/timeseries/src/autogluon/timeseries/dataset/ts_dataframe.py#L848)) and it's now based on `groupby` + `resample`, which should handle duplicate values in the index.

**Comment by shchur** [comment]
Closing this issue assuming that the above comment addressed it. Please feel free to re-open if it's not the case.
