### ISSUE TITLE
TimeSeriesPredictor redirect verbose output to file

### ISSUE THREAD

**Issue by lucical** [autogluon/autogluon#3766]
### Discussed in https://github.com/autogluon/autogluon/discussions/3765

<div type='discussions-op-text'>

<sup>Originally posted by **lucical** November 27, 2023</sup>
Hi,

How can I save the verbose output from the terminal when I train the `TimeSeriesPredictor` to a file? I found [these answers](https://github.com/autogluon/autogluon/issues/2325) for `TabularPredictor` but none of it works for Time Series prediction and there is no support for logging implemented like there `predictor = TabularPredictor(..., log_to_file=True)`.

Thanks!

</div>

**Comment by canerturkmen** [comment]
Hi @lucical, the issue should now be fixed and will be released with the next AG release. Thank you again for bringing it to our attention.
