### ISSUE TITLE
Refine v1.0 Release Notes

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#3791]
1. Move papers to end to release notes
2. Move special thanks to end of release notes
3. Potentially add links to spotlights to dedicated pages on each spotlight to save space
4. Potentially reduce verbosity of spotlights
5. Add spotlights for AutoMM and TimeSeries

**Comment by zhiqiangdon** [comment]
6. Adjust the order of the three modules. Currently, Tabular is at the top of both spotlight and regular.
7. Only mention papers already accepted (top conference preferred). Arxiv papers generally don't count since they are not peer-reviewed.

**Comment by Innixma** [comment]
Re 7: Move in-review papers to "In-Review Papers" section to avoid confusion with "Newly Published Papers"
