### ISSUE TITLE
RuntimeError: Version 1.0

### ISSUE THREAD

**Issue by luccadu98** [autogluon/autogluon#3793]
=================== System Info ===================
AutoGluon Version:  1.0.0
Python Version:     3.9.18
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.19045
CPU Count:          16
Pytorch Version:    2.0.1+cu118
CUDA Version:       11.8
Memory Avail:       15.24 GB / 31.92 GB (47.7%)
Disk Space Avail:   WARNING, an exception (FileNotFoundError) occurred while attempting to get available disk space. Consider opening a GitHub Issue.

**Describe the bug**
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Expected behavior**
I tryed your example on Object Dection. When i try to run: 
start = time.time()
predictor.fit(train_path)  # Fit
train_end = time.time()

I get the error message from above

**To Reproduce**

**Installed Versions**

INSTALLED VERSIONS
------------------                      
date                   : 2023-12-03     
time                   : 17:59:29.575980
python                 : 3.9.18.final.0 
OS                     : Windows        
OS-release             : 10
Version                : 10.0.19045
machine                : AMD64
processor              : Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
num_cores              : 16
cpu_ram_mb             : 32688.80859375
cuda version           : None
num_gpus               : 1
gpu_ram_mb             : [13798]
avail_disk_size_mb     : None

accelerate             : 0.21.0
async-timeout          : 4.0.3
autogluon              : 1.0.0
autogluon.common       : 1.0.0
autogluon.core         : 1.0.0
autogluon.features     : 1.0.0
autogluon.multimodal   : 1.0.0
autogluon.tabular      : 1.0.0
autogluon.timeseries   : 1.0.0
boto3                  : 1.33.6
catboost               : 1.2.2
defusedxml             : 0.7.1
evaluate               : 0.4.1
fastai                 : 2.7.13
gluonts                : 0.14.2
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.2
joblib                 : 1.3.2
jsonschema             : 4.17.3
lightgbm               : 4.1.0
lightning              : 2.0.9.post0
matplotlib             : 3.8.2
mlforecast             : 0.10.0
networkx               : 3.2.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.4
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
orjson                 : 3.9.10
pandas                 : 2.1.3
Pillow                 : 10.1.0
psutil                 : 5.9.6
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 2.0.9.post0
pytorch-metric-learning: 1.7.3
ray                    : 2.6.3
requests               : 2.28.2
scikit-image           : 0.20.0
scikit-learn           : 1.3.2
scikit-learn-intelex   : None
scipy                  : 1.9.1
seqeval                : 1.2.2
setuptools             : 60.2.0
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.0
tabpfn                 : None
tensorboard            : 2.15.1
text-unidecode         : 1.3
timm                   : 0.9.12
torch                  : 2.0.1+cu118
torchmetrics           : 1.1.2
torchvision            : 0.15.2+cu118
tqdm                   : 4.65.2
transformers           : 4.31.0
utilsforecast          : 0.0.10
vowpalwabbit           : None
xgboost                : 2.0.2

**Comment by Innixma** [comment]
Please provide exact reproducible code for us to assist.

Additionally, please ensure you used `if __name__ == '__main__':` as mentioned in the error message.
