### ISSUE TITLE
How to stop early-stopping globally 

### ISSUE THREAD

**Issue by AhangarAamir** [autogluon/autogluon#3798]
I have run AutoGluon multiple times, but most of the time, it completes before the specified time_limit. Is there any way to prevent early stopping and ensure that it utilizes the entire allocated time?

**Comment by AhangarAamir** [comment]
@Innixma please reply on this

**Comment by shchur** [comment]
This is not caused by early-stopping, this is caused by the fact that AutoGluon trained all the algorithms in its portfolio and there is nothing left to do. You can set `time_limit=None` to ensure that all algorithms are trained without any constraints.
