### ISSUE TITLE
Autogluon uses PyMuPDF, which has a very restrictive license

### ISSUE THREAD

**Issue by zkalson** [autogluon/autogluon#3800]
Hi all,

PyMuPDF is licensed under the copyleft GNU AFFERO GPL 3.0. I noticed that it is used in:
autogluon\multimodal\data\process_document.py (import fitz)

It seems that having to install PyMuPDF could cause some licensing issues. On the other hand, I know there aren't many easy ways to convert pdfs to images without depending on poppler.

**Comment by zhiqiangdon** [comment]
Hi, we have removed PyMuPDF from our installation. Users can install it by themselves to use the PDF classification feature.

**Comment by zhiqiangdon** [comment]
Thanks @zkalson . Feel free to dive into it and provide suggestions!

**Comment by tonyhoo** [comment]
Resolved by https://github.com/autogluon/autogluon/pull/4096
