### ISSUE TITLE
[BUG]. Unable to compile NeuralNetTorch to onnx

### ISSUE THREAD

**Issue by andborth** [autogluon/autogluon#3804]
**Bug Report Checklist**

- [x ] I provided code that demonstrates a minimal reproducible example.  
- [ x] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
Compilation of NeuralNetTorch models consistently fails for me across several datasets.  I get the error showed in the attached JupyterLab notebook:

`RuntimeError: Opset number 19 is higher than targeted opsets {'': 18} for node type 'Reshape' name='Re_Reshape3' input=['argmin_col0', 'Re_Reshapecst3'] output=['reshape_col0'] (domain='').`

**Expected behavior**
RF and XT compile without problems.  The issue is only with NN_TORCH

**To Reproduce**
See below.  The referenced file is accessible to the AWS AutoGluon team.

```python
path_prefix = "./ar_benchmark_dataset/"

image_col = "image"

target = "MEMBER"
eval_metric = "log_loss" 
usually_ignored_columns = ["signalData","MODIFIED_AT",'class_name','item_id','imageId']

target_class = '%SC%ProductSafety%RecalledProducts%EU_Recalls_ES_Christmas_Dancing_Cactus'  

from autogluon.tabular import TabularPredictor

ignored_columns = usually_ignored_columns + [image_col]
presets = ['medium_quality', {'excluded_model_types':['GBM','XGB','CAT','FASTAI','KNN']}]

import pandas as pd
path_for_train = "{}{}".format(path_prefix, target_class)
print("Now reading from: {}".format(path_for_train))

all_train = pd.read_parquet(path_for_train)

train = all_train[all_train["data_type"] == "train"].drop(columns=["data_type"])
display(train[target].value_counts())

predictor = TabularPredictor(label=target,eval_metric=eval_metric,
                         learner_kwargs=dict(ignored_columns=ignored_columns))
predictor.fit(train,presets=presets)
predictor.compile()  # Note the compilation!  
```

**Installed Versions**

<details>

```python

INSTALLED VERSIONS
------------------
date                : 2023-12-08
time                : 17:45:51.141403
python              : 3.10.13.final.0
OS                  : Linux
OS-release          : 5.10.192-183.736.amzn2.x86_64
Version             : #1 SMP Wed Sep 6 21:15:41 UTC 2023
machine             : x86_64
processor           : x86_64
num_cores           : 16
cpu_ram_mb          : 127337.50390625
cuda version        : None
num_gpus            : 0
gpu_ram_mb          : []
avail_disk_size_mb  : 1882070

async-timeout       : 4.0.3
autogluon           : None
autogluon.common    : 1.0.0
autogluon.core      : 1.0.0
autogluon.features  : 1.0.0
autogluon.tabular   : 1.0.0
boto3               : 1.33.10
catboost            : 1.2.2
fastai              : 2.7.13
hyperopt            : 0.2.7
imodels             : None
lightgbm            : 4.1.0
matplotlib          : 3.8.2
networkx            : 3.0
numpy               : 1.24.1
onnxruntime-gpu     : 1.15.1
pandas              : 2.1.4
psutil              : 5.9.5
ray                 : 2.6.3
requests            : 2.31.0
scikit-learn        : 1.3.2
scikit-learn-intelex: None
scipy               : 1.11.4
setuptools          : 69.0.2
skl2onnx            : 1.15.0
tabpfn              : None
torch               : 2.0.1+cpu
tqdm                : 4.66.1
vowpalwabbit        : None
xgboost             : 2.0.2

```

</details>

**Comment by rsj123** [comment]
Works fine here for me
``` python
from autogluon.tabular import TabularDataset, TabularPredictor
data_url = 'https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/'
train_data = TabularDataset(f'{data_url}train.csv')
train_data.head()
label = 'signature'
eval_metric = "log_loss" 
presets = ['medium_quality', {'excluded_model_types':['GBM','XGB','CAT','FASTAI','KNN']}]
predictor = TabularPredictor(label=label,eval_metric=eval_metric)
predictor.fit(train_data,presets=presets)
predictor.compile()  # Note the compilation!  
```
**Installed Versions**
<details>
INSTALLED VERSIONS
------------------
date                   : 2023-12-09
time                   : 12:10:00.118966
python                 : 3.10.12.final.0
OS                     : Linux
OS-release             : 5.15.120+
Version                : #1 SMP Wed Aug 30 11:19:59 UTC 2023
machine                : x86_64
processor              : x86_64
num_cores              : 2
cpu_ram_mb             : 12982.625
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 80233

accelerate             : 0.21.0
async-timeout          : 4.0.3
autogluon              : 1.0.0
autogluon.common       : 1.0.0
autogluon.core         : 1.0.0
autogluon.features     : 1.0.0
autogluon.multimodal   : 1.0.0
autogluon.tabular      : 1.0.0
autogluon.timeseries   : 1.0.0
boto3                  : 1.33.11
catboost               : 1.2.2
defusedxml             : 0.7.1
evaluate               : 0.4.1
fastai                 : 2.7.13
gluonts                : 0.14.3
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.2
joblib                 : 1.3.2
jsonschema             : 4.17.3
lightgbm               : 4.1.0
lightning              : 2.0.9.post0
matplotlib             : 3.7.1
mlforecast             : 0.10.0
networkx               : 3.2.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.23.5
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
orjson                 : 3.9.10
pandas                 : 2.1.4
Pillow                 : 10.0.1
psutil                 : 5.9.5
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 2.0.9.post0
pytorch-metric-learning: 1.7.3
ray                    : 2.6.3
requests               : 2.28.2
scikit-image           : 0.19.3
scikit-learn           : 1.3.2
scikit-learn-intelex   : None
scipy                  : 1.11.4
seqeval                : 1.2.2
setuptools             : 60.2.0
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.0
tabpfn                 : None
tensorboard            : 2.14.1
text-unidecode         : 1.3
timm                   : 0.9.12
torch                  : 2.0.1+cpu
torchmetrics           : 1.1.2
torchvision            : 0.15.2+cpu
tqdm                   : 4.65.2
transformers           : 4.31.0
utilsforecast          : 0.0.10
vowpalwabbit           : None
xgboost                : 2.0.2
</details>

**Comment by andborth** [comment]
Two points here:
1.  In your example, it skipped compilation of NeuralNetTorch, so this isn't a good test case
2. I'm wondering if there is something specific to my datasets.  The AWS AutoGluon team has access to them

**Comment by suzhoum** [comment]
I think I was able to reproduce the problem. Note that when installing `autogluon.tabular` instead of the whole `autogluon` package, only `onnxruntime-gpu` is installed on Linux. We found that installing `onnxruntime` on top of the `onnxruntime-gpu` could solve the problem. There might be some bug associated with `onnxruntime-gpu`. @andborth could you please check and let us know if this helps?

**Comment by suzhoum** [comment]
Fixed with https://github.com/autogluon/autogluon/pull/4536
