### ISSUE TITLE
DDP issue

### ISSUE THREAD

**Issue by vinayakkarande** [autogluon/autogluon#3813]
**Bug Report Checklist**

import pyarrow.parquet as pq
from autogluon.multimodal import MultiModalPredictor
import os
train_data = pq.read_table('features_with_label.parquet').to_pandas()

metric = 'f1'
time_limit = 180
predictor = MultiModalPredictor(label='label', eval_metric=metric)
predictor.fit(train_data, time_limit=time_limit)

**Describe the bug**
I am trying to use MultiModalPredictor to perform classification on combination of text and tabular data. I am running my code on "ml.p3.8xlarge" instance with kernel "conda_pytorch_py310". I am getting below eror 

“Lightning can’t create new processes if CUDA is already initialized. Did you manually call `torch.cuda.*` functions, have moved the model to the device, or allocated memory on the GPU any other way? Please remove any such calls, or change the selected strategy. You will have to restart the Python kernel.” 

**Screenshots / Logs**
[error_logs.txt](https://github.com/autogluon/autogluon/files/13666797/error_logs.txt)

```python
python version = Python 3.10.13
Lightning version = '2.0.9.post0'
autogluon = 2.21
```

**Comment by AnirudhDagar** [comment]
Hi, bringing the offline conversation on the issue here. Can you please share the output of `!nvidia-smi` after you restart your kernel in sagemaker?

**Comment by vinayakkarande** [comment]
Thu Dec 14 00:58:09 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-SXM2-16GB           On  | 00000000:00:1B.0 Off |                    0 |
| N/A   28C    P0              60W / 300W |    389MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2-16GB           On  | 00000000:00:1C.0 Off |                    0 |
| N/A   27C    P0              36W / 300W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2-16GB           On  | 00000000:00:1D.0 Off |                    0 |
| N/A   27C    P0              38W / 300W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2-16GB           On  | 00000000:00:1E.0 Off |                    0 |
| N/A   28C    P0              38W / 300W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    125234      C   ...conda3/envs/pytorch_p310/bin/python      386MiB |
+---------------------------------------------------------------------------------------+

**Comment by shchur** [comment]
This seems to be related to #4131. Closing this issue to keep track of the progress there.
