### ISSUE TITLE
Predictions and targets are expected to have the same shape, but got torch.Size([8, 2]) and torch.Size([8]).

### ISSUE THREAD

**Issue by vinayakkarande** [autogluon/autogluon#3818]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
Predictions and targets are expected to have the same shape, but got torch.Size([8, 2]) and torch.Size([8]).

**To Reproduce**
==========================================

from autogluon.multimodal import MultiModalPredictor
import uuid

metric = 'f1'
time_limit = 3 * 60  # set to larger value in your applications
model_path = f"./tmp/{uuid.uuid4().hex}-automm_ssd_text_non_text"
predictor = MultiModalPredictor(label='label', path=model_path, eval_metric=metric, problem_type="binary")
predictor.fit(train_data, time_limit=time_limit)
==========================================

**Screenshots / Logs**
[error_logs_14thDec2023.txt](https://github.com/autogluon/autogluon/files/13676427/error_logs_14thDec2023.txt)

**Installed Versions**
please check logs for version details

**Comment by vinayakkarande** [comment]
when I remove eval_metric=metric, it runs fine. by default it is using "BinaryAUROC " as validation metric

**Comment by FANGAreNotGnu** [comment]
It's been fixed here: https://github.com/autogluon/autogluon/pull/3822.
The code below works fine
```
import numpy as np
import warnings
import matplotlib.pyplot as plt

warnings.filterwarnings('ignore')
np.random.seed(123)

from autogluon.core.utils.loaders import load_pd

def main():
    train_data = load_pd.load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/train.parquet')
    test_data = load_pd.load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/dev.parquet')
    subsample_size = 1000  # subsample data for faster demo, try setting this to larger values
    train_data = train_data.sample(n=subsample_size, random_state=0)
    train_data.head(10)

    from autogluon.multimodal import MultiModalPredictor
    import uuid
    model_path = f"./tmp/{uuid.uuid4().hex}-automm_sst"
    predictor = MultiModalPredictor(
        label='label', 
        eval_metric='f1', 
        path=model_path,
        problem_type="binary",
    )
    predictor.fit(train_data, time_limit=180)


if __name__ == "__main__":
    main()
```
