### ISSUE TITLE
[BUG] 1.0.0 - timeseries - weighted ensemble only on a few models

### ISSUE THREAD

**Issue by obwohl** [autogluon/autogluon#3819]
autogluon 1.0.0 - timeseries - weighted ensemble
The weighted ensemble component of AutoGluon seems to be utilizing only a subset of the trained models for ensemble weighting, despite a larger pool of models being trained. Specifically, ensemble weights were assigned to 'AutoARIMA', 'AutoETS', 'DeepAR', 'PatchTST', and 'TemporalFusionTransformer', even though the training completed for a wider range of models including 'SeasonalNaive', 'CrostonSBA', 'NPTS', 'DynamicOptimizedTheta', 'RecursiveTabular', 'DirectTabular', among others. This behavior appears inconsistent with the expected functionality of the weighted ensemble, which should consider all trained models.

Expected behavior
The expected behavior is for the weighted ensemble to consider all trained models for ensemble weighting, providing a more comprehensive and potentially accurate combined forecast.

here is the log:
Fitting simple weighted ensemble.
	Ensemble weights: {'AutoARIMA': 0.13, 'AutoETS': 0.36, 'DeepAR': 0.03, 'PatchTST': 0.23, 'TemporalFusionTransformer': 0.25}
	-0.2274       = Validation score (-SQL)
	5.42    s     = Training runtime
	11.35   s     = Validation (prediction) runtime
Training complete. Models trained: ['SeasonalNaive', 'CrostonSBA', 'NPTS', 'AutoETS', 'DynamicOptimizedTheta', 'AutoARIMA', 'RecursiveTabular', 'DirectTabular', 'DeepAR', 'TemporalFusionTransformer', 'PatchTST', 'WeightedEnsemble']
Total runtime: 8076.75 s

Does it mean, the other models were just too bad? Or is it a bug?

**Comment by shchur** [comment]
Hi, this is a feature, not a bug. Ensemble considers all the trained models, but if adding a model does not improve the overall performance, it's not included in the ensemble. This also has the advantage of learning a sparse ensemble, which leads to faster inference speed.

The ensemble weights are learned using greedy forward selection algorithm from [this paper](https://www.cs.cornell.edu/~alexn/papers/shotgun.icml04.revised.rev2.pdf) (called "selection with replacement" in the paper).

**Comment by obwohl** [comment]
Great, Dankeschön. Learned sth. again :)
