### ISSUE TITLE
Support torchvision v0.16.1 and cuda 12.0

### ISSUE THREAD

**Issue by giswqs** [autogluon/autogluon#3827]
Currently, autogluon does not support cuda 12.0 due to the torchvision dependency restricition in autogluon.multimodal: `torchvision >=0.15.0,<0.16.0`. See the discussion in https://github.com/conda-forge/autogluon-feedstock/issues/27

Can augoluton support torchvision v0.16.1? If yes, please bump the version upper bound, making autogluon compatible with cuda 12.0. 

@suzhoum

**Comment by AnirudhDagar** [comment]
fixed in https://github.com/autogluon/autogluon/pull/3982
