### ISSUE TITLE
How is the "score_val" calculated

### ISSUE THREAD

**Issue by jujeonghoo** [autogluon/autogluon#3845]
When I use autogluon for regression (eval_metric='r2'), it generates the "score_val" metric. I would like to ask: 
(1) How is the "score_val" calculated? Is the 5 fold cross validation used? Or is some other method used? 
(2) Where can I get the two y-values used to calculate the "score_val"?
thank you!
![AAA](https://github.com/autogluon/autogluon/assets/155599233/c03f538b-3a79-49ec-b4a0-a551c04e9c52)

**Comment by suziqingCoin** [comment]
#### Have you solved this problem? I'm encountering the same doubt now?
