### ISSUE TITLE
How to read pre v1 FTTransformer weights with v1 autogluon

### ISSUE THREAD

**Issue by yizhexu** [autogluon/autogluon#3847]
## Description
I have pretrained weights obtained using older version of autogluon's FTTransformer implementation (v0.6). Now I would like to load the weights using v1. I tried something basic like the following which worked with older version but cannot load it with v1:

```python

from autogluon.tabular import TabularPredictor, TabularDataset

df_train = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
hyperparameters = {}
hyperparameters['FT_TRANSFORMER'] = {
   "env.per_gpu_batch_size": 128,
   "env.num_workers": 0,
   "env.num_workers_evaluation": 0,
   "optimization.max_epochs": 3,
   'finetune_on': './iter_2k.ckpt',
}
predictor = TabularPredictor(label="class",
                        eval_metric="roc_auc",
                        )
df_train = df_train.dropna(subset=["class"])
predictor.fit(train_data=df_train, hyperparameters=hyperparameters, time_limit=60)
```

It complaints: `'"finetune_on" is not found in the config. You may need to check the overrides. `

**Comment by Innixma** [comment]
@taoyang1122 would be best to answer.

My understanding is that we improved the architecture implementation of FT-Transformer in v1.0 and thus the weights are no longer compatible between v1.0 and prior versions, you would need to pre-train new weights for v1.0.

**Comment by yizhexu** [comment]
Thank you! This solved my issue and now I can load old weights with 

```
hyperparameters['FT_TRANSFORMER'] = {...
   'model.ft_transformer.checkpoint_name': './iter_2k.ckpt',
}
```
