### ISSUE TITLE
Feature Request: Make Deletion of lightning_logs Directory Optional in TimeSeries Models

### ISSUE THREAD

**Issue by obwohl** [autogluon/autogluon#3853]
## Description
The current implementation of AutoGluon's time series models, specifically those using the GluonTS torch backend, automatically deletes the `lightning_logs` directory after each training run. This directory contains logs that are essential for users who utilize TensorBoard to monitor and compare different training sessions. The automatic deletion of these logs makes it difficult to use TensorBoard effectively, as it relies on historical log data for comparison.

## Proposal
I propose a feature for the `timeseries` module where the deletion of the `lightning_logs` directory is made optional. This could be implemented by adding a parameter to the model training functions and the `fit()` method, allowing users to choose whether to preserve the logs. By default, this parameter could be `True` to maintain the current behavior, but when set to `False`, it would keep the logs intact for further analysis with TensorBoard.

## Code
this code is responsible for deletion of the logs:
 if lightning_logs_dir.exists() and lightning_logs_dir.is_dir(): logger.debug(f"Removing lightning_logs directory {lightning_logs_dir}") shutil.rmtree(lightning_logs_dir)

**Comment by shchur** [comment]
This functionality will be available in the next release.
