### ISSUE TITLE
Add RMSLE-metric

### ISSUE THREAD

**Issue by obwohl** [autogluon/autogluon#3878]
## Please add RMSLE-metric

Here is a proposal (this is my my_metrics.py file I am using right now)

import numpy as np
from autogluon.core.metrics import make_scorer

def rmsle_func(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    # Check for non-positive values to avoid log domain error
    if np.any(y_true < 0) or np.any(y_pred < 0):
        raise ValueError("Root Mean Squared Logarithmic Error cannot be computed for negative values.")
    # Compute the Mean Squared Logarithmic Error
    msle = ((np.log(1 + y_true) - np.log(1 + y_pred)) ** 2).mean()
    # Take the square root to get the RMSLE
    return np.sqrt(msle)

RMSLE_scorer = make_scorer(name='root_mean_squared_log_error',
                           score_func=rmsle_func,
                           optimum=0,
                           greater_is_better=False)

**Comment by canerturkmen** [comment]
Assuming the original request referred to the timeseries module, where RMSLE is most used, I believe this issue has now been addressed. Feel free to reopen it otherwise. Thanks for raising this @obwohl !
