### ISSUE TITLE
Timeseries: Random Seed Variability for "high_quality" vs "medium_quality" Presets

### ISSUE THREAD

**Issue by samuel-woerz** [autogluon/autogluon#3896]
Hi,
when experimenting with Autogluon, I noticed that when using the "medium_quality" preset and different random seeds, my scores fluctuate somewhat. But when using the "high_quality" preset and different random seeds, the scores are exactly the same (most of the time). The same holds for the ensemble weights: they fluctuate for "medium_quality", but are the same for "high_quality".

I reproduced this behavior using the [In-Depth Tutorial Notebook](https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-indepth.html) as a starting point: [link to colab notebook with results](https://colab.research.google.com/drive/1-ngYlUZu4m78FXPwIfKWJGt1v8jfQr19#scrollTo=r1-aQzKsLhx3) (runtime ist ~40 minutes on T4) 

I also noticed that this behavior seems to correlate with the inclusion of the TemporalFusionTransformer in the final ensemble.

As I understand it, the only difference between the presets are the models considered for the ensemble. 
Therefore, I have no good explanation for this difference in variability. 
Any chance you could share some insights?
Thanks for your time.

**Comment by canerturkmen** [comment]
Hi @samuel-woerz, thank you for raising this issue! We now merged a fix which should take care of it. I will close this issue for now, feel free to reopen if you find it persists. Thanks!!
