### ISSUE TITLE
[BUG] Document fit_pseudolabel() and fix compatibility with refit_full()

### ISSUE THREAD

**Issue by andborth** [autogluon/autogluon#3897]
**Bug Report Checklist**

- [ x] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

Two issues regarding [fit_pseudolabel](https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.fit_pseudolabel.html):

- Could you please add at least couple sentences sketching out the basic approach that AG Tabular takes when leveraging pseudolabeled data in [the API documentation](https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.fit_pseudolabel.html)?  For instance, how is train_data used and how is pseudo_data used?
- Secondly, there appears to be a bug with the interaction with refit_full().  This doesn't generate an error, but my accuracy metrics show that it completely lose the benefits of the pseudolabels.  Attached please find three scripts which I have run against the dataset "%SC%ProductSafety%RegulatoryEngagement%US_Multiple_BathroomShelves", which the AutoGluon team has access to:

1. minimal_demo_500_labels_best_quality_no_pseudo.ipynb shows baseline performance with 500 ground-truth labels of 
[bug_report.zip](https://github.com/autogluon/autogluon/files/14118032/bug_report.zip)

```
log_loss:0.18833911123873076
roc_auc_score:0.7489790735740716
AUPRC:0.1754345219105115
```
2. minimal_demo_500_labels_best_quality_with_pseudo.ipynb shows the same with the addition of 8824 pseudolabeled labeled rows into which we have introduced a 2% error rate.  With the addition of this data, we now have the following improved metrics:
```
log_loss:0.1609988051772629
roc_auc_score:0.8246199979999895
AUPRC:0.3470127101871933
```
3. On the other hand, minimal_demo_500_labels_best_quality_with_pseudo_with_separate_refit_full.ipynb shows us first using fit_pseudolabel as above and getting the same level of accuracy.  We then call `predictor.refit_full()` and the benefit of the pseudolabeled data completely disappear.  In fact, metrics are worse than the baseline.  Metrics are now:
```
log_loss:0.19120844475255883
roc_auc_score:0.7376429612787436
AUPRC:0.164376187655637
```

**Comment by Innixma** [comment]
Thanks for submitting! We will track and prioritize a fix and doc improvements.
