### ISSUE TITLE
[BUG] TimeSeriesPredictor.info raises exception when called after calling TimeSeriesPredictor.load

### ISSUE THREAD

**Issue by afmkt** [autogluon/autogluon#3899]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [x] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

TimeSeriesPredictor.info raises exception when called after calling TimeSeriesPredictor.load. 

**Expected behavior**

There should not be exception calling info after load and field time_fit_training should contain valid value.

**To Reproduce**

```

import pandas as pd
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
DUMMY_TS_DATAFRAME = TimeSeriesDataFrame.from_data_frame(pd.DataFrame.from_dict({
    'item_id':[1,1,1,1,1,1,1,1,1,1],
    'timestamp':['2022-01-01',
                 '2022-01-02', 
                 '2022-01-03',
                 '2022-01-04',
                 '2022-01-05',
                 '2022-01-06',
                 '2022-01-07',
                 '2022-01-08',
                 '2022-01-09',
                 '2022-01-10'],
    'target':[1,2,4,5,6,8,9,11,22,33]
}))
predictor = TimeSeriesPredictor(path='temp_model_path', prediction_length=2)
predictor.fit(
    train_data=DUMMY_TS_DATAFRAME,
    presets = 'fast_training'
)
predictor.save()
del predictor    
predictor = TimeSeriesPredictor.load('temp_model_path')
predictor.info()
```

**Screenshots / Logs**

This is the exception raised by TimeSeriesPredictor.info
```
Exception has occurred: AttributeError
'TimeSeriesLearner' object has no attribute '_time_fit_training'
  File "E:\code\python\autogluon\timeseries\src\autogluon\timeseries\learner.py", line 212, in get_info
    "time_fit_training": self._time_fit_training,
  File "E:\code\python\autogluon\timeseries\src\autogluon\timeseries\predictor.py", line 949, in info
    return self._learner.get_info(include_model_info=True)
  File "E:\code\python\autogluon\main.py", line 37, in <module>
    predictor.info()
AttributeError: 'TimeSeriesLearner' object has no attribute '_time_fit_training'
```

**Installed Versions**

<details>
OS: Windows 11
anaconda: 23.7.4
autogluon: latest git repo master branch

INSTALLED VERSIONS
------------------
date                   : 2024-02-04
time                   : 09:53:02.506159
python                 : 3.10.13.final.0
OS                     : Windows
OS-release             : 10
Version                : 10.0.22000
machine                : AMD64
processor              : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
num_cores              : 36
cpu_ram_mb             : 130791.765625
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : [15302]
avail_disk_size_mb     : None

accelerate             : 0.21.0
autogluon              : 1.0.1b20240202
autogluon.eda          : 1.0.1b20240202
autogluon.multimodal   : 1.0.1b20240202
autogluon.timeseries   : 1.0.1b20240202
boto3                  : 1.34.33
defusedxml             : 0.7.1
evaluate               : 0.4.1
gluonts                : 0.14.3
ipython                : 8.12.3
ipywidgets             : 8.1.1
jinja2                 : 3.1.2
joblib                 : 1.3.2
jsonschema             : 4.17.3
lightning              : 2.0.9.post0
matplotlib             : 3.6.3
missingno              : 0.5.2
mlforecast             : 0.10.0
networkx               : 3.2.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.26.3
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
openmim                : 0.3.9
orjson                 : 3.9.12
pandas                 : 2.1.4
phik                   : 0.12.4
Pillow                 : 10.2.0
PyMuPDF                : 1.21.1
pyod                   : 1.1.2
pytesseract            : 0.3.10
pytorch-metric-learning: 1.7.3
pytorch_lightning      : 2.0.9.post0
scikit-image           : 0.20.0
scikit-learn           : 1.4.0
scipy                  : 1.12.0
seaborn                : 0.12.2
seqeval                : 1.2.2
shap                   : 0.44.1
statsforecast          : 1.4.0
statsmodels            : 0.14.1
suod                   : 0.0.9
tensorboard            : 2.15.1
text-unidecode         : 1.3
timm                   : 0.9.12
torch                  : 2.0.1+cpu
torchmetrics           : 1.1.2
torchvision            : 0.15.2+cpu
tqdm                   : 4.65.2
transformers           : 4.31.0
utilsforecast          : 0.0.10
yellowbrick            : 1.5

</details>

**Comment by shchur** [comment]
Fixed by #3900.
