### ISSUE TITLE
[BUG] quick_start_coco.ipynb demo fails

### ISSUE THREAD

**Issue by andborth** [autogluon/autogluon#3902]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
I am unable to run [the AutoMM Detection demo](https://auto.gluon.ai/stable/tutorials/multimodal/object_detection/quick_start/quick_start_coco.html) (quick_start_coco).  I've tried in different environments and keep getting an error with being unable to import mmcv.  A demonstration notebook is attached.  Note that this is despite the presence in the script of `!mim install "mmcv==2.1.0"`.  

**Expected behavior**

**To Reproduce**
An example script with the output I saw is attached.  Basically, I can't get the demo to run either on SageMaker Studio Lab or in a SageMaker Notebook instance.
[quick_start_coco.ipynb.zip](https://github.com/autogluon/autogluon/files/14172933/quick_start_coco.ipynb.zip).  

**Screenshots / Logs**

**Installed Versions**

<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

</details>

**Comment by FANGAreNotGnu** [comment]
A kernal restart is required if the package is installed in the notebook. Closing the issue. Feel free to reopen it if restarting the notebook kernel does not help.
