### ISSUE TITLE
[BUG] Unable to work with Autogluon Object Detection

### ISSUE THREAD

**Issue by GDGauravDutta** [autogluon/autogluon#3915]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [x] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
Unable to work with Autogluon in Kaggle env 

**Expected behavior**
Code able to run without any error 

**To Reproduce**
!pip install autogluon

from autogluon.multimodal import MultiModalPredictor

predictor = MultiModalPredictor(label=label_col).fit(
    train_data=train_data,
    time_limit=120
)

OSError                                   Traceback (most recent call last)
Cell In[10], line 1
----> 1 from autogluon.multimodal import MultiModalPredictor
      3 predictor = MultiModalPredictor(label=label_col).fit(
      4     train_data=train_data,
      5     time_limit=120
      6 )

File /opt/conda/lib/python3.10/site-packages/autogluon/multimodal/__init__.py:6
      3 except ImportError:
      4     pass
----> 6 from . import constants, data, learners, models, optimization, predictor, problem_types, utils
      7 from .predictor import MultiModalPredictor
      8 from .utils import download

File /opt/conda/lib/python3.10/site-packages/autogluon/multimodal/data/__init__.py:2
      1 from . import collator, infer_types, randaug, utils
----> 2 from .datamodule import BaseDataModule
      3 from .dataset import BaseDataset
      4 from .dataset_mmlab import MultiImageMixDataset

File /opt/conda/lib/python3.10/site-packages/autogluon/multimodal/data/datamodule.py:4
      1 from typing import Dict, List, Optional, Union
      3 import pandas as pd
----> 4 from lightning.pytorch import LightningDataModule
      5 from torch.utils.data import DataLoader, Dataset
      7 from ..constants import PREDICT, TEST, TRAIN, VALIDATE

File /opt/conda/lib/python3.10/site-packages/lightning/__init__.py:25
     23 from lightning.fabric.fabric import Fabric  # noqa: E402
     24 from lightning.fabric.utilities.seed import seed_everything  # noqa: E402
---> 25 from lightning.pytorch.callbacks import Callback  # noqa: E402
     26 from lightning.pytorch.core import LightningDataModule, LightningModule  # noqa: E402
     27 from lightning.pytorch.trainer import Trainer  # noqa: E402

File /opt/conda/lib/python3.10/site-packages/lightning/pytorch/__init__.py:26
     23     _logger.propagate = False
     25 from lightning.fabric.utilities.seed import seed_everything  # noqa: E402
---> 26 from lightning.pytorch.callbacks import Callback  # noqa: E402
     27 from lightning.pytorch.core import LightningDataModule, LightningModule  # noqa: E402
     28 from lightning.pytorch.trainer import Trainer  # noqa: E402

File /opt/conda/lib/python3.10/site-packages/lightning/pytorch/callbacks/__init__.py:14
      1 # Copyright The Lightning AI team.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from lightning.pytorch.callbacks.batch_size_finder import BatchSizeFinder
     15 from lightning.pytorch.callbacks.callback import Callback
     16 from lightning.pytorch.callbacks.checkpoint import Checkpoint

File /opt/conda/lib/python3.10/site-packages/lightning/pytorch/callbacks/batch_size_finder.py:24
     21 from typing import Optional
     23 import lightning.pytorch as pl
---> 24 from lightning.pytorch.callbacks.callback import Callback
     25 from lightning.pytorch.tuner.batch_size_scaling import _scale_batch_size
     26 from lightning.pytorch.utilities.exceptions import _TunerExitException, MisconfigurationException

File /opt/conda/lib/python3.10/site-packages/lightning/pytorch/callbacks/callback.py:22
     19 from torch.optim import Optimizer
     21 import lightning.pytorch as pl
---> 22 from lightning.pytorch.utilities.types import STEP_OUTPUT
     25 class Callback:
     26     r"""Abstract base class used to build new callbacks.
     27 
     28     Subclass this class and override any of the relevant hooks
     29 
     30     """

File /opt/conda/lib/python3.10/site-packages/lightning/pytorch/utilities/types.py:40
     38 from torch import Tensor
     39 from torch.optim import Optimizer
---> 40 from torchmetrics import Metric
     41 from typing_extensions import NotRequired, Required
     43 from lightning.fabric.utilities.types import _TORCH_LRSCHEDULER, LRScheduler, ProcessGroup, ReduceLROnPlateau

File /opt/conda/lib/python3.10/site-packages/torchmetrics/__init__.py:14
     11 _PACKAGE_ROOT = os.path.dirname(__file__)
     12 _PROJECT_ROOT = os.path.dirname(_PACKAGE_ROOT)
---> 14 from torchmetrics import functional  # noqa: E402
     15 from torchmetrics.aggregation import (  # noqa: E402
     16     CatMetric,
     17     MaxMetric,
   (...)
     22     SumMetric,
     23 )
     24 from torchmetrics.audio._deprecated import _PermutationInvariantTraining as PermutationInvariantTraining  # noqa: E402

File /opt/conda/lib/python3.10/site-packages/torchmetrics/functional/__init__.py:14
      1 # Copyright The Lightning team.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
     15 from torchmetrics.functional.audio._deprecated import _pit_permutate as pit_permutate
     16 from torchmetrics.functional.audio._deprecated import (
     17     _scale_invariant_signal_distortion_ratio as scale_invariant_signal_distortion_ratio,
     18 )

File /opt/conda/lib/python3.10/site-packages/torchmetrics/functional/audio/__init__.py:14
      1 # Copyright The Lightning team.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
     15 from torchmetrics.functional.audio.sdr import (
     16     scale_invariant_signal_distortion_ratio,
     17     signal_distortion_ratio,
     18     source_aggregated_signal_distortion_ratio,
     19 )
     20 from torchmetrics.functional.audio.snr import (
     21     complex_scale_invariant_signal_noise_ratio,
     22     scale_invariant_signal_noise_ratio,
     23     signal_noise_ratio,
     24 )

File /opt/conda/lib/python3.10/site-packages/torchmetrics/functional/audio/pit.py:22
     19 from torch import Tensor
     20 from typing_extensions import Literal
---> 22 from torchmetrics.utilities import rank_zero_warn
     23 from torchmetrics.utilities.imports import _SCIPY_AVAILABLE
     25 # _ps_dict: cache of permutations
     26 # it's necessary to cache it, otherwise it will consume a large amount of time

File /opt/conda/lib/python3.10/site-packages/torchmetrics/utilities/__init__.py:14
      1 # Copyright The Lightning team.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from torchmetrics.utilities.checks import check_forward_full_state_property
     15 from torchmetrics.utilities.distributed import class_reduce, reduce
     16 from torchmetrics.utilities.prints import rank_zero_debug, rank_zero_info, rank_zero_warn

File /opt/conda/lib/python3.10/site-packages/torchmetrics/utilities/checks.py:25
     22 import torch
     23 from torch import Tensor
---> 25 from torchmetrics.metric import Metric
     26 from torchmetrics.utilities.data import select_topk, to_onehot
     27 from torchmetrics.utilities.enums import DataType

File /opt/conda/lib/python3.10/site-packages/torchmetrics/metric.py:30
     27 from torch import Tensor
     28 from torch.nn import Module
---> 30 from torchmetrics.utilities.data import (
     31     _flatten,
     32     _squeeze_if_scalar,
     33     dim_zero_cat,
     34     dim_zero_max,
     35     dim_zero_mean,
     36     dim_zero_min,
     37     dim_zero_sum,
     38 )
     39 from torchmetrics.utilities.distributed import gather_all_tensors
     40 from torchmetrics.utilities.exceptions import TorchMetricsUserError

File /opt/conda/lib/python3.10/site-packages/torchmetrics/utilities/data.py:22
     19 from torch import Tensor
     21 from torchmetrics.utilities.exceptions import TorchMetricsUserWarning
---> 22 from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
     23 from torchmetrics.utilities.prints import rank_zero_warn
     25 METRIC_EPS = 1e-6

File /opt/conda/lib/python3.10/site-packages/torchmetrics/utilities/imports.py:50
     48 _GAMMATONE_AVAILABEL: bool = package_available("gammatone")
     49 _TORCHAUDIO_AVAILABEL: bool = package_available("torchaudio")
---> 50 _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
     51 _SACREBLEU_AVAILABLE: bool = package_available("sacrebleu")
     52 _REGEX_AVAILABLE: bool = package_available("regex")

File /opt/conda/lib/python3.10/site-packages/lightning_utilities/core/imports.py:77, in compare_version(package, op, version, use_base_version)
     68 """Compare package version with some requirements.
     69 
     70 >>> compare_version("torch", operator.ge, "0.1")
   (...)
     74 
     75 """
     76 try:
---> 77     pkg = importlib.import_module(package)
     78 except (ImportError, pkg_resources.DistributionNotFound):
     79     return False

File /opt/conda/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File /opt/conda/lib/python3.10/site-packages/torchaudio/__init__.py:1
----> 1 from . import (  # noqa: F401
      2     _extension,
      3     compliance,
      4     datasets,
      5     functional,
      6     io,
      7     kaldi_io,
      8     models,
      9     pipelines,
     10     sox_effects,
     11     transforms,
     12     utils,
     13 )
     14 from ._backend.common import AudioMetaData  # noqa
     16 try:

File /opt/conda/lib/python3.10/site-packages/torchaudio/_extension/__init__.py:45
     43 _IS_ALIGN_AVAILABLE = False
     44 if _IS_TORCHAUDIO_EXT_AVAILABLE:
---> 45     _load_lib("libtorchaudio")
     47     import torchaudio.lib._torchaudio  # noqa
     49     _check_cuda_version()

File /opt/conda/lib/python3.10/site-packages/torchaudio/_extension/utils.py:64, in _load_lib(lib)
     62 if not path.exists():
     63     return False
---> 64 torch.ops.load_library(path)
     65 torch.classes.load_library(path)
     66 return True

File /opt/conda/lib/python3.10/site-packages/torch/_ops.py:643, in _Ops.load_library(self, path)
    638 path = _utils_internal.resolve_library_path(path)
    639 with dl_open_guard():
    640     # Import the shared library into the process, thus running its
    641     # static (global) initialization code in order to register custom
    642     # operators with the JIT.
--> 643     ctypes.CDLL(path)
    644 self.loaded_libraries.add(path)

File /opt/conda/lib/python3.10/ctypes/__init__.py:374, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371 self._FuncPtr = _FuncPtr
    373 if handle is None:
--> 374     self._handle = _dlopen(self._name, mode)
    375 else:
    376     self._handle = handle

OSError: /opt/conda/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN3c10ltERKNS_6SymIntEi

```python
INSTALLED VERSIONS
------------------
date                   : 2024-02-12
time                   : 18:42:30.368085
python                 : 3.10.13.final.0
OS                     : Linux
OS-release             : 5.15.133+
Version                : #1 SMP Tue Dec 19 13:14:11 UTC 2023
machine                : x86_64
processor              : x86_64
num_cores              : 4
cpu_ram_mb             : 32110.140625
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 19933

accelerate             : 0.21.0
async-timeout          : 4.0.3
autogluon              : 1.0.0
autogluon.common       : 1.0.0
autogluon.core         : 1.0.0
autogluon.features     : 1.0.0
autogluon.multimodal   : 1.0.0
autogluon.tabular      : 1.0.0
autogluon.timeseries   : 1.0.0
boto3                  : 1.26.100
catboost               : 1.2.2
defusedxml             : 0.7.1
evaluate               : 0.4.1
fastai                 : 2.7.13
gluonts                : 0.14.4
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.2
joblib                 : 1.3.2
jsonschema             : 4.17.3
lightgbm               : 4.1.0
lightning              : 2.0.9.post0
matplotlib             : None
mlforecast             : 0.10.0
networkx               : 3.2.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.26.3
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
orjson                 : 3.9.10
pandas                 : 2.1.4
Pillow                 : 10.2.0
psutil                 : 5.9.7
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 2.0.9.post0
pytorch-metric-learning: 1.7.3
ray                    : 2.6.3
requests               : 2.31.0
scikit-image           : 0.20.0
scikit-learn           : 1.4.0
scikit-learn-intelex   : 2024.1.0
scipy                  : 1.11.4
seqeval                : 1.2.2
setuptools             : 69.0.3
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.1
tabpfn                 : None
tensorboard            : 2.15.1
text-unidecode         : 1.3
timm                   : 0.9.12
torch                  : 2.0.1
torchmetrics           : 1.1.2
torchvision            : 0.15.2
tqdm                   : 4.66.1
transformers           : 4.31.0
utilsforecast          : 0.0.10
vowpalwabbit           : 9.9.0
xgboost                : 2.0.3
</details>

**Comment by CO0l-github** [comment]
I faced similar errors in multimodal case, and fixed it by adding `!pip uninstall torchvision torchaudio torchtext -y` before installing autogluon. Notice that in my case the uninstalling after autogluon installed can't fix this problem. Perhaps there's some conflict between kaggle's original torchaudio with autogluon.

**Comment by shchur** [comment]
Assuming that the above comment provides a fix, so closing this issue. Please feel free to re-open.
