### ISSUE TITLE
During inference, multi-GPUs are not used with DDP strategy. Only single GPU is used.

### ISSUE THREAD

**Issue by hohoCode** [autogluon/autogluon#3921]
I have 8 GPUs in a node, with "ddp_find_unused_parameters_true" as the strategy, it can train an AutoMM model with multiple GPUs. 

However, during inference with .predict(), the trained model cannot use multi GPUs for inference. Only 1 GPU is used.

**Comment by cheungdaven** [comment]
@hohoCode Could you provide your script and the environmental setting?  Thanks!

**Comment by FANGAreNotGnu** [comment]
It is a designed behavior, because DDP cannot run twice in a single process. More details and potential solutions are discussed here: https://github.com/autogluon/autogluon/issues/4082.
