### ISSUE TITLE
[BUG] [Errno 2] No such file or directory: c:\\...\\prediction-net-state.pt 

### ISSUE THREAD

**Issue by gianluca-coletta** [autogluon/autogluon#3939]
Hi everyone! 

I'm trying to do an HPO on a DeepAR model but when I try to execute the code, I will show below, I get the following **error**: 

`[Errno 2] No such file or directory: c:\\ (path that i chose in predictor object) \\models\\DeepAR\\9fdbe678\\W0\\gluon_ts\\prediction-net-state.pt `

The code that returns the error: 

```
predictor.fit(
    train_data,
    hyperparameters={
        "DeepAR": {
            "hidden_size": space.Int(20, 100),
            "dropout_rate": space.Categorical(0.1, 0.3),
        },
    },
    hyperparameter_tune_kwargs="auto",
)
```

`AutuGluon Version: 1.0.0`

Why do I get this error? How can I solve it? Thanks to everyone who can help me :)

**Comment by shchur** [comment]
Hi @gianluca-coletta, can you please let me know if this answer applies to your issue? https://github.com/autogluon/autogluon/issues/3892#issuecomment-1953877639

**Comment by gianluca-coletta** [comment]
> Hi @gianluca-coletta, can you please let me know if this answer applies to your issue? [#3892 (comment)](https://github.com/autogluon/autogluon/issues/3892#issuecomment-1953877639)

Yes, i have the same problem. But my path is this: 

`c:\\Users\\colig\\OneDrive\\Desktop\\Università\\Tesi_Magistrale\\Code\\test_prediction\\models\\DeepAR\\9fdbe678\\W0\\gluon_ts\\prediction-net-state.pt`

So, as you can see, it doesn't contain spaces. I saw that you suggested removing the spaces

**Comment by shchur** [comment]
Could you try running the script outside of the `OneDrive` directory, e.g., in `c:\\Users\\colig`? The problem could be related either to some weird `OneDrive` behavior (#3892 encountered the problem in OneDrive as well) or, alternatively, the `à` character in the path.

**Comment by gianluca-coletta** [comment]
I try with another path, outside of the OneDrive and  I no longer have any errors. 
Thanks for the help ( @shchur )
