### ISSUE TITLE
[BUG] AutoMM HPO tests crash on scikit-learn upgrade.

### ISSUE THREAD

**Issue by prateekdesai04** [autogluon/autogluon#3949]
`scikit-learn` released a new version `1.4.1post1` which causes all tests under AutoMM `test_hpo.py` to fail.
The reason is because this interferes with ray, a sample run using `1.4.1post1` is shown here: https://github.com/autogluon/autogluon/actions/runs/8011831095/job/21885981252
The temporary fix that we have for now is to cap the version of `scikit-learn`: https://github.com/autogluon/autogluon/pull/3947

**Comment by suzhoum** [comment]
Resolved by https://github.com/autogluon/autogluon/pull/4420
