### ISSUE TITLE
Is Conv-LoRA available?

### ISSUE THREAD

**Issue by iamjinchen** [autogluon/autogluon#3983]
## Problem 
 I've read this paper(Conv-LoRA), whose code links to this repository's directory. However, I noticed that this directory has been deleted already. Is Conv-LoRA still available in this repository? Where can I find the code? Many thanks for your reply.

## References
- Conv-LoRA https://arxiv.org/pdf/2401.17868.pdf
- Missing directory: https://github.com/autogluon/autogluon/tree/master/examples/automm/Conv-LoRA

**Comment by Innixma** [comment]
Hi @iamjinchen, the Conv-LoRA method is available in the latest AutoGluon release 1.1: https://github.com/autogluon/autogluon/tree/master/examples/automm/Conv-LoRA
