### ISSUE TITLE
How to use `TimeSeriesPredictor` predict all future time series values one by one (or by window)

### ISSUE THREAD

**Issue by eromoe** [autogluon/autogluon#3988]
Current `TimeSeriesPredictor` only produce one horizon forward predictions after last time of test_data for each item.

I see docs mention below models,
```
DirectTabularModel
- Predict all future time series values simultaneously using TabularPredictor from AutoGluon-Tabular.

RecursiveTabularModel
- Predict future time series values one by one using TabularPredictor from AutoGluon-Tabular.
```
But, how can I use `TimeSeriesPredictor` produce predictions for every time in test_data ?

**Comment by shchur** [comment]
Hi, thank you for the question. Currently, all models are implemented in such a way that they generate a probabilistic forecast exactly `prediction_length` many steps into the future (consisting of mean + quantile forecasts). Most models cannot sample trajectories autoregressively, so we cannot really unroll their forecasts beyond `prediction_length`. As a workaround, you could write a wrapper that feeds in the point forecast for the first window to the predictor as if it were the true observation, but that will make the probabilistic forecasts completely unreliable beyond the first window.

**Comment by shchur** [comment]
Closing this issue, assuming that the comment above answers it. Please feel free to re-open if this is not the case.
