### ISSUE TITLE
[timeseries] DirectTabular & RecursiveTabular models fail with "unique_id" not exist[BUG]

### ISSUE THREAD

**Issue by luochixq** [autogluon/autogluon#4001]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
DirectTabular & RecursiveTabular fail during timeseries models training.

**Expected behavior**
Other timeseres odels train normally.

**To Reproduce**
import pandas as pd
import numpy as np
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
predictor = TimeSeriesPredictor(
    prediction_length = 1,
    path="Vol_price_D_T",
    target="Todate",
    eval_metric="RMSE",
    quantile_levels=None,
    known_covariates_names=["No_Transaction"],
    # freq="D",
)

predictor.fit(
    train_data,
    # df_irr,
    presets="best_quality",
    time_limit=None,
    num_val_windows= 5,
    hyperparameters={
        "DeepAR":{},
        "DLinear":{},
        "PatchTST":{},
        "SimpleFeedForward":{},       
        "RecursiveTabular":{},
        "DirectTabular":{},
        "AutoETS":{},
        "WaveNet":{},
        # "AutoCES":{},
        "Theta":{},
        "WaveNet":{},
        # "TemporalFusionTransformer":{},
    },
    )
Error message
Training timeseries model RecursiveTabular. 
	Warning: Exception caused RecursiveTabular to fail during training... Skipping this model.
	"['unique_id'] not found in axis"
Training timeseries model DirectTabular. 
	Warning: Exception caused DirectTabular to fail during training... Skipping this model.
	"['unique_id'] not found in axis"

**Installed Versions**
AutoGluon v1.0

**Comment by shchur** [comment]
Hi, thank you for reporting the problem. Can you please provide a snippet of your data (just 1 row with `train_data.head()` and `train_data.static_features.head()` is enough) & list the package versions with `from autogluon.core.utils import show_versions; show_versions()`?

**Comment by luochixq** [comment]
hi, thanks for quick respond. below is the info according to your mail.&nbsp;





no static_features is set up in the models.


INSTALLED VERSIONS ------------------ date                   : 2024-03-24 time                   : 10:32:35.503240 python                 : 3.9.18.final.0 OS                     : Windows OS-release             : 10 Version                : 10.0.22621 machine                : AMD64 processor              : Intel64 Family 6 Model 151 Stepping 2, GenuineIntel num_cores              : 12 cpu_ram_mb             : 65291.734375 cuda version           : None num_gpus               : 1 gpu_ram_mb             : [11487] avail_disk_size_mb     : None accelerate             : 0.21.0 async-timeout          : 4.0.3 autogluon              : 1.0.0 autogluon.common       : 1.0.0 autogluon.core         : 1.0.0 autogluon.features     : 1.0.0 autogluon.multimodal   : 1.0.0 autogluon.tabular      : 1.0.0 autogluon.timeseries   : 1.0.0 boto3                  : 1.33.6 catboost               : 1.2.2 defusedxml             : 0.7.1 evaluate               : 0.4.1 fastai                 : 2.7.13 gluonts                : 0.14.2 hyperopt               : 0.2.7 imodels                : None jinja2                 : 3.1.2 joblib                 : 1.3.2 jsonschema             : 4.20.0 lightgbm               : 4.1.0 lightning              : 2.0.9.post0 matplotlib             : 3.7.2 mlforecast             : 0.10.0 networkx               : 3.2 nlpaug                 : 1.1.11 nltk                   : 3.8.1 nptyping               : 2.4.1 numpy                  : 1.22.4 nvidia-ml-py3          : 7.352.0 omegaconf              : 2.2.3 onnxruntime-gpu        : None openmim                : 0.3.9 orjson                 : 3.9.10 pandas                 : 1.5.3 Pillow                 : 10.1.0 psutil                 : 5.9.6 PyMuPDF                : None pytesseract            : 0.3.10 pytorch-lightning      : 2.0.9.post0 pytorch-metric-learning: 1.7.3 ray                    : 2.6.3 requests               : 2.31.0 scikit-image           : 0.20.0 scikit-learn           : 1.3.0 scikit-learn-intelex   : None scipy                  : 1.9.1 seqeval                : 1.2.2 setuptools             : 68.2.2 skl2onnx               : None statsforecast          : 1.4.0 statsmodels            : 0.14.0 tabpfn                 : None tensorboard            : 2.15.0 text-unidecode         : 1.3 timm                   : 0.9.12 torch                  : 2.0.1+cu118 torchmetrics           : 1.1.2 torchvision            : 0.15.2+cu118 tqdm                   : 4.66.1 transformers           : 4.31.0 utilsforecast          : 0.0.10 vowpalwabbit           : None xgboost                : 2.0.2




Luochi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "autogluon/autogluon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月24日(星期天) 凌晨1:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [autogluon/autogluon] [timeseries] DirectTabular &amp; RecursiveTabular models fail with "unique_id" not exist[BUG] (Issue #4001)





 
Hi, thank you for reporting the problem. Can you please provide a snippet of your data (just 1 row with train_data.head(1) and train_data.static_features.head(1) is enough) &amp; list the package versions with from autogluon.core.utils import show_versions; show_versions()?

**Comment by shchur** [comment]
Can you please show the output of `train_data.head(1)` as well as the full predictor log?

Also, here is a potentially related issue #3958.

**Comment by luochixq** [comment]
hi，train_data;head(3) is as below:
                        换手率     当日涨跌幅     涨跌幅_5    涨跌幅_10    涨跌幅_20    涨跌幅_30    涨跌幅_60   涨跌幅_120   涨跌幅_250      RSI_6  换手率_ma_3  换手率_std_3  换手率加权动量_3  涨跌幅_成交量系数_3      动量_3  量价相关系数_3    Bias_3       CCI_3           J       DIF       DEA      MACD        WR_3  换手率_ma_5  换手率_std_5  换手率加权动量_5  涨跌幅_成交量系数_5      动量_5  量价相关系数_5    Bias_5       CCI_5        WR_5  换手率_ma_10  换手率_std_10  换手率加权动量_10  涨跌幅_成交量系数_10     动量_10  量价相关系数_10   Bias_10      CCI_10       WR_10  换手率_ma_60  换手率_std_60  换手率加权动量_60  涨跌幅_成交量系数_60     动量_60  量价相关系数_60   Bias_60     CCI_60      WR_60       大户买入占比       中户买入占比       散户卖出占比      大中户买入占比  大户资金买入额std_5  中户资金买入额std_5  散户资金卖出额std_5  大户净流入成交额占比_5  中户净流入成交额占比_5  散户净流入成交额占比_5  大户资金买入额std_10  中户资金买入额std_10  散户资金卖出额std_10  大户净流入成交额占比_10  中户净流入成交额占比_10  散户净流入成交额占比_10  大户资金买入额std_20  中户资金买入额std_20  散户资金卖出额std_20  大户净流入成交额占比_20  中户净流入成交额占比_20  散户净流入成交额占比_20  大户资金买入额std_60  中户资金买入额std_60  散户资金卖出额std_60  大户净流入成交额占比_60  中户净流入成交额占比_60  散户净流入成交额占比_60  ***@***.***_单季     ROE单季    毛利率_单季   上方筹码集中度   上方筹码偏离度     筹码偏离度       IQR  iqr_10日标准差  ***@***.***_单季_中性  归母净利润_中性化_分位数  ROE单季_二级行业分位数  ROE单季_分位数  毛利率_行业分位数  上方筹码集中度_分位数  上方筹码偏离度_分位数    上方筹码空间 No_Transaction item_id  timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     sz301559 2024-03-16  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.000000  0.000000   0.000000   0.000000     0.000000  0.000000  0.000000  0.000000    0.000000    0.000000  0.000000  0.000000  0.000000    0.000000  0.000000   0.000000   0.000000     0.000000  0.000000  0.000000  0.000000    0.000000    0.000000   0.000000    0.000000    0.000000      0.000000  0.000000   0.000000  0.000000    0.000000    0.000000   0.000000    0.000000    0.000000      0.000000  0.000000   0.000000  0.000000   0.000000   0.000000     0.000000     0.000000     0.000000     0.000000  0.000000e+00  0.000000e+00  0.000000e+00      0.000000      0.000000      0.000000   0.000000e+00   0.000000e+00   0.000000e+00       0.000000       0.000000       0.000000   0.000000e+00   0.000000e+00   0.000000e+00       0.000000       0.000000       0.000000   0.000000e+00   0.000000e+00   0.000000e+00       0.000000       0.000000       0.000000        0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000    0.000000           0.000000e+00       0.000000       0.000000   0.000000   0.000000     0.000000     0.000000  0.000000              1          2024-03-17  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.000000  0.000000   0.000000   0.000000     0.000000  0.000000  0.000000  0.000000    0.000000    0.000000  0.000000  0.000000  0.000000    0.000000  0.000000   0.000000   0.000000     0.000000  0.000000  0.000000  0.000000    0.000000    0.000000   0.000000    0.000000    0.000000      0.000000  0.000000   0.000000  0.000000    0.000000    0.000000   0.000000    0.000000    0.000000      0.000000  0.000000   0.000000  0.000000   0.000000   0.000000     0.000000     0.000000     0.000000     0.000000  0.000000e+00  0.000000e+00  0.000000e+00      0.000000      0.000000      0.000000   0.000000e+00   0.000000e+00   0.000000e+00       0.000000       0.000000       0.000000   0.000000e+00   0.000000e+00   0.000000e+00       0.000000       0.000000       0.000000   0.000000e+00   0.000000e+00   0.000000e+00       0.000000       0.000000       0.000000        0.000000e+00  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000    0.000000           0.000000e+00       0.000000       0.000000   0.000000   0.000000     0.000000     0.000000  0.000000              1          2024-03-18  0.033106  0.011820  0.019048  0.034441  0.076053 -0.009832 -0.089362 -0.255907 -0.255907  71.627514  0.023169   0.008761   3.769037    -0.420432  0.018441  0.839119  0.013418   88.775510  104.553887  0.035144 -0.082484  0.235257    3.571429  0.023655   0.006850   6.209309    -0.420432  0.019048  0.776545  0.014699   99.217527    3.571429   0.024422    0.004948    7.090858     -0.420432  0.034441   0.262413  0.024107  136.170213    2.173913   0.029679    0.009559  -19.927363     -0.420432 -0.089362  -0.082066 -0.011081 -11.207937  39.728353  1767.961869  4273.975108  4067.258089  6041.936977  2.494788e+10  5.065326e+10  3.742622e+10   -332.758433    275.656788    184.246792   1.938956e+10   3.970383e+10   2.943945e+10    -240.203399     191.535323      56.645214   1.975697e+10   6.173047e+10   5.050967e+10    -365.645934     128.122939     281.474517   3.236724e+10   6.518027e+10   6.389451e+10    -343.319922     -10.602442     379.402452        1.283287e+08  0.025411  0.139216  0.042933  0.108793 -0.019362  0.214043    0.014205           4.798246e+07       0.648078       0.261682   0.266844   0.271028     0.827255     0.628141  1.455396              0


&nbsp;full predictor log? do you mean this?


Warning: path already exists! This predictor may overwrite an existing predictor! path="Combo_D_T" Beginning AutoGluon training... AutoGluon will save models to 'Combo_D_T' =================== System Info =================== AutoGluon Version:  1.0.0 Python Version:     3.9.18 Operating System:   Windows Platform Machine:   AMD64 Platform Version:   10.0.22621 CPU Count:          12 GPU Count:          1 Memory Avail:       13.13 GB / 63.76 GB (20.6%) Disk Space Avail:   967.07 GB / 1906.96 GB (50.7%) =================================================== Setting presets to: best_quality Fitting with arguments: {'enable_ensemble': True,  'eval_metric': RMSE,  'hyperparameters': {'AutoETS': {},                      'DLinear': {},                      'DeepAR': {},                      'DirectTabular': {},                      'PatchTST': {},                      'RecursiveTabular': {},                      'SimpleFeedForward': {},                      'Theta': {},                      'WaveNet': {}},  'known_covariates_names': ['No_Transaction'],  'num_val_windows': 5,  'prediction_length': 1,  'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],  'random_seed': 123,  'refit_every_n_windows': 1,  'refit_full': False,  'target': '当日涨跌幅',  'verbosity': 2} Inferred time series frequency: 'D' Provided train_data has 12195713 rows, 5286 time series. Median time series length is 3004 (min=138, max=3004).  Provided dataset contains following columns: 	target:           '当日涨跌幅' 	known covariates: ['No_Transaction'] 	past covariates:  ['换手率', '涨跌幅_5', '涨跌幅_10', '涨跌幅_20', '涨跌幅_30', '涨跌幅_60', '涨跌幅_120', '涨跌幅_250', 'RSI_6', '换手率_ma_3', '换手率_std_3', '换手率加权动量_3', '涨跌幅_成交量系数_3', '动量_3', '量价相关系数_3', 'Bias_3', 'CCI_3', 'J', 'DIF', 'DEA', 'MACD', 'WR_3', '换手率_ma_5', '换手率_std_5', '换手率加权动量_5', '涨跌幅_成交量系数_5', '动量_5', '量价相关系数_5', 'Bias_5', 'CCI_5', 'WR_5', '换手率_ma_10', '换手率_std_10', '换手率加权动量_10', '涨跌幅_成交量系数_10', '动量_10', '量价相关系数_10', 'Bias_10', 'CCI_10', 'WR_10', '换手率_ma_60', '换手率_std_60', '换手率加权动量_60', '涨跌幅_成交量系数_60', '动量_60', '量价相关系数_60', 'Bias_60', 'CCI_60', 'WR_60', '大户买入占比', '中户买入占比', '散户卖出占比', '大中户买入占比', '大户资金买入额std_5', '中户资金买入额std_5', '散户资金卖出额std_5', '大户净流入成交额占比_5', '中户净流入成交额占比_5', '散户净流入成交额占比_5', '大户资金买入额std_10', '中户资金买入额std_10', '散户资金卖出额std_10', '大户净流入成交额占比_10', '中户净流入成交额占比_10', '散户净流入成交额占比_10', '大户资金买入额std_20', '中户资金买入额std_20', '散户资金卖出额std_20', '大户净流入成交额占比_20', '中户净流入成交额占比_20', '散户净流入成交额占比_20', '大户资金买入额std_60', '中户资金买入额std_60', '散户资金卖出额std_60', '大户净流入成交额占比_60', '中户净流入成交额占比_60', '散户净流入成交额占比_60', ***@***.***_单季', 'ROE单季', '毛利率_单季', '上方筹码集中度', '上方筹码偏离度', '筹码偏离度', 'IQR', 'iqr_10日标准差', ***@***.***_单季_中性', '归母净利润_中性化_分位数', 'ROE单季_二级行业分位数', 'ROE单季_分位数', '毛利率_行业分位数', '上方筹码集中度_分位数', '上方筹码偏离度_分位数', '上方筹码空间'] AutoGluon will gauge predictive performance using evaluation metric: 'RMSE' 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value. =================================================== Starting training. Start time is 2024-03-26 08:34:15 Models that will be trained: ['AutoETS', 'Theta', 'RecursiveTabular', 'DirectTabular', 'DeepAR', 'WaveNet', 'PatchTST', 'SimpleFeedForward', 'DLinear'] Training timeseries model AutoETS.  	-0.0175       = Validation score (-RMSE) 	3064.45 s     = Training runtime 	493.07  s     = Validation (prediction) runtime Training timeseries model Theta.  	-0.0203       = Validation score (-RMSE) 	991.66  s     = Training runtime 	200.13  s     = Validation (prediction) runtime Training timeseries model RecursiveTabular.  	Warning: Exception caused RecursiveTabular to fail during training... Skipping this model. 	"['unique_id'] not found in axis" Training timeseries model DirectTabular.  	Warning: Exception caused DirectTabular to fail during training... Skipping this model. 	"['unique_id'] not found in axis" Training timeseries model DeepAR.  	-0.0171       = Validation score (-RMSE) 	644.24  s     = Training runtime 	13.87   s     = Validation (prediction) runtime Training timeseries model WaveNet.  	-0.0206       = Validation score (-RMSE) 	407.21  s     = Training runtime 	13.52   s     = Validation (prediction) runtime Training timeseries model PatchTST.  	-0.0166       = Validation score (-RMSE) 	446.40  s     = Training runtime 	11.72   s     = Validation (prediction) runtime Training timeseries model SimpleFeedForward.  	-0.0167       = Validation score (-RMSE) 	290.63  s     = Training runtime 	11.84   s     = Validation (prediction) runtime Training timeseries model DLinear.  	-0.0176       = Validation score (-RMSE) 	236.82  s     = Training runtime 	11.68   s     = Validation (prediction) runtime Fitting simple weighted ensemble. 	Ensemble weights: {'PatchTST': 1.0} 	-0.0166       = Validation score (-RMSE) 	172.68  s     = Training runtime 	11.72   s     = Validation (prediction) runtime Training complete. Models trained: ['AutoETS', 'Theta', 'DeepAR', 'WaveNet', 'PatchTST', 'SimpleFeedForward', 'DLinear', 'WeightedEnsemble'] Total runtime: 7163.40 s Best model: PatchTST Best model score: -0.0166
tks!




Luochi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "autogluon/autogluon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月25日(星期一) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [autogluon/autogluon] [timeseries] DirectTabular &amp; RecursiveTabular models fail with "unique_id" not exist[BUG] (Issue #4001)





 
Can you please show the output of train_data.head(1) as well as the full predictor log?
 
Also, here is a potentially related issue #3958.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

**Comment by gwdekker** [comment]
FWIW I encounter the same issue.

**Comment by luochixq** [comment]
Hi, I have sort it out by reinstall the enviorment and AG. thanks!
&nbsp;


Luochi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oleksandr ***@***.***&gt;; 
发送时间: 2024年5月7日(星期二) 下午5:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [autogluon/autogluon] [timeseries] DirectTabular &amp; RecursiveTabular models fail with &quot;unique_id&quot; not exist[BUG] (Issue #4001)














 
Hi @gwdekker, thank you for reporting the problem and I'm sorry for a late response.
 
Unfortunately, I was unable to reproduce the bug based on the description in the thread so far. Could you please share more information about the problem that you encountered (full predictor log and, ideally, a snippet of your data)?

**Comment by shchur** [comment]
Closing this issue assuming the bug doesn't appear in the latest AG version (v1.1). Please feel free to re-open if this is not the case.
