### ISSUE TITLE
Support manual assignment of cross-validation folds

### ISSUE THREAD

**Issue by dluks** [autogluon/autogluon#4014]
## Description
This feature request pertains to the `tabular` module.

For some types of data, such as geospatial data, spatial autocorrelation can confound the evaluation of k-fold cross-validation. In cases like these, spatially aware fold assignment is especially useful. With this in mind, it would greatly enhance the confidence in `TabularPredictor` performance results if custom fold assignment IDs could be manually pre-assigned and then passed to `TabularPredictor.fit()`.

## References
- [Spatial validation reveals poor predictive performance of large-scale ecological mapping models](https://www.nature.com/articles/s41467-020-18321-y)
- [Estimating the prediction performance of spatial models via spatial k-fold cross validation](https://doi.org/10.1080/13658816.2017.1346255)
- [Cross-validation strategy impacts the performance and interpretation of machine learning models](https://journals.ametsoc.org/view/journals/aies/aop/AIES-D-23-0026.1/AIES-D-23-0026.1.xml)
- [Spatially autocorrelated training and validation samples inflate performance assessment of convolutional neural networks](https://www.sciencedirect.com/science/article/pii/S2667393222000072)
- [Assessing and improving the transferability of current global spatial prediction models](https://onlinelibrary.wiley.com/doi/abs/10.1111/geb.13635)
- [blockCV: an R package for generating spatially or environmentally separated folds for k-fold cross-validation of species distribution models](https://www.biorxiv.org/content/10.1101/357798v1)
- [SamComber/spacv: Spatial cross-validation in Python.](https://github.com/SamComber/spacv)

**Comment by Innixma** [comment]
Thanks for creating an issue and providing a variety of links!

We do support manual group assignment. Refer to the `groups` parameter in https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.html.

Can you try this logic and see if it satisfies your needs?

If not, could you provide a reproducible code example that uses a dataset where such manual assignment leads to an improved result? We can use this example to test potential solutions.

**Comment by alberto-jj** [comment]
Hi, following up on this.

Could you please confirm if the mentioned "groups" parameter in the TabularPredictor class could be used to perform a typical K-fold cross-validation (or stratified CV) where the AutoGluon models will be trained in all groups/folds except by one (the validation fold)?

Below is a random df with a "Fold" column that I want to use to define the training/validation splits used for the internal bagging of AutoGluon.

Is my interpretation correct? or am I misunderstanding the documentation?
Thanks a lot for your reply!


```
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from autogluon.tabular import TabularDataset, TabularPredictor

# Generate random data
np.random.seed(42)
data_size = 300
feature1 = np.random.normal(loc=0, scale=1, size=data_size)
feature2 = np.random.normal(loc=5, scale=2, size=data_size)
groups = np.random.choice(['Group_A', 'Group_B', 'Group_C'], size=data_size)

# Create DataFrame
df = pd.DataFrame({
    'Feature1': feature1,
    'Feature2': feature2,
    'Group': groups
})

# Apply Stratified K-Fold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
fold_column = np.zeros(data_size, dtype=int)

for fold, (train_index, test_index) in enumerate(skf.split(df, df['Group'])):
    fold_column[test_index] = fold

#Add the Fold column (to be used as "groups" in TabularPredictor)
df['Fold'] = fold_column

#AutoGluon using user-defined stratified K-fold CV
train_data = df
label = 'Group'
groups = 'Fold'
save_path = 'data/test_folds_automl/'  

predictor = TabularPredictor(label=label, path=save_path, groups=groups, eval_metric='balanced_accuracy',
                             sample_weight='auto_weight').fit(train_data, time_limit=80, auto_stack=True)


```

**Comment by Innixma** [comment]
Thanks @dluks! We don't support getting std dev of folds yet, but it is something we plan to add in an upcoming release.
For the NeuralNetwork issue, a reproducible example in a new ticket would be great if you find the time so we can take a closer look. I don't expect this to be the case, and am surprised this would cause an issue. It is probably the time limit.

Regarding the GPU hanging, this is fixed in pre-release / mainline and will be part of the next release.

@alberto-jj Yes should work.
