### ISSUE TITLE
Support Getting Coefficient from Linear Regression 

### ISSUE THREAD

**Issue by geniusjenny** [autogluon/autogluon#4017]
Description

I have checked the documentation on all methods and could not find a way to get coefficients from TabularPredictor if the TabularPredictor is using linear regression. Can any methods/functions do the job? 

Reference:
https://auto.gluon.ai/0.1.0/api/autogluon.task.html#autogluon.tabular.TabularPredictor.fit

**Comment by shchur** [comment]
Hi @geniusjenny, here is how you can load a specific model: https://github.com/autogluon/autogluon/issues/586. You can them access the LR weights via the `coef_` attribute (see https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html). 

Closing this issue for now in favor of #4237 that is more general.
