### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by mabdulker** [autogluon/autogluon#4046]
## Description
I have recently migrated codebase to python3.12 and was sad to see that autogluon does not yet work on 3.12. Is support for for python3.12 planned for the near future?

**Comment by mabdulker** [comment]
I attempted to build from source with minimal changes using https://github.com/autogluon/autogluon/pull/3190 for inspiration. Everything works apart from Ray installation, turns out they are still [yet to roll out support for pytnon3.12](https://github.com/ray-project/ray/issues/40211)

**Comment by Innixma** [comment]
Thanks for creating the issue for us to track @mabdulker!

We have been waiting for our dependencies to slowly add support for Python 3.12. We will keep it on our radar, however we are mostly waiting for Ray to add 3.12 support. If Ray adds support for 3.12, let us know and we will start a deeper dive.

**Comment by MarvinGe** [comment]
Hi everyone,
saw the issue here and as ray has a new version out, wanted to let you know.
With 2.31.0 ray supports python 3.12. The release is still an alpha release as of 5 days ago.
Information comes from @can-anyscale in [https://github.com/ray-project/ray/issues/45904#issuecomment-2192785158_]

**Comment by nadavramot1** [comment]
Hi all,
Just updating that as of yesterday ray released 2.32.0 which offers 3.12 alpha support

**Comment by Innixma** [comment]
Great to hear that ray has released alpha support! We will monitor this and see if we can adopt it into our next release to add Python 3.12 support.

**Comment by nicolaerosia** [comment]
@mabdulker if you have bandwidth, can you please prepare a PR? I see `ray` was bumped to `2.33.0`

**Comment by yaniv92648** [comment]
The latest autogluon still doesn't support python 3.12

**Comment by BwL1289** [comment]
Also interested

**Comment by Innixma** [comment]
Providing an update: Python 3.12 is top of our priority list for the next release: AutoGluon v1.2, planned for release in November.

**Comment by tonyhoo** [comment]
Thanks to @suzhoum, Python 3.12 support has been added in this [PR](https://github.com/autogluon/autogluon/pull/4536). Look for it in AutoGluon v1.2 later this month! 🚀
