### ISSUE TITLE
Add an explanation of requirements for data input in TimeSeriesPredictor.leaderboard()

### ISSUE THREAD

**Issue by lleiou** [autogluon/autogluon#4050]
### Describe the issue linked to the documentation

Hello, 

Thanks for the great library that you built! I'm relatively new to AutoGluon Time Series and recently we ran into an issue while running `predictor.leaderboard()` on a `test_data`, by reading [the source code](https://github.com/autogluon/autogluon/blob/master/timeseries/src/autogluon/timeseries/predictor.py#L1216) we noticed that it is required the number of timesteps in the data input to this function must be more than `prediction_length` value, I think this is an important information that needs to be mentioned in the documentation both [here](https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-quick-start.html#evaluating-the-performance-of-different-models) and [here](https://auto.gluon.ai/stable/api/autogluon.timeseries.TimeSeriesPredictor.leaderboard.html#autogluon.timeseries.TimeSeriesPredictor.leaderboard), and additionally I'm also wondering if you could explain the reason for such requirement and why can't `test_data` have exactly `prediction_length` number of timesteps? 

Thanks in advance!

### Suggest a potential alternative/fix

Add a note to `data` variable saying something like below and explain why there is such requirement
> *Please make sure that data includes both historic and future data, and that all time series have length > `prediction_length` (at least `prediction_length `+ 1)*

Thank you!

**Comment by shchur** [comment]
Thank you, this is a great idea! I have opened a PR with the suggested changes #4054

**Comment by lleiou** [comment]
Thanks a lot!
