### ISSUE TITLE
TimeSeriesDataFrame.convert_frequency SLOW !

### ISSUE THREAD

**Issue by shchur** [autogluon/autogluon#4060]
### Discussed in https://github.com/autogluon/autogluon/discussions/4058

<div type='discussions-op-text'>

<sup>Originally posted by **raedbsili1991** April  7, 2024</sup>
Hello, 

I am working with irregular data with that I want to convert to monthly data set using the convert_frequency("M", agg_numeric = "sum"). 
Here is an exemple of what look like my TimeSeriesDataFrame 

![image](https://github.com/autogluon/autogluon/assets/31764213/9be49b21-9f0e-408a-9be1-493f1c674c14)

I wanted to infer the "Monthly" frequency before starting forecasting. 
However, the execution is "infintesily" slow! it never ended. 

I also tried to replicate the https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-indepth.html but it the convert_frequency() is also so slow! 

[requirements.txt](https://github.com/autogluon/autogluon/files/14899071/requirements.txt) 

Why is this happening ? 
</div>

**Comment by raedbsili1991** [comment]
Hi @shchur , Appreciate your reactivity, Thank you.  

Here is the version output: 

![image](https://github.com/autogluon/autogluon/assets/31764213/08d1649a-b855-46a2-ad7f-cc1c1278e6eb)
![image](https://github.com/autogluon/autogluon/assets/31764213/9416fb68-0d75-4073-ad86-91fff1b952a5)

Regarding the execution of the code, it stills never-ending slow 

![image](https://github.com/autogluon/autogluon/assets/31764213/20856195-7ff7-4266-bab2-363ca689f7bc)

**Comment by shchur** [comment]
Thanks @raedbsili1991, it seems that in your case the parallel processes created by `joblib` get stuck for some reason. Can you please try upgrading joblib to a newer version (v1.1 seems to be quite old). 
```
pip install -U joblib
```
Alternatively, could you try disabling multiprocessing for `convert_frequency` with
```python
df_irregular.convert_frequency(freq="D", num_cpus=1)
```

**Comment by shchur** [comment]
I assume that the above fix addressed the issue. Please feel free to re-open if this is not the case.
