### ISSUE TITLE
[BUG]cannot import name 'ModelMetaclass' from 'pydantic.main'

### ISSUE THREAD

**Issue by Hemonn** [autogluon/autogluon#4067]
![微信截图_20240409170658](https://github.com/autogluon/autogluon/assets/95368530/8022d8be-4428-49b8-9e76-2c8aefe4a690)

**Comment by shchur** [comment]
The bug seems to be related to pytorch-lightning and some dependency conflicts. Please see https://stackoverflow.com/questions/76647518/how-to-fix-error-cannot-import-name-modelmetaclass-from-pydantic-main for a fix.

**Comment by Hemonn** [comment]
您发给我的信件已经收到，阅读后回复您。This is an automatic reply, confirming that your e-mail was received. Thank you.
