### ISSUE TITLE
[BUG]ValueError: Model Dlinear is not supported yet.

### ISSUE THREAD

**Issue by isCopyman** [autogluon/autogluon#4095]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
ValueError: Model Dlinear is not supported yet.

**Expected behavior**

**To Reproduce**

**Installed Versions**

gluonts                   0.14.4
autogluon                 1.0.0
autogluon.common          1.0.0
autogluon.core            1.0.0
autogluon.features        1.0.0
autogluon.multimodal      1.0.0
autogluon.tabular         1.0.0
autogluon.timeseries      1.0.0
Python 3.10.14 

</details>

**Comment by isCopyman** [comment]
```
predictor = TimeSeriesPredictor(
    quantile_levels=None,
    prediction_length=prediction_length,
    eval_metric="RMSE",
    freq="15T",
    path=f"{station}-{prediction_length}_ahead-15min/" + pd.Timestamp.now().strftime("%Y_%m_%d_%H_%M_%S"),
    known_covariates_names=known_covariates_name,
    target="power",
)
predictor.fit(
    train_data,
    # presets="best_quality",
    hyperparameters={
      "DlinearModel": {}
   },
    num_val_windows=3,
    refit_every_n_windows=1,
    refit_full=True,
)
```

**Comment by shchur** [comment]
Hi @isCopyman, there is a problem with the capitalization, it should be `DLinear`, not `Dlinear` (see https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-model-zoo.html#autogluon.timeseries.models.DLinearModel for model names)
