### ISSUE TITLE
Object detection support for Torch 2.2

### ISSUE THREAD

**Issue by tonyhoo** [autogluon/autogluon#4126]
## Description
Currently, Multimodal has compatibility issues with mmcv and mmdet in object detection use cases under Torch 2.2. For the supported versions of Torch and Cuda, consult [this](https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-with-pip) guide. Our required action steps include:
* Updating our notebooks and tutorials to guide users through proper setup for object detection under the Torch 2.2 update.
* Adjusting our CICD to reflect these changes.

## References
Please see the [failure details](https://github.com/autogluon/autogluon/actions/runs/8790245479/job/24121990532) for additional information.

**Comment by prateekdesai04** [comment]
@tonyhoo CICD has been adjusted, updated the batch images to use torch 2.2, it is being used in the current CI.
PR for base image change is here: https://github.com/autogluon/autogluon/pull/4123/files#diff-0d8e2186c2607cbd9df799c7b7f0da33d2dfb56c1927d44a5fc1ad984a77d6c9

**Comment by tonyhoo** [comment]
One interesting observation is that the docs are built fine with torch 2.2 at [here](https://auto.gluon.ai/dev/tutorials/multimodal/object_detection/quick_start/quick_start_coco.html)

**Comment by FANGAreNotGnu** [comment]
Add installation instruction (downgrade torch to 2.1.0) in https://github.com/autogluon/autogluon/pull/4447.

**Comment by tonyhoo** [comment]
Issue should be resolved as part this https://github.com/autogluon/autogluon/pull/4612
