### ISSUE TITLE
Model Chronos is not supported yet.

### ISSUE THREAD

**Issue by luochixq** [autogluon/autogluon#4134]
Upgrade to v1.1.0, try to test Chonos, but failed with the msg as title. 
predictor.fit(
    train_data,

    presets="best_quality",
    time_limit=None,
    num_val_windows= 5,
    hyperparameters={

        'Chronos':{'model_path': 'base'},

    },
    
    )

**Comment by canerturkmen** [comment]
Hi @luochixq. I do not get this error with a fresh install of Autogluon v1.1. Could you maybe give a full reproducable example including 1/ your operating system and environment, 2/ steps you took to install Autogluon 1.1 and 3/ the full code including how you initialize the dataset and predictor?

Also, might help to check:
```
from autogluon.timeseries import __version__; print(__version__)
```

**Comment by luochixq** [comment]
hi, today I reinstall autogluon 1.1.0, it has been successfully installed. but it can not recognize my GPU, which work normally in verion 1.0.0. 
it shows as :Starting training. Start time is 2024-04-26 15:07:28
Models that will be trained: ['Chronos[base]']
Training timeseries model Chronos[base]. 
	Warning: Exception caused Chronos[base] to fail during training... Skipping this model.
	Chronos[base]\W0 requires a GPU to run, but no GPU was detected. Please make sure that you are using a computer with a CUDA-compatible GPU and `import torch; torch.cuda.is_available()` returns `True`.
Not fitting ensemble as no models were successfully trained.
Training complete. Models trained: []
Total runtime: 11.76 s
Trainer has no fit models that can predict.

My system is Windows -Conda - GPU, and I have followed the install instructions to install forge mamba, pytorch and cuda.

pls let me know how to sort this out. tks
