### ISSUE TITLE
Chronos problem

### ISSUE THREAD

**Issue by luochixq** [autogluon/autogluon#4146]
Installed fresh version 1.1.0  and tried to test Chronos, but got problem as followings:

Beginning AutoGluon training...
AutoGluon will save models to 'Vol_price_D_0'
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.14
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.22621
CPU Count:          12
GPU Count:          1
Memory Avail:       46.55 GB / 63.76 GB (73.0%)
Disk Space Avail:   700.60 GB / 1906.96 GB (36.7%)
===================================================
Setting presets to: best_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': RMSE,
 'hyperparameters': {'AutoCES': {}, 'Chronos': {'model_path': 'base'}},
 'known_covariates_names': [],
 'num_val_windows': 5,
 'prediction_length': 1,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'Growth',
 'verbosity': 2}

Inferred time series frequency: 'D'
Provided train_data has 12360854 rows, 5295 time series. Median time series length is 3035 (min=140, max=3035). 
AutoGluon will gauge predictive performance using evaluation metric: 'RMSE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2024-04-26 17:45:56
Models that will be trained: ['Chronos[base]', 'AutoCES']
Training timeseries model Chronos[base]. 
	Warning: Exception caused Chronos[base] to fail during training... Skipping this model.
	We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like amazon/chronos-t5-base is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

how to deal with this? thanks!

**Comment by drmanhatin** [comment]
I'm dealing with the same problem. How did you fix this?

**Comment by luochixq** [comment]
del the current AG, python, and enviornment, and reinstall everything ...:)&nbsp;


Luochi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月7日(星期二) 晚上11:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [autogluon/autogluon] Chronos problem (Issue #4146)














 
I'm dealing with the same problem. How did you fix this?
