### ISSUE TITLE
I have already downloaded the CUDA version of torch, why does it automatically uninstall my CUDA when I pip install autogluon and turn it into the CPU version?

### ISSUE THREAD

**Issue by psv666** [autogluon/autogluon#4151]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

![bug](https://github.com/autogluon/autogluon/assets/150513104/2ce6cf4a-4caf-4f11-8f80-e23c4dfab99d)

**Expected behavior**

**To Reproduce**

**Screenshots / Logs**

**Installed Versions**

<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

</details>

**Comment by shchur** [comment]
Hi @psv666, thank you for opening the issue. The latest version of AutoGluon requires PyTorch v2.1, while your previous installation was v2.0. Therefore, the old PyTorch version (2.0) needs to be uninstalled before the new version (2.1) required by AutoGluon can be installed.
