### ISSUE TITLE
[timeseries] Show model hyperparmeters in the leaderboard

### ISSUE THREAD

**Issue by shchur** [autogluon/autogluon#4152]
## Description
It should be possible to view the model hyperparameters after HPO is performed. For example, this can be done via the `TimeSeriesPredictor.leaderboard` method, similar to how `TabularPredictor.leaderboard` returns such information when `extra_info=True`.

**Comment by shchur** [comment]
Here is a workaround that can be used in v1.1 to get this information 
```python
def get_hyperparameters(model_name: str) -> dict:
    model = predictor._trainer.load_model(model_name)
    if hasattr(model, "most_recent_model"):
        model = model.most_recent_model
    return model._get_params()

leaderboard = predictor.leaderboard()
leaderboard["hyperparameters"] = [get_hyperparameters(m) for m in leaderboard["model"]]
```

**Comment by dany4142** [comment]
Can we please add it as a feature?

**Comment by shchur** [comment]
@dany4142 we will try to include it in the v1.2 release.

**Comment by shchur** [comment]
Completed in #4481
