### ISSUE TITLE
Failed to load cask: libomp.rb

### ISSUE THREAD

**Issue by LeonTing1010** [autogluon/autogluon#4181]
$ brew install libomp.rb
Error: Failed to load cask: libomp.rb
Cask 'libomp' is unreadable: wrong constant name #<Class:0x00000001150a5b48>
Warning: Treating libomp.rb as a formula.
==> Fetching libomp
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libomp-11.1.0.big_sur.bottle.tar.gz
curl: (22) The requested URL returned error: 404

Warning: Bottle missing, falling back to the default domain...
==> Downloading https://ghcr.io/v2/homebrew/core/libomp/manifests/11.1.0
Already downloaded: /Users/leo/Library/Caches/Homebrew/downloads/d07c72aee9e97441cb0e3a5ea764f8acae989318597336359b6e111c3f4c44b1--libomp-11.1.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libomp/blobs/sha256:ec279162f0062c675ea96251801a99c19c3b82f395f1598ae2f31cd4cbd9a963
############################################################################################################################################################################## 100.0%
Warning: libomp 18.1.5 is available and more recent than version 11.1.0.
==> Pouring libomp--11.1.0.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/libomp/11.1.0: 9 files, 1.4MB
==> Running `brew cleanup libomp`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/leo/Library/Caches/Homebrew/libomp--11.1.0... (467.3KB)

**Comment by Innixma** [comment]
Also, please provide details on system

**Comment by shchur** [comment]
@LeonTing1010 I assume that the solution provided by Nick fixed the problem, so closing the issue for now. Please feel free to re-open if that's not the case.
