### ISSUE TITLE
About training Conv-LoRA on semantic segmentation datasets

### ISSUE THREAD

**Issue by zhengyuan-xie** [autogluon/autogluon#4206]
Hi, thanks for your great work! I wonder whether conv-lora can be trained on semantic segmentation datasets such as VOC or ADE20K? Do I need to change some hyper-parameters like the number of mask tokens?

**Comment by cheungdaven** [comment]
Hi @Harry-zzh, could you answer this question? Thank you!

**Comment by Harry-zzh** [comment]
Yes, you can try increasing the number of mask tokens to a larger number, such as 100. This is because the number of mask tokens for an image in some datasets may exceed our default setting.

**Comment by zhengyuan-xie** [comment]
Thanks for your reply!
