### ISSUE TITLE
[tabular] Parallel Model Training

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#4215]
Resolved by #4606 

Related: #4213 

We should add support for parallel model training via ray that goes beyond the currently implemented parallel fold model fitting and parallel HPO.

Given a portfolio of 100 models, we should be able to train multiple of them at the same time if we have sufficient resources.

This should also be extended to work with a distributed cluster.

#### Current logic:

```
for model in portfolio:
    models.append(fit_model(model))
```

Code that does this in mainline: https://github.com/autogluon/autogluon/blob/7b782df424da4a232d3c2c33ff4eb4bd2a25dcdc/core/src/autogluon/core/trainer/abstract_trainer.py#L2478-L2504

#### Proposed logic:

```
# Need smart logic to determine how to schedule and how much resources to give each model
models = ray_parallel(portfolio)
```

**Comment by jmakov** [comment]
Ray Tune offers distributed HPO, also Optuna.
