### ISSUE TITLE
How does TabularPredictor handle new categorical values in test data?

### ISSUE THREAD

**Issue by gymoon10** [autogluon/autogluon#4226]
Hi, I'm GooYoung Moon from LG Electronics. While trying to train and test a model using TabularPredictor, I had a question and thus leaving this issue. 

I would like to know how the TabularPredictor's  .predict method internally handles a case where a categorical variable that did not appear in the training data appears in the test data.  Of course, even if a categorical variable value that was not used in the training data appears in the test data, there was no error in executing .predict and .evaluate_predictions, but I want to know how it responds internally.

Thanks for your hard work.

**Comment by Innixma** [comment]
New categories are converted to NaN and handled separately per model. In some, for instance, they are mapped to first category (category 0), such as in RandomForest and ExtraTrees. Some methods have their own special NaN category handling, such as LightGBM.

[Category conversion source code](https://github.com/autogluon/autogluon/blob/master/features/src/autogluon/features/generators/category.py).
