### ISSUE TITLE
Error occur while using kaggle notebook

### ISSUE THREAD

**Issue by EXEDENN** [autogluon/autogluon#4241]
![image](https://github.com/autogluon/autogluon/assets/101499960/2e3762c1-66cd-4d6c-ae22-80543b7ba2dc)
The folder "aiohttp-3.9.5.dist-info" is already in this path :\opt\.conda\envs\myenv\Lib\site-packages\aiohttp-3.9.5.dist-info
I tried re-install anaconda, miniconda and install anaconda in macbook, but it doesn't work. Could anyone help me to fix this issue?

**Comment by EXEDENN** [comment]
Python: 3.11
Pip: 23.3.1

**Comment by Innixma** [comment]
@EXEDENN could you share the kaggle notebook link so we can reproduce?

**Comment by shchur** [comment]
@EXEDENN It seems that this comment provides a fix https://github.com/autogluon/autogluon/issues/3918#issuecomment-2180260480. Please feel free to re-open the issue if this not the case
