### ISSUE TITLE
[BUG]During the training process with AutoGluon, if some parameter contributions are greater than 1, this usually indicates what?

### ISSUE THREAD

**Issue by Yun-Tianming** [autogluon/autogluon#4274]
![image](https://github.com/autogluon/autogluon/assets/80634739/c3b93e34-c921-4b7f-95e7-866ee326e841)

**Comment by Innixma** [comment]
This is the amount that your eval_metric score drops if the feature is removed. Negative values mean the score increases by removing the feature.

**Comment by Yun-Tianming** [comment]
Thanks! I have learned a lot from "<SHAP with AutoGluon-Tabular Diabetes regression.ipynb>". However, I have one more question: Why are my evaluation results negative values? I thought they were supposed to be positive.
![image](https://github.com/autogluon/autogluon/assets/80634739/79a69edd-b3af-4131-b65b-4ab400927adb)
