### ISSUE TITLE
The train of Conv-LoRA

### ISSUE THREAD

**Issue by wang-ziqi993495** [autogluon/autogluon#4296]
Hi, thanks for your great work! 
In the run semantic_segmentation file, when trained with COD10K (camouflaged object detection dataset), no train.csv file is displayed, May I ask whether I need to generate this file by myself or just run the prepares-_semantic_segmentation_datasets file?

**Comment by wang-ziqi993495** [comment]
I feel that the prepare file is a function of unzipping the datasets, so I would like to ask if there is a csv file of COD10K and other data sets that can be shared? Thank you very much.
![image](https://github.com/autogluon/autogluon/assets/70625052/500b34f6-4c6a-4dd3-b655-019ec9d271ef)

**Comment by Harry-zzh** [comment]
Hi, please run the prepare_semantic_segmentation_datasets.py script. It will download and unzip the dataset zip file, which contains the CSV files for training, validation, and testing.

**Comment by wang-ziqi993495** [comment]
> Hi, please run the prepare_semantic_segmentation_datasets.py script. It will download and unzip the dataset zip file, which contains the CSV files for training, validation, and testing.

Thank you！
