### ISSUE TITLE
Logging of tuning data size in timeseries predictor incorrectly logs train data size [BUG]

### ISSUE THREAD

**Issue by ivandochev** [autogluon/autogluon#4297]
Line 715 in timeseries/predictor.py:

            logger.info(f"Provided tuning_data has {self._get_dataset_stats(train_data)}")

Should be:

            logger.info(f"Provided tuning_data has {self._get_dataset_stats(***tuning_data***)}")

It seems a small thing, but I when I was looking at the logs I was really unsure if it is a logging issue, or my train data is then actually wrongly used for tuning...

**Comment by shchur** [comment]
Nice catch, thanks! I've submitted a PR to fix this #4299.
