### ISSUE TITLE
Seeking a list of (evaluation) metrics supported

### ISSUE THREAD

**Issue by yuxuan-z19** [autogluon/autogluon#4305]
### Describe the issue linked to the documentation

I wish to record some metrics, for example, `"roc_auc"`, while `MultimodalPredictor` is fitting. Apart from this metric mentioned in the tutorial, I'm seeking a list showing other metrics supported in the tutorials (and their corresponding `str`). Lots of thanks!

### Suggest a potential alternative/fix

Add a list of metrics supported in the docs or cheatsheets

**Comment by Zjianglin** [comment]
same request.  @yuxuan-z19 @jaheba  Do you  have any idea about getting the eval_metrics during the `fit` execution for each CV of every model?

**Comment by Zjianglin** [comment]
@yuxuan-z19  It seems the `TabularPredictor.predict_proba_oof` function can return every `oof` predicted probability of every record of train data. It should be able to compare the `y_label` of `train` data with the `positive_class` oof probability of `TabularPredictor.predict_proba_oof` to get the `ROC` and `AUC`.

Here is my codes:
```

lbmps = predictorx.class_labels_internal_map
train_oof_p = predictorx.predict_proba_oof(model='WeightedEnsemble_L3')
print(train_oof_p)
print(train_oof_p['active'].values)
y_true = [lbmps[trainx.loc[yx, label]] for yx in train_oof_p.index]

y_pred_pos = train_oof_p['active'].values  # `active` is  positive_class in my data
fpr, tpr, thresholds = metrics.roc_curve(y_true, y_pred_pos, pos_label=1)
roc_auc = metrics.auc(fpr, tpr)
display = metrics.RocCurveDisplay(fpr=fpr, tpr=tpr, roc_auc=roc_auc,
                                  estimator_name='{}_{}'.format(modelx, 'WeightedEnsemble_L3'))
display.plot()
plt.show()
```

**Comment by yuxuan-z19** [comment]
Updated: one could refer to the [predictor API](https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.html#autogluon.tabular.TabularPredictor) and the [forecasting metrics](https://auto.gluon.ai/stable/tutorials/timeseries/forecasting-metrics.html#) for more about the metrics available
