### ISSUE TITLE
Error during TabularPredictor's `predict_proba`

### ISSUE THREAD

**Issue by ArijitSinghEDA** [autogluon/autogluon#4314]
I am using `TabularPredictor` for a classification problem. I am using the method `TabularPredictor.predict`, which throws the error:

```
OSError: libgomp.so.1: cannot open shared object file: No such file or directory
```

On further reading the traceback, the problem starts when it internally calls `predict_proba`.
The problem exists even after installing the `libgomp` library on Linux.

The predict method works fine in case of regression problems.

I am using `autogluon==0.8.2`

**Comment by shchur** [comment]
Hi @ArijitSinghEDA, this could be related to LightGBM installation on Mac. I would recommend to re-install autogluon following the instructions for your platform here: https://auto.gluon.ai/stable/install.html.

**Comment by Innixma** [comment]
@ArijitSinghEDA Let us know if following the instructions shared by @shchur resolved the problem. Alternatively, please upgrade to the latest AutoGluon release and open a new GitHub issue with a minimally reproducible code example and stack trace.

**Comment by ArijitSinghEDA** [comment]
@shchur @Innixma Thank you for taking out your time for this issue.

I was running this on a Linux system, so I suppose it cannot be the issue @shchur mentioned, but this problem stopped on its own. Everything is running fine now.

Will try switching to the latest version to avoid this issue.
