### ISSUE TITLE
update to sklearn 1.5.1

### ISSUE THREAD

**Issue by leonardorhojas** [autogluon/autogluon#4331]
Hi team, there is a posibility to update this dependency to the latest `1.5.1` If need I can contribute, but I have not seen any discussion about update it.

https://github.com/autogluon/autogluon/blob/af5ced1937cda95984d111eece6783318badd2ee/core/src/autogluon/core/_setup_utils.py#L22

I'm tryng to address: https://security.snyk.io/package/pip/scikit-learn/1.4.2 in a project wher I'm using this library.

Thanks!

**Comment by Innixma** [comment]
Thanks for creating a GitHub issue! We will target scikit-learn 1.5.1 support for our next minor release (v1.2)

**Comment by leonardorhojas** [comment]
Thank you @Innixma  for your prompt response and for adding the update to the 1.2 Release milestone. I appreciate the efforts of the team in addressing the dependency update.

Would it be possible to share an expected timeline for the v1.2 release? This information would be very helpful for planning purposes in my project.

Thanks again for your hard work!

Best regards,

**Comment by Innixma** [comment]
Hi @leonardorhojas, we currently don't have an exact timeline, but you can expect it is likely we would release 1.2 in late September.

Note that AutoGluon v1.1.1 might already work with the newest sklearn release, but it is something you would have to test on your end to see if it does, in case you want to unblock yourself in your project before our release.

**Comment by prateekdesai04** [comment]
Closing as fix is available on mainline or in the upcoming 1.2 release
