### ISSUE TITLE
Add support of PyTorch 2.4

### ISSUE THREAD

**Issue by tonyhoo** [autogluon/autogluon#4348]
## Description
The recent release of [PyTorch 2.4](https://pytorch.org/blog/pytorch2-4/) necessitates an update for AutoGluon compatibility.

**Comment by tonyhoo** [comment]
fastai currently doesn't support torch 2.4, cut a [PR](https://github.com/fastai/fastai/pull/4040) for its update

**Comment by Innixma** [comment]
Added in 1.2 release
