### ISSUE TITLE
TabularPredictor and the default value of log_to_file

### ISSUE THREAD

**Issue by crossxwill** [autogluon/autogluon#4377]
### Describe the issue linked to the documentation

The class definition of `autogluon.tabular.TabularPredictor` shows that `log_to_file` is set to `False` by default. However, later in the API documentation, it shows that the default is set to `True`:

```
log_to_file (bool, default = True) – Whether to save the logs into a file for later reference
```

https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.html

### Suggest a potential alternative/fix

Change the API documentation for the class `autogluon.tabular.TabularPredictor` to show the actual default setting:

```
log_to_file (bool, default = False) – Whether to save the logs into a file for later reference
```

**Comment by Innixma** [comment]
Thanks for the issue @crossxwill! The docstring has been updated in #4399
