### ISSUE TITLE
What does "gluon" mean?

### ISSUE THREAD

**Issue by skim2257** [autogluon/autogluon#4378]
Came up in a team meeting while chatting about you guys and we'd love to know what your name means!

**Comment by Innixma** [comment]
Gluon is a subatomic particle (https://en.wikipedia.org/wiki/Gluon)

It is the name used for the pre-cursor packages `GluonCV` and `GluonNLP`. `AutoGluon` was originally intended to wrap `GluonCV` and `GluonNLP`. AutoGluon is no longer using GluonCV and GluonNLP, as it has become its own distinct project, however the name has remained.

As for why `GluonCV` and `GluonNLP` chose `Gluon` for their name, funnily enough, I don't know.
