### ISSUE TITLE
Disable bagging and Enable stacking

### ISSUE THREAD

**Issue by crossxwill** [autogluon/autogluon#4408]
The following parameter combination returns an error:

```python
custom_hyperparameters = get_hyperparameter_config('zeroshot')

custom_preset = {'auto_stack': False, 'dynamic_stacking': False,
                'hyperparameters':custom_hyperparameters, 'refit_full': False,
                'set_best_to_refit_full': False, 'save_bag_folds': False,
                'num_bag_folds': 0, 'num_stack_levels': 3}
```

If bagging is disabled (`num_bag_folds=0`), then `num_stack_levels` must be set to 0.

I want a feature where bagging is disabled (to improve training time), but the user can set `num_stack_levels` > 0.

**Comment by Innixma** [comment]
This is not something we intend to support. Bagging is required to obtain good performance with multi-layer stacking. Without bagging, multi-layer stacking will be very bad. If you want fast training time, don't do multi-layer stacking.
