### ISSUE TITLE
[BUG] Pandas 2.1-->2.2 upgrade on MacOS (not Ubuntu) causes autogluon.timeseries.TimeSeriesDataFrame `astype` return type change, causing error during `predictor.fit`

### ISSUE THREAD

**Issue by colehawkins** [autogluon/autogluon#4418]
**Bug Report Checklist**

- [ X] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ X] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

Pandas 2.1-->2.2 upgrade causes a change in AG-TS TimeSeriesDataFrame `astype` method return type in at least one instance on MacOS (but not Ubuntu).

Therefore [this line](https://github.com/autogluon/autogluon/blob/b13eab6632dc29e309b8d8520a0a4dcff666e49e/timeseries/src/autogluon/timeseries/predictor.py#L296) returns an unexpected `pd.DataFrame` datatype which has no `freq` attribute, causing an error when `df.freq` is accessed in the rest of the function.

**Expected behavior**

Same behavior on pandas versions 2.1 and 2.2 on MacOS.

**To Reproduce**

Run the following script on MacOS with latest AG-TS installed. My OS version is `14.6.1 (23G93)`, no M1 chip.

```python
import autogluon.timeseries
import pandas as pd

data = [{"timestamp": pd.Timestamp(10), "item_id":"a", "target": 1}]

df = pd.DataFrame(data)
time_series_df = autogluon.timeseries.TimeSeriesDataFrame.from_data_frame(df)
print(type(time_series_df),type(time_series_df.astype({"target": "float64"})))

# on MacOS local with pandas 2.1
# <class 'autogluon.timeseries.dataset.ts_dataframe.TimeSeriesDataFrame'> <class 'autogluon.timeseries.dataset.ts_dataframe.TimeSeriesDataFrame'>

# on MacOS local with pandas 2.2
# <class 'autogluon.timeseries.dataset.ts_dataframe.TimeSeriesDataFrame'> <class 'pandas.core.frame.DataFrame'>

# on Ubuntu EC2 machine with pandas 2.1 or 2.2
# <class 'autogluon.timeseries.dataset.ts_dataframe.TimeSeriesDataFrame'> <class 'autogluon.timeseries.dataset.ts_dataframe.TimeSeriesDataFrame'>

```

**Comment by shchur** [comment]
Thanks a lot for reporting this problem! This seems to be the underlying issue that also caused #4337

**Comment by shchur** [comment]
I couldn't reproduce this locally on a M1 Mac with Python 3.11 & pandas-2.2.3, unfortunately. 

I attempted the following change [here](https://github.com/autogluon/autogluon/pull/4566/files#diff-0eaa2842673843776db8a88d92a7d60b8d8676a3d29a8edd5731673f3f2c4625R296), hope that this resolves the issue. I don't have access to a non-M1 mac so I cannot be 100% sure that this fixes the problem though.

Feel free to re-open the issue if you find the problem still persists, or if you find alternative solutions.
