### ISSUE TITLE
[BUG] !mim install "mmcv==2.1.0" not working/installing #Multimodal

### ISSUE THREAD

**Issue by allandclive** [autogluon/autogluon#4421]
![brave_screenshot_colab research google com (1)](https://github.com/user-attachments/assets/832f3209-359a-4f8a-bd56-220cb71958e2)
![brave_screenshot_colab research google com](https://github.com/user-attachments/assets/03146441-9bd6-4333-a500-0519c3f6578d)

**Comment by FANGAreNotGnu** [comment]
Hi @allandclive, could you provide the complete error message?

**Comment by allandclive** [comment]
> Hi @allandclive, could you provide the complete error message?
I have tried this object detection tutorial on both colab and kaggle, it gets stuck in endless "installation of mmcv"

https://colab.research.google.com/github/autogluon/autogluon/blob/stable/docs/tutorials/multimodal/object_detection/advanced/finetune_coco.ipynb#scrollTo=f83f7cb0

**Comment by FANGAreNotGnu** [comment]
For google Colab this works: 
```
!pip install autogluon.multimodal
!pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0
!pip install "mmcv==2.1.0" -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/index.html
!pip install "mmdet==3.2.0"
```

**Comment by FANGAreNotGnu** [comment]
Update the tutorial in https://github.com/autogluon/autogluon/pull/4447.
Closing the issue. Feel free to reopen it if the problem still exists.
