### ISSUE TITLE
Add LogLoss to the default hyperparameters.

### ISSUE THREAD

**Issue by crossxwill** [autogluon/autogluon#4429]
## Description
Add log loss criterion to the default hyperparameters for RF and XT.

## Proposed additions

```python
{
	'RF': [{'criterion': 'log_loss', 'ag_args': {'name_suffix': 'LogLoss', 'problem_types': ['binary', 'multiclass']}}],
	'XT': [{'criterion': 'log_loss', 'ag_args': {'name_suffix': 'LogLoss', 'problem_types': ['binary', 'multiclass']}}]
}


```

**Comment by Innixma** [comment]
Thanks for the suggestion! We plan to investigate these options more thoroughly in a follow-up study using TabRepo. For now I will close this issue.
