### ISSUE TITLE
Exception caused NeuralNetFastAI to fail during training (tabular)

### ISSUE THREAD

**Issue by jmren168** [autogluon/autogluon#4467]
When I create an envirnment via 

`pip install autogluon.tabular==1.0.0`

and run my code, the following exception occured

```
autogluon.core.trainer.abstract_trainer - ERROR - 	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
autogluon.core.trainer.abstract_trainer - ERROR - 		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.0.0`. 
```

Is it necessary to install fastai when I create environment?

**Comment by rahulrocksn** [comment]
Hey, 
I would suggest use this to install it. This would install the fastai dependencies for AutoGluon

pip install autogluon.tabular[fastai]==1.0.0

**Comment by jmren168** [comment]
Hi @Innixma 
We do not use fastai (as a base model) during training and we want to minimize the disk space of installing autgluon, so fastai is not installed.
Is there any way to ignore this warning? Many thanks.

**Comment by Innixma** [comment]
@jmren168 you can specify `excluded_models=["FASTAI"]` in the fit call to skip the warning and not fit the model.

**Comment by jmren168** [comment]
@Innixma 
Thanks for the help. I tried excluded_model_types=['FASTAI'] and it works.
