### ISSUE TITLE
use in pyspark

### ISSUE THREAD

**Issue by hhk123** [autogluon/autogluon#4486]
## Description

from autogluon.tabular import TabularPredictor
can TabularPredictor use spark engine to deal with big data?

**Comment by Innixma** [comment]
Hi @hhk123. Currently we do not support using PySpark in AutoGluon. However, you can preprocess your data with PySpark, convert it to a pandas DataFrame, and then pass it into AutoGluon. For now I am going to close this issue as integrating PySpark into AutoGluon would be a very large effort which we don't intend to do unless there are many users requesting it.
