### ISSUE TITLE
timestamp column is millisecond but not date

### ISSUE THREAD

**Issue by zhaowei0315** [autogluon/autogluon#4499]
Hello Expert,
    in my dataset, the timestamp column is millisecond but not date. how can I initiate TimeSeriesDataFrame?

BR,

**Comment by birdhouses** [comment]
You can use Pandas to convert your dataset to millisecond datetimes.

This is however, not related to Autogluon. 

But here's roughly how you could do it:

```
// Load your dataset into a pandas dataframe
import pandas as pd

df = pd.DataFrame(data)

df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')

```

For more info:
https://pandas.pydata.org/docs/user_guide/timeseries.html
https://docs.python.org/3/library/datetime.html#timedelta-objects
https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html#pandas-to-datetime

**Comment by zhaowei0315** [comment]
> You can use Pandas to convert your dataset to millisecond datetimes.
> 
> This is however, not related to Autogluon.
> 
> But here's roughly how you could do it:
> 
> ```
> // Load your dataset into a pandas dataframe
> import pandas as pd
> 
> df = pd.DataFrame(data)
> 
> df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
> ```
> 
> For more info: https://pandas.pydata.org/docs/user_guide/timeseries.html https://docs.python.org/3/library/datetime.html#timedelta-objects https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html#pandas-to-datetime

Many thanks, it works.
