### ISSUE TITLE
How to visualize the structure of a trained model and obtain its corresponding parameters ?

### ISSUE THREAD

**Issue by Dexterssssss** [autogluon/autogluon#4510]
AutoGluon is such a great tool, especially its automated multi-model training capability. I've been trying to visualize the structure of trained models and obtain the parameters of each layer over the past few days. After reviewing the official documentation and browsing numerous websites, I still haven't found a solution. Does anyone have a good method?

**Comment by Innixma** [comment]
Can you clarify which module you are referring to? For example: tabular, timeseries, multimodal

**Comment by Dexterssssss** [comment]
multimodal

**Comment by cheungdaven** [comment]
Hi @Dexterssssss, you can try to print predictor._learner._model to get the structures of the model.

**Comment by Dexterssssss** [comment]
@cheungdaven 
I will try this very soon. Thanks a lot.

**Comment by Dexterssssss** [comment]
@cheungdaven It works. Thanks so much.
