### ISSUE TITLE
[MultiModal] Suppressing NLTK Download Messages Not Working in beginner_text Tutorial

### ISSUE THREAD

**Issue by tonyhoo** [autogluon/autogluon#4556]
## Description:
Even though `quiet=True` is passed in the `nltk.download()` function calls, verbose output is still appearing when executing the [Beginner Text Prediction Tutorial](https://auto.gluon.ai/stable/tutorials/multimodal/text_prediction/beginner_text.html#training). The tutorial utilizes NLTK for text processing, and suppressing output from NLTK downloads is important for clean logs and user experience.

Steps to Reproduce:
	1. Follow the instructions from the [Beginner Text Prediction Tutorial](https://auto.gluon.ai/stable/tutorials/multimodal/text_prediction/beginner_text.html#training).
	2.Run the section that involves text processing with NLTK.
	3. Observe that despite setting quiet=True for nltk.download(), there is still output in the logs.

Expected Behavior:
When quiet=True is passed, no verbose output should appear during the NLTK download process.

Actual Behavior:
Output is still shown in the logs, indicating the download process of NLTK packages.
```
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ci/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
```

**Comment by tonyhoo** [comment]
It appears the issue emerged from [this commit](http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-4327/78d82af/tutorials/multimodal/multimodal_prediction/beginner_multimodal.html), as the previous one [here](http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-4325/c845911/tutorials/multimodal/multimodal_prediction/beginner_multimodal.html) does not exhibit the problem.

**Comment by LOYINuts** [comment]
This is still happening,where could be wrong? I just Follow the instructions from the [Beginner Text Prediction Tutorial](https://auto.gluon.ai/stable/tutorials/multimodal/text_prediction/beginner_text.html#training).
