### ISSUE TITLE
Bump transformers and accelerate versions

### ISSUE THREAD

**Issue by canerturkmen** [autogluon/autogluon#4595]
## Description
- The incoming Chronos version depends on `accelerate` version 0.32 and runs stable with version 0.34, which is the last version of `accelerate` before its v1.0 release. In AG, accelerate is capped at v0.22.
- Transformers dependency is also now 5 minor versions behind. Chronos runs stable with v4.39. The latest version is v4.46. AG cap is at 4.41.

This is a tracking issue to bump these dependencies to
```
"transformers[sentencepiece]": ">=4.39.0,<4.47",
"accelerate": ">=0.32,<1",
```

**Comment by tonyhoo** [comment]
updated at [PR](https://github.com/autogluon/autogluon/pull/4612)
