### ISSUE TITLE
[BUG]ONNX==1.10.0 can't be installed

### ISSUE THREAD

**Issue by ruichenhaoandlittlecap** [autogluon/autogluon#4620]
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      /tmp/pip-install-xetf3nx9/onnx_af1b3c6ed330409aa6548e86f40476ca/setup.py:36: DeprecationWarning: Use shutil.which instead of find_executable
        CMAKE = find_executable('cmake3') or find_executable('cmake')
      /tmp/pip-install-xetf3nx9/onnx_af1b3c6ed330409aa6548e86f40476ca/setup.py:37: DeprecationWarning: Use shutil.which instead of find_executable
        MAKE = find_executable('make')
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xetf3nx9/onnx_af1b3c6ed330409aa6548e86f40476ca/setup.py", line 318, in <module>
          raise FileNotFoundError("Unable to find " + requirements_file)
      FileNotFoundError: Unable to find requirements.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ruichenhaoandlittlecap** [comment]
I see this version relies on onnx==1.10.0. But this version of onnx can't be installed correctly because of its own bug.

**Comment by tonyhoo** [comment]
Thanks for reporting the issue! Could you please share the reproducible steps and any platform information?

**Comment by albertcthomas** [comment]
I'm having the same issue on Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64).
```
mamba create -n autogluon python=3.11
pip install autogluon
```
First I have
```
Collecting onnx (from optimum[onnxruntime]<1.19,>=1.17; extra == "all"->autogluon.timeseries[all]==1.1.1->autogluon)
  Using cached onnx-1.11.0.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      /tmp/pip-install-7jhzs4zv/onnx_d6828eae45004dbaaa62e4ee6d856a66/setup.py:36: DeprecationWarning: Use shutil.which instead of find_executable
        CMAKE = find_executable('cmake3') or find_executable('cmake')
      /tmp/pip-install-7jhzs4zv/onnx_d6828eae45004dbaaa62e4ee6d856a66/setup.py:37: DeprecationWarning: Use shutil.which instead of find_executable
        MAKE = find_executable('make')
      fatal: Not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7jhzs4zv/onnx_d6828eae45004dbaaa62e4ee6d856a66/setup.py", line 86, in <module>
          assert CMAKE, 'Could not find "cmake" executable!'
      AssertionError: Could not find "cmake" executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```
so I did `mamba install cmake`. Then I had the same error as above
```
Collecting onnx (from optimum[onnxruntime]<1.19,>=1.17; extra == "all"->autogluon.timeseries[all]==1.1.1->autogluon)
  Using cached onnx-1.11.0.tar.gz (9.9 MB)
  Preparing metadata (setup.py) ... done
  Using cached onnx-1.10.2.tar.gz (9.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached onnx-1.10.1.tar.gz (10.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached onnx-1.10.0.tar.gz (10.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      /tmp/pip-install-vcew93bp/onnx_cfcf2e6fc6c44ce3b3dfd84f86731fc4/setup.py:36: DeprecationWarning: Use shutil.which instead of find_executable
        CMAKE = find_executable('cmake3') or find_executable('cmake')
      /tmp/pip-install-vcew93bp/onnx_cfcf2e6fc6c44ce3b3dfd84f86731fc4/setup.py:37: DeprecationWarning: Use shutil.which instead of find_executable
        MAKE = find_executable('make')
      fatal: Not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vcew93bp/onnx_cfcf2e6fc6c44ce3b3dfd84f86731fc4/setup.py", line 318, in <module>
          raise FileNotFoundError("Unable to find " + requirements_file)
      FileNotFoundError: Unable to find requirements.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mavileo** [comment]
Same for me, onnx 1.10.0 fails with the same error mentioned above with Python3.8 and Python3.11 and with Python3.10, I have this error:
`Collecting opt-einsum>=2.3.2                                                                                                         
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)                                                                              
     |████████████████████████████████| 65 kB 6.7 MB/s                                                                               
  Downloading opt_einsum-3.2.1-py3-none-any.whl (63 kB)                                                                              
     |████████████████████████████████| 63 kB 3.3 MB/s                                                                               
  Downloading opt_einsum-3.2.0-py3-none-any.whl (63 kB)                                                                              
     |████████████████████████████████| 63 kB 3.6 MB/s                                                                               
  Downloading opt_einsum-3.1.0.tar.gz (69 kB)                                                                                        
     |████████████████████████████████| 69 kB 6.7 MB/s                                                                               
ERROR: Exception:                                                                                                                    
Traceback (most recent call last):                                                                                                   
  File "/home/maxence/ml/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 173, in _main                    
    status = self.run(options, args)                                                                                                 
  File "/home/maxence/ml/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper                   
    return func(self, options, args)                                                                                                 
  File "/home/maxence/ml/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 315, in run                      
    requirement_set = resolver.resolve(                                                                                              
  File "/home/maxence/ml/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve     
    result = self._result = resolver.resolve(                                                                                        
  File "/home/maxence/ml/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve                
    state = resolution.resolve(requirements, max_rounds=max_rounds)                                                                  
  File "/home/maxence/ml/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 383, in resolve                
    raise ResolutionTooDeep(max_rounds)                                                                                              
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000`

**Comment by Innixma** [comment]
The current work-around is using `uv` for installation:

```
python -m pip install uv
python -m uv pip install autogluon
```

**Comment by albertcthomas** [comment]
Thanks a lot @Innixma ! Is it because uv handles dependencies differently?

**Comment by albertcthomas** [comment]
I confirm that the work-around works. Thanks again.

**Comment by 731315163** [comment]
I encountered the same issue.

**Comment by andylizf** [comment]
Thanks a lot @Innixma ! Solved my problem.
