### ISSUE TITLE
OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK3c105Error4whatEv

### ISSUE THREAD

**Issue by FelixNeutatz** [autogluon/autogluon#4679]
Hi,

unfortunately, the Google Colab: https://colab.research.google.com/github/autogluon/autogluon/blob/stable/docs/tutorials/multimodal/text_prediction/beginner_text.ipynb#scrollTo=d2535bb3

throws the following exception:

![image](https://github.com/user-attachments/assets/4caa6691-9150-43a6-9d47-5fcf57c6aa8e)

Thank you for your help.

Best regards,
Felix

**Comment by shchur** [comment]
Hi, Colab comes with pre-installed packages that result in conflicts when pytorch is updated. You should be able to fix the problem with
```
pip uninstall -q torchaudio torchvision torchtext
```

**Comment by suzhoum** [comment]
Confirming that this happens in Kaggle Notebook as well.
`pip uninstall -y torchaudio torchvision` would resolve the issue.
Will close the issue for now.
