### ISSUE TITLE
Tabular Feature Engineering on Large Datasets

### ISSUE THREAD

**Issue by jrdzha** [autogluon/autogluon#545]
I am specifically interested in using Autogluon's feature engineering. My question is if this is something that can be exposed to the end user?

Also, I've noticed that Autogluon's tabular data import requires an Autogluon-specific table, but also works with pandas dataframe. However, it does not work with Dask dataframe. Are there plans to make Autogluon compatible with other distributed large-scale data systems (I'm specifically interested in the feature engineering aspect)?

**Comment by Innixma** [comment]
In the next 1-2 months we plan to refactor the API of AutoGluon to enable the use of the feature engineering exclusively without needing to also train models.

For now, you can hack around this by training a very simple model and never using it:

```
predictor = task.fit(..., hyperparameters={'LR': {}})
data_preprocessed = predictor.transform_features(dataset=data_raw)
```

Regarding the input format, it is actually just a wrapper to the pandas DataFrame, and therefore anything that shares the same functionality as the pandas DataFrame should be compatible.

I am not familiar with how exactly how the dask DataFrame differs from normal pandas, but someone would have to look into this and contribute the functionality to pass it into the feature preprocessor. We welcome any contributions to this issue!

**Comment by jrdzha** [comment]
Thanks, then my followup question is this: I've noticed that the nlp function for feature engineering creates different number of features based on how the number of rows its given. For a large dataset, would I be able to break my table into, say 10 sub-tables, run feature engineering in parallel on each of these, then join back somehow, with the resulting dataframe the same as if I had just run the feature engineering on a single large dataframe?

**Comment by Innixma** [comment]
Great question. As of right now it would be very difficult, if not impossible, to parallelize feature engineering during training fully, as we use a CountVectorizer for text, which requires all of the text data at once (or at least it isn't trivial to combine them in parallel). I had looked into this in the past, and I wasn't able to find a parallelized version of CountVectorizer.

However, it should be possible to make it parallelized during inference. The trick will be trying to outdo the overhead incurred by the parallel thread creation, and finding a way to avoid loading objects that take up a lot of memory many times. I have tried it in the past but wasn't able to make meaningful speedups for all of the instabilities it might have created.

Wrapping the existing inference functionality in something like EMR/Spark for clusters could work, with each core node having a copy of the preprocessor, but you will suffer overhead making it worthwhile primarily for very large datasets.

**Comment by jrdzha** [comment]
Ah I see. I'd be interested in parallelizing feature engineering if possible. Maybe I can play with this and see if I get anywhere. Is there any resource / reading for how autogluon is doing feature engineering? Thanks!

**Comment by jrdzha** [comment]
It seems like Spark has a countvectorizer. Is there anything that can be taken from their implementation?

**Comment by Innixma** [comment]
If you are interested in contributing to AutoGluon, please send me an email or confirm your interest in this thread and I can give you a link to our recently created developer slack channel where we can collaborate more closely.

The best way to look at how AutoGluon is doing feature engineering would be to look at the source code at present, as it hasn't been touched for a long time as we have been focusing on the modeling side of things.

I'd recommend our paper: https://arxiv.org/pdf/2003.06505.pdf

as well as the code: 
https://github.com/awslabs/autogluon/blob/master/autogluon/utils/tabular/features/abstract_feature_generator.py
https://github.com/awslabs/autogluon/blob/master/autogluon/utils/tabular/features/auto_ml_feature_generator.py

The full feature engineering process occurs between the start of Learner.fit() and the creation of the Trainer object:

https://github.com/awslabs/autogluon/blob/master/autogluon/utils/tabular/ml/learner/default_learner.py#L32

This is where the feature_generator is fit: https://github.com/awslabs/autogluon/blob/master/autogluon/utils/tabular/ml/learner/abstract_learner.py#L210

Stepping through it with a debugger and breakpoints on a toy problem will be the most insightful.

> It seems like Spark has a countvectorizer. Is there anything that can be taken from their implementation?

Unsure, I have never used Spark's countvectorizer, but do know that Spark should not be a required dependency of AutoGluon to avoid bloat, so it would either have to work as an optional functionality if Spark is present, or we would have to find a way to move it out of Spark.

**Comment by jrdzha** [comment]
@Innixma Thanks, I've sent you an email.

**Comment by Innixma** [comment]
@jrdzha Responded, thanks for your interest!
