### ISSUE TITLE
classifier.predict PIL object loading

### ISSUE THREAD

**Issue by Pentar0o** [autogluon/autogluon#925]
Hi, 

Will it be possible in a near future to be able to use a PIL Image object instead of a physical file in classifier.predict() ?

Regards.

**Comment by zhreshold** [comment]
@Pentar0o You can use numpy image with RGB layout in shape (H, W, 3), will try to add PIL image support in the future.

**Comment by Pentar0o** [comment]
So I tried this (tabofimage contains the content of the image in a PIL format) :
                ImageNumpy = np.asarray(tabofimage[1])
                indice, _, _ = classifier.predict(ImageNumpy)

And I get this following error : 
TypeError: cannot unpack non-iterable NoneType object

Did I misunderstand something in your answer ?

**Comment by zhreshold** [comment]
@Pentar0o can you post the stack trace of this particular error?

**Comment by Pentar0o** [comment]
Hope that help (tell me if you need more info) : 

The Code : 
                try:
                    ImageNumpy = np.asarray(lettre[1])
                except Exception as ex:
                    traceback.print_exception(type(ex), ex, ex.__traceback__)

                try:
                    indice, _, _ = classifier.predict(ImageNumpy)
                except Exception as ex:
                    traceback.print_exception(type(ex), ex, ex.__traceback__)

The Error : 


Le Print : [64, <PIL.Image.Image image mode=RGB size=105x210 at 0x7F2175BA5D90>]
Traceback (most recent call last):
  File "Lapinator.py", line 248, in main
    indice, _, _ = classifier.predict(ImageNumpy)
TypeError: cannot unpack non-iterable NoneType object
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "Lapinator.py", line 266, in <module>
    main(sys.argv[1])
  File "Lapinator.py", line 255, in main
    indice = indice.asnumpy()
UnboundLocalError: local variable 'indice' referenced before assignment
