### ISSUE TITLE
Align predict_proba behavior on regression problems

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#978]
Tabular and Text differ in predict_proba behavior on regression problems. They should be aligned for v0.1.

Option 1: Internally call predict and return predict output
- Tabular does this
- AbstractModel does this
- Increases flexibility for new users who may not understand the nuances of regression and predict_proba.

Option 2: Raise Exception
- Text does this
- May help avoid bugs in users code (Will return Series instead of what they may expect (DataFrame))

**Comment by Innixma** [comment]
@jwmueller @sxjscience @gradientsky @zhreshold Feel free to weigh in.

**Comment by sxjscience** [comment]
I'll vote for Option 2. `predict_proba` should be disabled if it's a regression problem. Raising an exception will make the life easier and avoid bugs.

**Comment by sxjscience** [comment]
I think the general rule is to always raise exceptions if the user is using the toolkit in any unexpected way.

**Comment by gradientsky** [comment]
I'll vote for Option 2 - this clears confusion for experienced users who deal with forecasting problems: they usually want the prediction with the confidence intervals.

**Comment by jwmueller** [comment]
I’m fine with either way. I think it’s not that confusing if predict_proba just calls predict for regression, and unlikely to introduce bugs unless the user didn’t even realize they’re working with a regression problem in the first place...

We are also in the process of adding quantile regression problem_type, but were planning to have a separate predict method for that problem.
I agree predict_proba could be nice to override in the future with some basic uncertainty estimate even for regular regression problem, so it may be better to free it up for that by disabling it now.

**Comment by Innixma** [comment]
I also think it is unlikely to produce bugs (What bug exactly would be produced that wouldn't already happen if this threw an exception?)

Regarding confidence intervals / quantiles, I think that may want to live in a separate method altogether.

I think this is a 2-way door, since we can always later add a deprecation warning to calls to predict_proba when problem type is regression, so I think we can delay this decision until after v0.1 and keep things as they are.

**Comment by Innixma** [comment]
#2684 marks predict_proba calls to regression as deprecated, raising an error starting in v0.8.

**Comment by Innixma** [comment]
Resolved by #3240
